<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class AccommodationInventoriesTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('accommodation_inventories')->delete();
        
        \DB::table('accommodation_inventories')->insert(array (
            0 => 
            array (
                'id' => 1,
                'accommodation_id' => 1,
                'room_type_id' => 1,
                'board_type_id' => 1,
                'check_in' => '2022-07-29 19:00:00',
                'check_in_time_confirmed' => 1,
                'check_out' => '2022-07-30 09:00:00',
                'check_out_time_confirmed' => 1,
                'fit_selectable' => 1,
                'stock' => 50,
                'purchase_price' => 25.0,
                'sales_price' => 40.0,
                'notes' => NULL,
                'created_at' => '2022-01-20 11:58:49',
                'updated_at' => '2022-01-20 11:58:49',
                'deleted_at' => NULL,
            ),
            1 => 
            array (
                'id' => 2,
                'accommodation_id' => 1,
                'room_type_id' => 1,
                'board_type_id' => 2,
                'check_in' => '2022-07-29 19:00:00',
                'check_in_time_confirmed' => 1,
                'check_out' => '2022-07-30 09:00:00',
                'check_out_time_confirmed' => 1,
                'fit_selectable' => 1,
                'stock' => 50,
                'purchase_price' => 30.0,
                'sales_price' => 45.0,
                'notes' => NULL,
                'created_at' => '2022-01-20 11:58:55',
                'updated_at' => '2022-01-20 12:00:38',
                'deleted_at' => NULL,
            ),
            2 => 
            array (
                'id' => 3,
                'accommodation_id' => 1,
                'room_type_id' => 2,
                'board_type_id' => 1,
                'check_in' => '2022-07-29 19:00:00',
                'check_in_time_confirmed' => 1,
                'check_out' => '2022-07-30 09:00:00',
                'check_out_time_confirmed' => 1,
                'fit_selectable' => 1,
                'stock' => 50,
                'purchase_price' => 30.0,
                'sales_price' => 45.0,
                'notes' => NULL,
                'created_at' => '2022-01-20 11:59:14',
                'updated_at' => '2022-01-20 11:59:40',
                'deleted_at' => NULL,
            ),
            3 => 
            array (
                'id' => 4,
                'accommodation_id' => 1,
                'room_type_id' => 2,
                'board_type_id' => 2,
                'check_in' => '2022-07-29 19:00:00',
                'check_in_time_confirmed' => 1,
                'check_out' => '2022-07-30 09:00:00',
                'check_out_time_confirmed' => 1,
                'fit_selectable' => 1,
                'stock' => 50,
                'purchase_price' => 40.0,
                'sales_price' => 60.0,
                'notes' => NULL,
                'created_at' => '2022-01-20 12:00:15',
                'updated_at' => '2022-01-20 12:00:25',
                'deleted_at' => NULL,
            ),
            4 => 
            array (
                'id' => 5,
                'accommodation_id' => 1,
                'room_type_id' => 1,
                'board_type_id' => 1,
                'check_in' => '2022-07-30 19:00:00',
                'check_in_time_confirmed' => 1,
                'check_out' => '2022-08-01 09:00:00',
                'check_out_time_confirmed' => 1,
                'fit_selectable' => 1,
                'stock' => 50,
                'purchase_price' => 25.0,
                'sales_price' => 40.0,
                'notes' => NULL,
                'created_at' => '2022-01-20 11:58:49',
                'updated_at' => '2022-01-20 11:58:49',
                'deleted_at' => NULL,
            ),
            5 => 
            array (
                'id' => 6,
                'accommodation_id' => 1,
                'room_type_id' => 1,
                'board_type_id' => 2,
                'check_in' => '2022-07-30 19:00:00',
                'check_in_time_confirmed' => 1,
                'check_out' => '2022-08-01 09:00:00',
                'check_out_time_confirmed' => 1,
                'fit_selectable' => 1,
                'stock' => 50,
                'purchase_price' => 30.0,
                'sales_price' => 45.0,
                'notes' => NULL,
                'created_at' => '2022-01-20 11:58:55',
                'updated_at' => '2022-01-20 12:00:38',
                'deleted_at' => NULL,
            ),
            6 => 
            array (
                'id' => 7,
                'accommodation_id' => 1,
                'room_type_id' => 2,
                'board_type_id' => 1,
                'check_in' => '2022-07-30 19:00:00',
                'check_in_time_confirmed' => 1,
                'check_out' => '2022-08-01 09:00:00',
                'check_out_time_confirmed' => 1,
                'fit_selectable' => 1,
                'stock' => 50,
                'purchase_price' => 30.0,
                'sales_price' => 45.0,
                'notes' => NULL,
                'created_at' => '2022-01-20 11:59:14',
                'updated_at' => '2022-01-20 11:59:40',
                'deleted_at' => NULL,
            ),
            7 => 
            array (
                'id' => 8,
                'accommodation_id' => 1,
                'room_type_id' => 2,
                'board_type_id' => 2,
                'check_in' => '2022-07-30 19:00:00',
                'check_in_time_confirmed' => 1,
                'check_out' => '2022-08-01 09:00:00',
                'check_out_time_confirmed' => 1,
                'fit_selectable' => 1,
                'stock' => 50,
                'purchase_price' => 40.0,
                'sales_price' => 60.0,
                'notes' => NULL,
                'created_at' => '2022-01-20 12:00:15',
                'updated_at' => '2022-01-20 12:00:25',
                'deleted_at' => NULL,
            ),
            8 => 
            array (
                'id' => 9,
                'accommodation_id' => 1,
                'room_type_id' => 1,
                'board_type_id' => 1,
                'check_in' => '2022-08-01 19:00:00',
                'check_in_time_confirmed' => 1,
                'check_out' => '2022-08-02 09:00:00',
                'check_out_time_confirmed' => 1,
                'fit_selectable' => 1,
                'stock' => 50,
                'purchase_price' => 25.0,
                'sales_price' => 40.0,
                'notes' => NULL,
                'created_at' => '2022-01-20 11:58:49',
                'updated_at' => '2022-01-20 11:58:49',
                'deleted_at' => NULL,
            ),
            9 => 
            array (
                'id' => 10,
                'accommodation_id' => 1,
                'room_type_id' => 1,
                'board_type_id' => 2,
                'check_in' => '2022-08-01 19:00:00',
                'check_in_time_confirmed' => 1,
                'check_out' => '2022-08-02 09:00:00',
                'check_out_time_confirmed' => 1,
                'fit_selectable' => 1,
                'stock' => 50,
                'purchase_price' => 30.0,
                'sales_price' => 45.0,
                'notes' => NULL,
                'created_at' => '2022-01-20 11:58:55',
                'updated_at' => '2022-01-20 12:00:38',
                'deleted_at' => NULL,
            ),
            10 => 
            array (
                'id' => 11,
                'accommodation_id' => 1,
                'room_type_id' => 2,
                'board_type_id' => 1,
                'check_in' => '2022-08-01 19:00:00',
                'check_in_time_confirmed' => 1,
                'check_out' => '2022-08-02 09:00:00',
                'check_out_time_confirmed' => 1,
                'fit_selectable' => 1,
                'stock' => 50,
                'purchase_price' => 30.0,
                'sales_price' => 45.0,
                'notes' => NULL,
                'created_at' => '2022-01-20 11:59:14',
                'updated_at' => '2022-01-20 11:59:40',
                'deleted_at' => NULL,
            ),
            11 => 
            array (
                'id' => 12,
                'accommodation_id' => 1,
                'room_type_id' => 2,
                'board_type_id' => 2,
                'check_in' => '2022-08-01 19:00:00',
                'check_in_time_confirmed' => 1,
                'check_out' => '2022-08-02 09:00:00',
                'check_out_time_confirmed' => 1,
                'fit_selectable' => 1,
                'stock' => 50,
                'purchase_price' => 40.0,
                'sales_price' => 60.0,
                'notes' => NULL,
                'created_at' => '2022-01-20 12:00:15',
                'updated_at' => '2022-01-20 12:00:25',
                'deleted_at' => NULL,
            ),
            12 => 
            array (
                'id' => 13,
                'accommodation_id' => 1,
                'room_type_id' => 1,
                'board_type_id' => 1,
                'check_in' => '2022-08-02 19:00:00',
                'check_in_time_confirmed' => 1,
                'check_out' => '2022-08-03 09:00:00',
                'check_out_time_confirmed' => 1,
                'fit_selectable' => 1,
                'stock' => 50,
                'purchase_price' => 25.0,
                'sales_price' => 40.0,
                'notes' => NULL,
                'created_at' => '2022-01-20 11:58:49',
                'updated_at' => '2022-01-20 11:58:49',
                'deleted_at' => NULL,
            ),
            13 => 
            array (
                'id' => 14,
                'accommodation_id' => 1,
                'room_type_id' => 1,
                'board_type_id' => 2,
                'check_in' => '2022-08-02 19:00:00',
                'check_in_time_confirmed' => 1,
                'check_out' => '2022-08-03 09:00:00',
                'check_out_time_confirmed' => 1,
                'fit_selectable' => 1,
                'stock' => 50,
                'purchase_price' => 30.0,
                'sales_price' => 45.0,
                'notes' => NULL,
                'created_at' => '2022-01-20 11:58:55',
                'updated_at' => '2022-01-20 12:00:38',
                'deleted_at' => NULL,
            ),
            14 => 
            array (
                'id' => 15,
                'accommodation_id' => 1,
                'room_type_id' => 2,
                'board_type_id' => 1,
                'check_in' => '2022-08-02 19:00:00',
                'check_in_time_confirmed' => 1,
                'check_out' => '2022-08-03 09:00:00',
                'check_out_time_confirmed' => 1,
                'fit_selectable' => 1,
                'stock' => 50,
                'purchase_price' => 30.0,
                'sales_price' => 45.0,
                'notes' => NULL,
                'created_at' => '2022-01-20 11:59:14',
                'updated_at' => '2022-01-20 11:59:40',
                'deleted_at' => NULL,
            ),
            15 => 
            array (
                'id' => 16,
                'accommodation_id' => 1,
                'room_type_id' => 2,
                'board_type_id' => 2,
                'check_in' => '2022-08-02 19:00:00',
                'check_in_time_confirmed' => 1,
                'check_out' => '2022-08-03 09:00:00',
                'check_out_time_confirmed' => 1,
                'fit_selectable' => 1,
                'stock' => 50,
                'purchase_price' => 40.0,
                'sales_price' => 60.0,
                'notes' => NULL,
                'created_at' => '2022-01-20 12:00:15',
                'updated_at' => '2022-01-20 12:00:25',
                'deleted_at' => NULL,
            ),
            16 => 
            array (
                'id' => 17,
                'accommodation_id' => 1,
                'room_type_id' => 1,
                'board_type_id' => 1,
                'check_in' => '2022-08-03 19:00:00',
                'check_in_time_confirmed' => 1,
                'check_out' => '2022-08-04 09:00:00',
                'check_out_time_confirmed' => 1,
                'fit_selectable' => 1,
                'stock' => 50,
                'purchase_price' => 25.0,
                'sales_price' => 40.0,
                'notes' => NULL,
                'created_at' => '2022-01-20 11:58:49',
                'updated_at' => '2022-01-20 11:58:49',
                'deleted_at' => NULL,
            ),
            17 => 
            array (
                'id' => 18,
                'accommodation_id' => 1,
                'room_type_id' => 1,
                'board_type_id' => 2,
                'check_in' => '2022-08-03 19:00:00',
                'check_in_time_confirmed' => 1,
                'check_out' => '2022-08-04 09:00:00',
                'check_out_time_confirmed' => 1,
                'fit_selectable' => 1,
                'stock' => 50,
                'purchase_price' => 30.0,
                'sales_price' => 45.0,
                'notes' => NULL,
                'created_at' => '2022-01-20 11:58:55',
                'updated_at' => '2022-01-20 12:00:38',
                'deleted_at' => NULL,
            ),
            18 => 
            array (
                'id' => 19,
                'accommodation_id' => 1,
                'room_type_id' => 2,
                'board_type_id' => 1,
                'check_in' => '2022-08-03 19:00:00',
                'check_in_time_confirmed' => 1,
                'check_out' => '2022-08-04 09:00:00',
                'check_out_time_confirmed' => 1,
                'fit_selectable' => 1,
                'stock' => 50,
                'purchase_price' => 30.0,
                'sales_price' => 45.0,
                'notes' => NULL,
                'created_at' => '2022-01-20 11:59:14',
                'updated_at' => '2022-01-20 11:59:40',
                'deleted_at' => NULL,
            ),
            19 => 
            array (
                'id' => 20,
                'accommodation_id' => 1,
                'room_type_id' => 2,
                'board_type_id' => 2,
                'check_in' => '2022-08-03 19:00:00',
                'check_in_time_confirmed' => 1,
                'check_out' => '2022-08-04 09:00:00',
                'check_out_time_confirmed' => 1,
                'fit_selectable' => 1,
                'stock' => 50,
                'purchase_price' => 40.0,
                'sales_price' => 60.0,
                'notes' => NULL,
                'created_at' => '2022-01-20 12:00:15',
                'updated_at' => '2022-01-20 12:00:25',
                'deleted_at' => NULL,
            ),
            20 => 
            array (
                'id' => 21,
                'accommodation_id' => 2,
                'room_type_id' => 1,
                'board_type_id' => 1,
                'check_in' => '2022-08-04 19:00:00',
                'check_in_time_confirmed' => 1,
                'check_out' => '2022-08-05 09:00:00',
                'check_out_time_confirmed' => 1,
                'fit_selectable' => 1,
                'stock' => 50,
                'purchase_price' => 25.0,
                'sales_price' => 40.0,
                'notes' => NULL,
                'created_at' => '2022-01-20 11:58:49',
                'updated_at' => '2022-01-20 11:58:49',
                'deleted_at' => NULL,
            ),
            21 => 
            array (
                'id' => 22,
                'accommodation_id' => 2,
                'room_type_id' => 1,
                'board_type_id' => 2,
                'check_in' => '2022-08-04 19:00:00',
                'check_in_time_confirmed' => 1,
                'check_out' => '2022-08-05 09:00:00',
                'check_out_time_confirmed' => 1,
                'fit_selectable' => 1,
                'stock' => 50,
                'purchase_price' => 30.0,
                'sales_price' => 45.0,
                'notes' => NULL,
                'created_at' => '2022-01-20 11:58:55',
                'updated_at' => '2022-01-20 12:00:38',
                'deleted_at' => NULL,
            ),
            22 => 
            array (
                'id' => 23,
                'accommodation_id' => 2,
                'room_type_id' => 2,
                'board_type_id' => 1,
                'check_in' => '2022-08-04 19:00:00',
                'check_in_time_confirmed' => 1,
                'check_out' => '2022-08-05 09:00:00',
                'check_out_time_confirmed' => 1,
                'fit_selectable' => 1,
                'stock' => 50,
                'purchase_price' => 30.0,
                'sales_price' => 45.0,
                'notes' => NULL,
                'created_at' => '2022-01-20 11:59:14',
                'updated_at' => '2022-01-20 11:59:40',
                'deleted_at' => NULL,
            ),
            23 => 
            array (
                'id' => 24,
                'accommodation_id' => 2,
                'room_type_id' => 2,
                'board_type_id' => 2,
                'check_in' => '2022-08-04 19:00:00',
                'check_in_time_confirmed' => 1,
                'check_out' => '2022-08-05 09:00:00',
                'check_out_time_confirmed' => 1,
                'fit_selectable' => 1,
                'stock' => 50,
                'purchase_price' => 40.0,
                'sales_price' => 60.0,
                'notes' => NULL,
                'created_at' => '2022-01-20 12:00:15',
                'updated_at' => '2022-01-20 12:00:25',
                'deleted_at' => NULL,
            ),
            24 => 
            array (
                'id' => 25,
                'accommodation_id' => 2,
                'room_type_id' => 1,
                'board_type_id' => 1,
                'check_in' => '2022-08-05 19:00:00',
                'check_in_time_confirmed' => 1,
                'check_out' => '2022-08-06 09:00:00',
                'check_out_time_confirmed' => 1,
                'fit_selectable' => 1,
                'stock' => 50,
                'purchase_price' => 25.0,
                'sales_price' => 40.0,
                'notes' => NULL,
                'created_at' => '2022-01-20 11:58:49',
                'updated_at' => '2022-01-20 11:58:49',
                'deleted_at' => NULL,
            ),
            25 => 
            array (
                'id' => 26,
                'accommodation_id' => 2,
                'room_type_id' => 1,
                'board_type_id' => 2,
                'check_in' => '2022-08-05 19:00:00',
                'check_in_time_confirmed' => 1,
                'check_out' => '2022-08-06 09:00:00',
                'check_out_time_confirmed' => 1,
                'fit_selectable' => 1,
                'stock' => 50,
                'purchase_price' => 30.0,
                'sales_price' => 45.0,
                'notes' => NULL,
                'created_at' => '2022-01-20 11:58:55',
                'updated_at' => '2022-01-20 12:00:38',
                'deleted_at' => NULL,
            ),
            26 => 
            array (
                'id' => 27,
                'accommodation_id' => 2,
                'room_type_id' => 2,
                'board_type_id' => 1,
                'check_in' => '2022-08-05 19:00:00',
                'check_in_time_confirmed' => 1,
                'check_out' => '2022-08-06 09:00:00',
                'check_out_time_confirmed' => 1,
                'fit_selectable' => 1,
                'stock' => 50,
                'purchase_price' => 30.0,
                'sales_price' => 45.0,
                'notes' => NULL,
                'created_at' => '2022-01-20 11:59:14',
                'updated_at' => '2022-01-20 11:59:40',
                'deleted_at' => NULL,
            ),
            27 => 
            array (
                'id' => 28,
                'accommodation_id' => 2,
                'room_type_id' => 2,
                'board_type_id' => 2,
                'check_in' => '2022-08-05 19:00:00',
                'check_in_time_confirmed' => 1,
                'check_out' => '2022-08-06 09:00:00',
                'check_out_time_confirmed' => 1,
                'fit_selectable' => 1,
                'stock' => 50,
                'purchase_price' => 40.0,
                'sales_price' => 60.0,
                'notes' => NULL,
                'created_at' => '2022-01-20 12:00:15',
                'updated_at' => '2022-01-20 12:00:25',
                'deleted_at' => NULL,
            ),
            28 => 
            array (
                'id' => 29,
                'accommodation_id' => 2,
                'room_type_id' => 1,
                'board_type_id' => 1,
                'check_in' => '2022-08-06 19:00:00',
                'check_in_time_confirmed' => 1,
                'check_out' => '2022-08-07 09:00:00',
                'check_out_time_confirmed' => 1,
                'fit_selectable' => 1,
                'stock' => 50,
                'purchase_price' => 25.0,
                'sales_price' => 40.0,
                'notes' => NULL,
                'created_at' => '2022-01-20 11:58:49',
                'updated_at' => '2022-01-20 11:58:49',
                'deleted_at' => NULL,
            ),
            29 => 
            array (
                'id' => 30,
                'accommodation_id' => 2,
                'room_type_id' => 1,
                'board_type_id' => 2,
                'check_in' => '2022-08-06 19:00:00',
                'check_in_time_confirmed' => 1,
                'check_out' => '2022-08-07 09:00:00',
                'check_out_time_confirmed' => 1,
                'fit_selectable' => 1,
                'stock' => 50,
                'purchase_price' => 30.0,
                'sales_price' => 45.0,
                'notes' => NULL,
                'created_at' => '2022-01-20 11:58:55',
                'updated_at' => '2022-01-20 12:00:38',
                'deleted_at' => NULL,
            ),
            30 => 
            array (
                'id' => 31,
                'accommodation_id' => 2,
                'room_type_id' => 2,
                'board_type_id' => 1,
                'check_in' => '2022-08-06 19:00:00',
                'check_in_time_confirmed' => 1,
                'check_out' => '2022-08-07 09:00:00',
                'check_out_time_confirmed' => 1,
                'fit_selectable' => 1,
                'stock' => 50,
                'purchase_price' => 30.0,
                'sales_price' => 45.0,
                'notes' => NULL,
                'created_at' => '2022-01-20 11:59:14',
                'updated_at' => '2022-01-20 11:59:40',
                'deleted_at' => NULL,
            ),
            31 => 
            array (
                'id' => 32,
                'accommodation_id' => 2,
                'room_type_id' => 2,
                'board_type_id' => 2,
                'check_in' => '2022-08-06 19:00:00',
                'check_in_time_confirmed' => 1,
                'check_out' => '2022-08-07 09:00:00',
                'check_out_time_confirmed' => 1,
                'fit_selectable' => 1,
                'stock' => 50,
                'purchase_price' => 40.0,
                'sales_price' => 60.0,
                'notes' => NULL,
                'created_at' => '2022-01-20 12:00:15',
                'updated_at' => '2022-01-20 12:00:25',
                'deleted_at' => NULL,
            ),
            32 => 
            array (
                'id' => 33,
                'accommodation_id' => 2,
                'room_type_id' => 1,
                'board_type_id' => 1,
                'check_in' => '2022-08-07 19:00:00',
                'check_in_time_confirmed' => 1,
                'check_out' => '2022-08-08 09:00:00',
                'check_out_time_confirmed' => 1,
                'fit_selectable' => 1,
                'stock' => 50,
                'purchase_price' => 25.0,
                'sales_price' => 40.0,
                'notes' => NULL,
                'created_at' => '2022-01-20 11:58:49',
                'updated_at' => '2022-01-20 11:58:49',
                'deleted_at' => NULL,
            ),
            33 => 
            array (
                'id' => 34,
                'accommodation_id' => 2,
                'room_type_id' => 1,
                'board_type_id' => 2,
                'check_in' => '2022-08-07 19:00:00',
                'check_in_time_confirmed' => 1,
                'check_out' => '2022-08-08 09:00:00',
                'check_out_time_confirmed' => 1,
                'fit_selectable' => 1,
                'stock' => 50,
                'purchase_price' => 30.0,
                'sales_price' => 45.0,
                'notes' => NULL,
                'created_at' => '2022-01-20 11:58:55',
                'updated_at' => '2022-01-20 12:00:38',
                'deleted_at' => NULL,
            ),
            34 => 
            array (
                'id' => 35,
                'accommodation_id' => 2,
                'room_type_id' => 2,
                'board_type_id' => 1,
                'check_in' => '2022-08-07 19:00:00',
                'check_in_time_confirmed' => 1,
                'check_out' => '2022-08-08 09:00:00',
                'check_out_time_confirmed' => 1,
                'fit_selectable' => 1,
                'stock' => 50,
                'purchase_price' => 30.0,
                'sales_price' => 45.0,
                'notes' => NULL,
                'created_at' => '2022-01-20 11:59:14',
                'updated_at' => '2022-01-20 11:59:40',
                'deleted_at' => NULL,
            ),
            35 => 
            array (
                'id' => 36,
                'accommodation_id' => 2,
                'room_type_id' => 2,
                'board_type_id' => 2,
                'check_in' => '2022-08-07 19:00:00',
                'check_in_time_confirmed' => 1,
                'check_out' => '2022-08-08 09:00:00',
                'check_out_time_confirmed' => 1,
                'fit_selectable' => 1,
                'stock' => 50,
                'purchase_price' => 40.0,
                'sales_price' => 60.0,
                'notes' => NULL,
                'created_at' => '2022-01-20 12:00:15',
                'updated_at' => '2022-01-20 12:00:25',
                'deleted_at' => NULL,
            ),
        ));
    }
}
