<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class AccommodationInventoryToursTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('accommodation_inventory_tours')->delete();
        
        \DB::table('accommodation_inventory_tours')->insert(array (
            0 => 
            array (
                'id' => 1,
                'tour_id' => 1,
                'accommodation_inventory_id' => 3,
                'tour_sales_price' => '45.00',
                'is_template' => 1,
                'tour_component_type' => 'Included',
                'booking_policy' => 'overbook',
                'created_at' => '2022-01-20 12:51:19',
                'updated_at' => '2022-01-20 12:51:19',
                'deleted_at' => NULL,
                'is_bookable' => 1,
                'stock_control_active' => 0,
            ),
            1 => 
            array (
                'id' => 2,
                'tour_id' => 1,
                'accommodation_inventory_id' => 7,
                'tour_sales_price' => '45.00',
                'is_template' => 1,
                'tour_component_type' => 'Included',
                'booking_policy' => 'overbook',
                'created_at' => '2022-01-20 12:51:19',
                'updated_at' => '2022-01-20 12:51:19',
                'deleted_at' => NULL,
                'is_bookable' => 1,
                'stock_control_active' => 0,
            ),
            2 => 
            array (
                'id' => 3,
                'tour_id' => 1,
                'accommodation_inventory_id' => 11,
                'tour_sales_price' => '45.00',
                'is_template' => 1,
                'tour_component_type' => 'Included',
                'booking_policy' => 'overbook',
                'created_at' => '2022-01-20 12:51:19',
                'updated_at' => '2022-01-20 12:51:19',
                'deleted_at' => NULL,
                'is_bookable' => 1,
                'stock_control_active' => 0,
            ),
            3 => 
            array (
                'id' => 4,
                'tour_id' => 1,
                'accommodation_inventory_id' => 15,
                'tour_sales_price' => '45.00',
                'is_template' => 1,
                'tour_component_type' => 'Included',
                'booking_policy' => 'overbook',
                'created_at' => '2022-01-20 12:51:19',
                'updated_at' => '2022-01-20 12:51:19',
                'deleted_at' => NULL,
                'is_bookable' => 1,
                'stock_control_active' => 0,
            ),
            4 => 
            array (
                'id' => 5,
                'tour_id' => 1,
                'accommodation_inventory_id' => 19,
                'tour_sales_price' => '45.00',
                'is_template' => 1,
                'tour_component_type' => 'Included',
                'booking_policy' => 'overbook',
                'created_at' => '2022-01-20 12:51:19',
                'updated_at' => '2022-01-20 12:51:19',
                'deleted_at' => NULL,
                'is_bookable' => 1,
                'stock_control_active' => 0,
            ),
            5 => 
            array (
                'id' => 6,
                'tour_id' => 1,
                'accommodation_inventory_id' => 23,
                'tour_sales_price' => '45.00',
                'is_template' => 1,
                'tour_component_type' => 'Included',
                'booking_policy' => 'overbook',
                'created_at' => '2022-01-20 12:51:19',
                'updated_at' => '2022-01-20 12:51:19',
                'deleted_at' => NULL,
                'is_bookable' => 1,
                'stock_control_active' => 0,
            ),
            6 => 
            array (
                'id' => 7,
                'tour_id' => 1,
                'accommodation_inventory_id' => 27,
                'tour_sales_price' => '45.00',
                'is_template' => 1,
                'tour_component_type' => 'Included',
                'booking_policy' => 'overbook',
                'created_at' => '2022-01-20 12:51:19',
                'updated_at' => '2022-01-20 12:51:19',
                'deleted_at' => NULL,
                'is_bookable' => 1,
                'stock_control_active' => 0,
            ),
            7 => 
            array (
                'id' => 8,
                'tour_id' => 1,
                'accommodation_inventory_id' => 31,
                'tour_sales_price' => '45.00',
                'is_template' => 1,
                'tour_component_type' => 'Included',
                'booking_policy' => 'overbook',
                'created_at' => '2022-01-20 12:51:19',
                'updated_at' => '2022-01-20 12:51:19',
                'deleted_at' => NULL,
                'is_bookable' => 1,
                'stock_control_active' => 0,
            ),
            8 => 
            array (
                'id' => 9,
                'tour_id' => 1,
                'accommodation_inventory_id' => 35,
                'tour_sales_price' => '45.00',
                'is_template' => 1,
                'tour_component_type' => 'Included',
                'booking_policy' => 'overbook',
                'created_at' => '2022-01-20 12:51:19',
                'updated_at' => '2022-01-20 12:51:19',
                'deleted_at' => NULL,
                'is_bookable' => 1,
                'stock_control_active' => 0,
            ),
            9 => 
            array (
                'id' => 10,
                'tour_id' => 1,
                'accommodation_inventory_id' => 12,
                'tour_sales_price' => '20.00',
                'is_template' => 0,
                'tour_component_type' => 'Upgrade',
                'booking_policy' => 'overbook',
                'created_at' => '2022-01-20 12:56:34',
                'updated_at' => '2022-01-20 12:56:34',
                'deleted_at' => NULL,
                'is_bookable' => 1,
                'stock_control_active' => 0,
            ),
            10 => 
            array (
                'id' => 11,
                'tour_id' => 1,
                'accommodation_inventory_id' => 9,
                'tour_sales_price' => '50.00',
                'is_template' => 0,
                'tour_component_type' => 'Included',
                'booking_policy' => 'overbook',
                'created_at' => '2022-01-20 13:08:43',
                'updated_at' => '2022-01-20 13:08:43',
                'deleted_at' => NULL,
                'is_bookable' => 1,
                'stock_control_active' => 0,
            ),
            11 => 
            array (
                'id' => 12,
                'tour_id' => 1,
                'accommodation_inventory_id' => 10,
                'tour_sales_price' => '100.00',
                'is_template' => 0,
                'tour_component_type' => 'Upgrade',
                'booking_policy' => 'overbook',
                'created_at' => '2022-01-20 13:09:17',
                'updated_at' => '2022-01-20 13:09:17',
                'deleted_at' => NULL,
                'is_bookable' => 1,
                'stock_control_active' => 0,
            ),
            12 => 
            array (
                'id' => 13,
                'tour_id' => 1,
                'accommodation_inventory_id' => 8,
                'tour_sales_price' => '25.00',
                'is_template' => 0,
                'tour_component_type' => 'Upgrade',
                'booking_policy' => 'overbook',
                'created_at' => '2022-01-20 13:12:50',
                'updated_at' => '2022-01-20 13:12:50',
                'deleted_at' => NULL,
                'is_bookable' => 1,
                'stock_control_active' => 0,
            ),
            13 => 
            array (
                'id' => 14,
                'tour_id' => 1,
                'accommodation_inventory_id' => 5,
                'tour_sales_price' => '50.00',
                'is_template' => 0,
                'tour_component_type' => 'Included',
                'booking_policy' => 'overbook',
                'created_at' => '2022-01-20 13:13:03',
                'updated_at' => '2022-01-20 13:13:03',
                'deleted_at' => NULL,
                'is_bookable' => 1,
                'stock_control_active' => 0,
            ),
            14 => 
            array (
                'id' => 15,
                'tour_id' => 1,
                'accommodation_inventory_id' => 6,
                'tour_sales_price' => '75.00',
                'is_template' => 0,
                'tour_component_type' => 'Upgrade',
                'booking_policy' => 'overbook',
                'created_at' => '2022-01-20 13:13:16',
                'updated_at' => '2022-01-20 13:13:16',
                'deleted_at' => NULL,
                'is_bookable' => 1,
                'stock_control_active' => 0,
            ),
            15 => 
            array (
                'id' => 16,
                'tour_id' => 1,
                'accommodation_inventory_id' => 4,
                'tour_sales_price' => '25.00',
                'is_template' => 0,
                'tour_component_type' => 'Upgrade',
                'booking_policy' => 'overbook',
                'created_at' => '2022-01-20 13:13:55',
                'updated_at' => '2022-01-20 13:13:55',
                'deleted_at' => NULL,
                'is_bookable' => 1,
                'stock_control_active' => 0,
            ),
            16 => 
            array (
                'id' => 17,
                'tour_id' => 1,
                'accommodation_inventory_id' => 1,
                'tour_sales_price' => '50.00',
                'is_template' => 0,
                'tour_component_type' => 'Included',
                'booking_policy' => 'overbook',
                'created_at' => '2022-01-20 13:14:07',
                'updated_at' => '2022-01-20 13:14:07',
                'deleted_at' => NULL,
                'is_bookable' => 1,
                'stock_control_active' => 0,
            ),
            17 => 
            array (
                'id' => 18,
                'tour_id' => 1,
                'accommodation_inventory_id' => 2,
                'tour_sales_price' => '75.00',
                'is_template' => 0,
                'tour_component_type' => 'Upgrade',
                'booking_policy' => 'overbook',
                'created_at' => '2022-01-20 13:14:21',
                'updated_at' => '2022-01-20 13:14:21',
                'deleted_at' => NULL,
                'is_bookable' => 1,
                'stock_control_active' => 0,
            ),
            18 => 
            array (
                'id' => 19,
                'tour_id' => 1,
                'accommodation_inventory_id' => 36,
                'tour_sales_price' => '25.00',
                'is_template' => 0,
                'tour_component_type' => 'Upgrade',
                'booking_policy' => 'overbook',
                'created_at' => '2022-01-20 13:14:57',
                'updated_at' => '2022-01-20 13:14:57',
                'deleted_at' => NULL,
                'is_bookable' => 1,
                'stock_control_active' => 0,
            ),
            19 => 
            array (
                'id' => 20,
                'tour_id' => 1,
                'accommodation_inventory_id' => 33,
                'tour_sales_price' => '50.00',
                'is_template' => 0,
                'tour_component_type' => 'Included',
                'booking_policy' => 'overbook',
                'created_at' => '2022-01-20 13:15:19',
                'updated_at' => '2022-01-20 13:15:19',
                'deleted_at' => NULL,
                'is_bookable' => 1,
                'stock_control_active' => 0,
            ),
            20 => 
            array (
                'id' => 21,
                'tour_id' => 1,
                'accommodation_inventory_id' => 34,
                'tour_sales_price' => '75.00',
                'is_template' => 0,
                'tour_component_type' => 'Upgrade',
                'booking_policy' => 'overbook',
                'created_at' => '2022-01-20 13:15:28',
                'updated_at' => '2022-01-20 13:15:28',
                'deleted_at' => NULL,
                'is_bookable' => 1,
                'stock_control_active' => 0,
            ),
            21 => 
            array (
                'id' => 22,
                'tour_id' => 1,
                'accommodation_inventory_id' => 32,
                'tour_sales_price' => '25.00',
                'is_template' => 0,
                'tour_component_type' => 'Upgrade',
                'booking_policy' => 'overbook',
                'created_at' => '2022-01-20 13:16:30',
                'updated_at' => '2022-01-20 13:16:30',
                'deleted_at' => NULL,
                'is_bookable' => 1,
                'stock_control_active' => 0,
            ),
            22 => 
            array (
                'id' => 23,
                'tour_id' => 1,
                'accommodation_inventory_id' => 29,
                'tour_sales_price' => '50.00',
                'is_template' => 0,
                'tour_component_type' => 'Included',
                'booking_policy' => 'overbook',
                'created_at' => '2022-01-20 13:16:44',
                'updated_at' => '2022-01-20 13:16:44',
                'deleted_at' => NULL,
                'is_bookable' => 1,
                'stock_control_active' => 0,
            ),
            23 => 
            array (
                'id' => 24,
                'tour_id' => 1,
                'accommodation_inventory_id' => 30,
                'tour_sales_price' => '75.00',
                'is_template' => 0,
                'tour_component_type' => 'Upgrade',
                'booking_policy' => 'overbook',
                'created_at' => '2022-01-20 13:17:51',
                'updated_at' => '2022-01-20 13:17:51',
                'deleted_at' => NULL,
                'is_bookable' => 1,
                'stock_control_active' => 0,
            ),
            24 => 
            array (
                'id' => 25,
                'tour_id' => 1,
                'accommodation_inventory_id' => 28,
                'tour_sales_price' => '25.00',
                'is_template' => 0,
                'tour_component_type' => 'Upgrade',
                'booking_policy' => 'overbook',
                'created_at' => '2022-01-20 13:18:20',
                'updated_at' => '2022-01-20 13:18:20',
                'deleted_at' => NULL,
                'is_bookable' => 1,
                'stock_control_active' => 0,
            ),
            25 => 
            array (
                'id' => 26,
                'tour_id' => 1,
                'accommodation_inventory_id' => 25,
                'tour_sales_price' => '50.00',
                'is_template' => 0,
                'tour_component_type' => 'Included',
                'booking_policy' => 'overbook',
                'created_at' => '2022-01-20 13:18:34',
                'updated_at' => '2022-01-20 13:18:34',
                'deleted_at' => NULL,
                'is_bookable' => 1,
                'stock_control_active' => 0,
            ),
            26 => 
            array (
                'id' => 27,
                'tour_id' => 1,
                'accommodation_inventory_id' => 26,
                'tour_sales_price' => '75.00',
                'is_template' => 0,
                'tour_component_type' => 'Upgrade',
                'booking_policy' => 'overbook',
                'created_at' => '2022-01-20 13:18:47',
                'updated_at' => '2022-01-20 13:18:47',
                'deleted_at' => NULL,
                'is_bookable' => 1,
                'stock_control_active' => 0,
            ),
            27 => 
            array (
                'id' => 28,
                'tour_id' => 1,
                'accommodation_inventory_id' => 24,
                'tour_sales_price' => '25.00',
                'is_template' => 0,
                'tour_component_type' => 'Upgrade',
                'booking_policy' => 'overbook',
                'created_at' => '2022-01-20 13:19:12',
                'updated_at' => '2022-01-20 13:19:12',
                'deleted_at' => NULL,
                'is_bookable' => 1,
                'stock_control_active' => 0,
            ),
            28 => 
            array (
                'id' => 29,
                'tour_id' => 1,
                'accommodation_inventory_id' => 21,
                'tour_sales_price' => '50.00',
                'is_template' => 0,
                'tour_component_type' => 'Included',
                'booking_policy' => 'overbook',
                'created_at' => '2022-01-20 13:19:23',
                'updated_at' => '2022-01-20 13:19:23',
                'deleted_at' => NULL,
                'is_bookable' => 1,
                'stock_control_active' => 0,
            ),
            29 => 
            array (
                'id' => 30,
                'tour_id' => 1,
                'accommodation_inventory_id' => 22,
                'tour_sales_price' => '75.00',
                'is_template' => 0,
                'tour_component_type' => 'Upgrade',
                'booking_policy' => 'overbook',
                'created_at' => '2022-01-20 13:19:33',
                'updated_at' => '2022-01-20 13:19:33',
                'deleted_at' => NULL,
                'is_bookable' => 1,
                'stock_control_active' => 0,
            ),
            30 => 
            array (
                'id' => 31,
                'tour_id' => 1,
                'accommodation_inventory_id' => 20,
                'tour_sales_price' => '25.00',
                'is_template' => 0,
                'tour_component_type' => 'Upgrade',
                'booking_policy' => 'overbook',
                'created_at' => '2022-01-20 13:22:35',
                'updated_at' => '2022-01-20 13:22:35',
                'deleted_at' => NULL,
                'is_bookable' => 1,
                'stock_control_active' => 0,
            ),
            31 => 
            array (
                'id' => 32,
                'tour_id' => 1,
                'accommodation_inventory_id' => 17,
                'tour_sales_price' => '50.00',
                'is_template' => 0,
                'tour_component_type' => 'Included',
                'booking_policy' => 'overbook',
                'created_at' => '2022-01-20 13:22:46',
                'updated_at' => '2022-01-20 13:22:46',
                'deleted_at' => NULL,
                'is_bookable' => 1,
                'stock_control_active' => 0,
            ),
            32 => 
            array (
                'id' => 33,
                'tour_id' => 1,
                'accommodation_inventory_id' => 18,
                'tour_sales_price' => '75.00',
                'is_template' => 0,
                'tour_component_type' => 'Upgrade',
                'booking_policy' => 'overbook',
                'created_at' => '2022-01-20 13:22:57',
                'updated_at' => '2022-01-20 13:22:57',
                'deleted_at' => NULL,
                'is_bookable' => 1,
                'stock_control_active' => 0,
            ),
            33 => 
            array (
                'id' => 34,
                'tour_id' => 1,
                'accommodation_inventory_id' => 16,
                'tour_sales_price' => '25.00',
                'is_template' => 0,
                'tour_component_type' => 'Upgrade',
                'booking_policy' => 'overbook',
                'created_at' => '2022-01-20 13:23:35',
                'updated_at' => '2022-01-20 13:23:35',
                'deleted_at' => NULL,
                'is_bookable' => 1,
                'stock_control_active' => 0,
            ),
            34 => 
            array (
                'id' => 35,
                'tour_id' => 1,
                'accommodation_inventory_id' => 13,
                'tour_sales_price' => '50.00',
                'is_template' => 0,
                'tour_component_type' => 'Included',
                'booking_policy' => 'overbook',
                'created_at' => '2022-01-20 13:23:47',
                'updated_at' => '2022-01-20 13:23:47',
                'deleted_at' => NULL,
                'is_bookable' => 1,
                'stock_control_active' => 0,
            ),
            35 => 
            array (
                'id' => 36,
                'tour_id' => 1,
                'accommodation_inventory_id' => 14,
                'tour_sales_price' => '75.00',
                'is_template' => 0,
                'tour_component_type' => 'Upgrade',
                'booking_policy' => 'overbook',
                'created_at' => '2022-01-20 13:24:00',
                'updated_at' => '2022-01-20 13:24:00',
                'deleted_at' => NULL,
                'is_bookable' => 1,
                'stock_control_active' => 0,
            ),
            36 => 
            array (
                'id' => 37,
                'tour_id' => 1,
                'accommodation_inventory_id' => 37,
                'tour_sales_price' => '25.00',
                'is_template' => 0,
                'tour_component_type' => 'Included',
                'booking_policy' => 'overbook',
                'created_at' => '2022-02-09 09:34:21',
                'updated_at' => '2022-02-09 09:34:21',
                'deleted_at' => NULL,
                'is_bookable' => 1,
                'stock_control_active' => 0,
            ),
            37 => 
            array (
                'id' => 38,
                'tour_id' => 1,
                'accommodation_inventory_id' => 38,
                'tour_sales_price' => '25.00',
                'is_template' => 0,
                'tour_component_type' => 'Included',
                'booking_policy' => 'overbook',
                'created_at' => '2022-02-09 09:34:21',
                'updated_at' => '2022-02-09 09:34:21',
                'deleted_at' => NULL,
                'is_bookable' => 1,
                'stock_control_active' => 0,
            ),
            38 => 
            array (
                'id' => 39,
                'tour_id' => 1,
                'accommodation_inventory_id' => 39,
                'tour_sales_price' => '25.00',
                'is_template' => 0,
                'tour_component_type' => 'Included',
                'booking_policy' => 'overbook',
                'created_at' => '2022-02-09 09:34:21',
                'updated_at' => '2022-02-09 09:34:21',
                'deleted_at' => NULL,
                'is_bookable' => 1,
                'stock_control_active' => 0,
            ),
            39 => 
            array (
                'id' => 40,
                'tour_id' => 1,
                'accommodation_inventory_id' => 40,
                'tour_sales_price' => '25.00',
                'is_template' => 0,
                'tour_component_type' => 'Included',
                'booking_policy' => 'overbook',
                'created_at' => '2022-02-09 09:34:21',
                'updated_at' => '2022-02-09 09:34:21',
                'deleted_at' => NULL,
                'is_bookable' => 1,
                'stock_control_active' => 0,
            ),
            40 => 
            array (
                'id' => 41,
                'tour_id' => 1,
                'accommodation_inventory_id' => 41,
                'tour_sales_price' => '25.00',
                'is_template' => 0,
                'tour_component_type' => 'Included',
                'booking_policy' => 'overbook',
                'created_at' => '2022-02-09 09:34:21',
                'updated_at' => '2022-02-09 09:34:21',
                'deleted_at' => NULL,
                'is_bookable' => 1,
                'stock_control_active' => 0,
            ),
            41 => 
            array (
                'id' => 42,
                'tour_id' => 1,
                'accommodation_inventory_id' => 42,
                'tour_sales_price' => '25.00',
                'is_template' => 0,
                'tour_component_type' => 'Included',
                'booking_policy' => 'overbook',
                'created_at' => '2022-02-09 09:34:21',
                'updated_at' => '2022-02-09 09:34:21',
                'deleted_at' => NULL,
                'is_bookable' => 1,
                'stock_control_active' => 0,
            ),
            42 => 
            array (
                'id' => 43,
                'tour_id' => 1,
                'accommodation_inventory_id' => 43,
                'tour_sales_price' => '25.00',
                'is_template' => 0,
                'tour_component_type' => 'Included',
                'booking_policy' => 'overbook',
                'created_at' => '2022-02-09 09:34:21',
                'updated_at' => '2022-02-09 09:34:21',
                'deleted_at' => NULL,
                'is_bookable' => 1,
                'stock_control_active' => 0,
            ),
            43 => 
            array (
                'id' => 44,
                'tour_id' => 1,
                'accommodation_inventory_id' => 44,
                'tour_sales_price' => '25.00',
                'is_template' => 0,
                'tour_component_type' => 'Included',
                'booking_policy' => 'overbook',
                'created_at' => '2022-02-09 09:34:21',
                'updated_at' => '2022-02-09 09:34:21',
                'deleted_at' => NULL,
                'is_bookable' => 1,
                'stock_control_active' => 0,
            ),
            44 => 
            array (
                'id' => 45,
                'tour_id' => 1,
                'accommodation_inventory_id' => 45,
                'tour_sales_price' => '25.00',
                'is_template' => 0,
                'tour_component_type' => 'Included',
                'booking_policy' => 'overbook',
                'created_at' => '2022-02-09 09:34:21',
                'updated_at' => '2022-02-09 09:34:21',
                'deleted_at' => NULL,
                'is_bookable' => 1,
                'stock_control_active' => 0,
            ),
            45 => 
            array (
                'id' => 46,
                'tour_id' => 2,
                'accommodation_inventory_id' => 3,
                'tour_sales_price' => '45.00',
                'is_template' => 1,
                'tour_component_type' => 'Included',
                'booking_policy' => 'overbook',
                'created_at' => '2022-09-14 09:49:12',
                'updated_at' => '2022-09-14 09:53:49',
                'deleted_at' => '2022-09-14 09:53:49',
                'is_bookable' => 1,
                'stock_control_active' => 0,
            ),
            46 => 
            array (
                'id' => 47,
                'tour_id' => 2,
                'accommodation_inventory_id' => 4,
                'tour_sales_price' => '25.00',
                'is_template' => 0,
                'tour_component_type' => 'Upgrade',
                'booking_policy' => 'overbook',
                'created_at' => '2022-09-14 09:49:12',
                'updated_at' => '2022-09-14 09:53:51',
                'deleted_at' => '2022-09-14 09:53:51',
                'is_bookable' => 1,
                'stock_control_active' => 0,
            ),
            47 => 
            array (
                'id' => 48,
                'tour_id' => 2,
                'accommodation_inventory_id' => 1,
                'tour_sales_price' => '50.00',
                'is_template' => 0,
                'tour_component_type' => 'Included',
                'booking_policy' => 'overbook',
                'created_at' => '2022-09-14 09:49:12',
                'updated_at' => '2022-09-14 09:53:54',
                'deleted_at' => '2022-09-14 09:53:54',
                'is_bookable' => 1,
                'stock_control_active' => 0,
            ),
            48 => 
            array (
                'id' => 49,
                'tour_id' => 2,
                'accommodation_inventory_id' => 2,
                'tour_sales_price' => '75.00',
                'is_template' => 0,
                'tour_component_type' => 'Upgrade',
                'booking_policy' => 'overbook',
                'created_at' => '2022-09-14 09:49:12',
                'updated_at' => '2022-09-14 09:53:56',
                'deleted_at' => '2022-09-14 09:53:56',
                'is_bookable' => 1,
                'stock_control_active' => 0,
            ),
            49 => 
            array (
                'id' => 50,
                'tour_id' => 2,
                'accommodation_inventory_id' => 7,
                'tour_sales_price' => '45.00',
                'is_template' => 1,
                'tour_component_type' => 'Included',
                'booking_policy' => 'overbook',
                'created_at' => '2022-09-14 09:49:12',
                'updated_at' => '2022-09-14 09:54:00',
                'deleted_at' => '2022-09-14 09:54:00',
                'is_bookable' => 1,
                'stock_control_active' => 0,
            ),
            50 => 
            array (
                'id' => 51,
                'tour_id' => 2,
                'accommodation_inventory_id' => 8,
                'tour_sales_price' => '25.00',
                'is_template' => 0,
                'tour_component_type' => 'Upgrade',
                'booking_policy' => 'overbook',
                'created_at' => '2022-09-14 09:49:12',
                'updated_at' => '2022-09-14 09:54:02',
                'deleted_at' => '2022-09-14 09:54:02',
                'is_bookable' => 1,
                'stock_control_active' => 0,
            ),
            51 => 
            array (
                'id' => 52,
                'tour_id' => 2,
                'accommodation_inventory_id' => 5,
                'tour_sales_price' => '50.00',
                'is_template' => 0,
                'tour_component_type' => 'Included',
                'booking_policy' => 'overbook',
                'created_at' => '2022-09-14 09:49:12',
                'updated_at' => '2022-09-14 09:54:04',
                'deleted_at' => '2022-09-14 09:54:04',
                'is_bookable' => 1,
                'stock_control_active' => 0,
            ),
            52 => 
            array (
                'id' => 53,
                'tour_id' => 2,
                'accommodation_inventory_id' => 6,
                'tour_sales_price' => '75.00',
                'is_template' => 0,
                'tour_component_type' => 'Upgrade',
                'booking_policy' => 'overbook',
                'created_at' => '2022-09-14 09:49:12',
                'updated_at' => '2022-09-14 09:54:06',
                'deleted_at' => '2022-09-14 09:54:06',
                'is_bookable' => 1,
                'stock_control_active' => 0,
            ),
            53 => 
            array (
                'id' => 54,
                'tour_id' => 2,
                'accommodation_inventory_id' => 11,
                'tour_sales_price' => '45.00',
                'is_template' => 1,
                'tour_component_type' => 'Included',
                'booking_policy' => 'overbook',
                'created_at' => '2022-09-14 09:49:12',
                'updated_at' => '2022-09-14 09:51:21',
                'deleted_at' => '2022-09-14 09:51:21',
                'is_bookable' => 1,
                'stock_control_active' => 0,
            ),
            54 => 
            array (
                'id' => 55,
                'tour_id' => 2,
                'accommodation_inventory_id' => 12,
                'tour_sales_price' => '20.00',
                'is_template' => 0,
                'tour_component_type' => 'Upgrade',
                'booking_policy' => 'overbook',
                'created_at' => '2022-09-14 09:49:12',
                'updated_at' => '2022-09-14 09:52:21',
                'deleted_at' => '2022-09-14 09:52:21',
                'is_bookable' => 1,
                'stock_control_active' => 0,
            ),
            55 => 
            array (
                'id' => 56,
                'tour_id' => 2,
                'accommodation_inventory_id' => 9,
                'tour_sales_price' => '50.00',
                'is_template' => 0,
                'tour_component_type' => 'Included',
                'booking_policy' => 'overbook',
                'created_at' => '2022-09-14 09:49:12',
                'updated_at' => '2022-09-14 09:52:24',
                'deleted_at' => '2022-09-14 09:52:24',
                'is_bookable' => 1,
                'stock_control_active' => 0,
            ),
            56 => 
            array (
                'id' => 57,
                'tour_id' => 2,
                'accommodation_inventory_id' => 10,
                'tour_sales_price' => '100.00',
                'is_template' => 0,
                'tour_component_type' => 'Upgrade',
                'booking_policy' => 'overbook',
                'created_at' => '2022-09-14 09:49:12',
                'updated_at' => '2022-09-14 09:52:26',
                'deleted_at' => '2022-09-14 09:52:26',
                'is_bookable' => 1,
                'stock_control_active' => 0,
            ),
            57 => 
            array (
                'id' => 58,
                'tour_id' => 2,
                'accommodation_inventory_id' => 15,
                'tour_sales_price' => '45.00',
                'is_template' => 1,
                'tour_component_type' => 'Included',
                'booking_policy' => 'overbook',
                'created_at' => '2022-09-14 09:49:12',
                'updated_at' => '2022-09-14 09:52:31',
                'deleted_at' => '2022-09-14 09:52:31',
                'is_bookable' => 1,
                'stock_control_active' => 0,
            ),
            58 => 
            array (
                'id' => 59,
                'tour_id' => 2,
                'accommodation_inventory_id' => 16,
                'tour_sales_price' => '25.00',
                'is_template' => 0,
                'tour_component_type' => 'Upgrade',
                'booking_policy' => 'overbook',
                'created_at' => '2022-09-14 09:49:12',
                'updated_at' => '2022-09-14 09:52:34',
                'deleted_at' => '2022-09-14 09:52:34',
                'is_bookable' => 1,
                'stock_control_active' => 0,
            ),
            59 => 
            array (
                'id' => 60,
                'tour_id' => 2,
                'accommodation_inventory_id' => 13,
                'tour_sales_price' => '50.00',
                'is_template' => 0,
                'tour_component_type' => 'Included',
                'booking_policy' => 'overbook',
                'created_at' => '2022-09-14 09:49:12',
                'updated_at' => '2022-09-14 09:52:36',
                'deleted_at' => '2022-09-14 09:52:36',
                'is_bookable' => 1,
                'stock_control_active' => 0,
            ),
            60 => 
            array (
                'id' => 61,
                'tour_id' => 2,
                'accommodation_inventory_id' => 14,
                'tour_sales_price' => '75.00',
                'is_template' => 0,
                'tour_component_type' => 'Upgrade',
                'booking_policy' => 'overbook',
                'created_at' => '2022-09-14 09:49:12',
                'updated_at' => '2022-09-14 09:52:38',
                'deleted_at' => '2022-09-14 09:52:38',
                'is_bookable' => 1,
                'stock_control_active' => 0,
            ),
            61 => 
            array (
                'id' => 62,
                'tour_id' => 2,
                'accommodation_inventory_id' => 19,
                'tour_sales_price' => '45.00',
                'is_template' => 1,
                'tour_component_type' => 'Included',
                'booking_policy' => 'overbook',
                'created_at' => '2022-09-14 09:49:12',
                'updated_at' => '2022-09-14 09:52:52',
                'deleted_at' => '2022-09-14 09:52:52',
                'is_bookable' => 1,
                'stock_control_active' => 0,
            ),
            62 => 
            array (
                'id' => 63,
                'tour_id' => 2,
                'accommodation_inventory_id' => 20,
                'tour_sales_price' => '25.00',
                'is_template' => 0,
                'tour_component_type' => 'Upgrade',
                'booking_policy' => 'overbook',
                'created_at' => '2022-09-14 09:49:12',
                'updated_at' => '2022-09-14 09:52:54',
                'deleted_at' => '2022-09-14 09:52:54',
                'is_bookable' => 1,
                'stock_control_active' => 0,
            ),
            63 => 
            array (
                'id' => 64,
                'tour_id' => 2,
                'accommodation_inventory_id' => 17,
                'tour_sales_price' => '50.00',
                'is_template' => 0,
                'tour_component_type' => 'Included',
                'booking_policy' => 'overbook',
                'created_at' => '2022-09-14 09:49:12',
                'updated_at' => '2022-09-14 09:52:57',
                'deleted_at' => '2022-09-14 09:52:57',
                'is_bookable' => 1,
                'stock_control_active' => 0,
            ),
            64 => 
            array (
                'id' => 65,
                'tour_id' => 2,
                'accommodation_inventory_id' => 18,
                'tour_sales_price' => '75.00',
                'is_template' => 0,
                'tour_component_type' => 'Upgrade',
                'booking_policy' => 'overbook',
                'created_at' => '2022-09-14 09:49:12',
                'updated_at' => '2022-09-14 09:52:59',
                'deleted_at' => '2022-09-14 09:52:59',
                'is_bookable' => 1,
                'stock_control_active' => 0,
            ),
            65 => 
            array (
                'id' => 66,
                'tour_id' => 2,
                'accommodation_inventory_id' => 23,
                'tour_sales_price' => '45.00',
                'is_template' => 1,
                'tour_component_type' => 'Included',
                'booking_policy' => 'overbook',
                'created_at' => '2022-09-14 09:49:12',
                'updated_at' => '2022-09-14 09:53:04',
                'deleted_at' => '2022-09-14 09:53:04',
                'is_bookable' => 1,
                'stock_control_active' => 0,
            ),
            66 => 
            array (
                'id' => 67,
                'tour_id' => 2,
                'accommodation_inventory_id' => 24,
                'tour_sales_price' => '25.00',
                'is_template' => 0,
                'tour_component_type' => 'Upgrade',
                'booking_policy' => 'overbook',
                'created_at' => '2022-09-14 09:49:12',
                'updated_at' => '2022-09-14 09:53:06',
                'deleted_at' => '2022-09-14 09:53:06',
                'is_bookable' => 1,
                'stock_control_active' => 0,
            ),
            67 => 
            array (
                'id' => 68,
                'tour_id' => 2,
                'accommodation_inventory_id' => 21,
                'tour_sales_price' => '50.00',
                'is_template' => 0,
                'tour_component_type' => 'Included',
                'booking_policy' => 'overbook',
                'created_at' => '2022-09-14 09:49:12',
                'updated_at' => '2022-09-14 09:53:09',
                'deleted_at' => '2022-09-14 09:53:09',
                'is_bookable' => 1,
                'stock_control_active' => 0,
            ),
            68 => 
            array (
                'id' => 69,
                'tour_id' => 2,
                'accommodation_inventory_id' => 22,
                'tour_sales_price' => '75.00',
                'is_template' => 0,
                'tour_component_type' => 'Upgrade',
                'booking_policy' => 'overbook',
                'created_at' => '2022-09-14 09:49:12',
                'updated_at' => '2022-09-14 09:53:12',
                'deleted_at' => '2022-09-14 09:53:12',
                'is_bookable' => 1,
                'stock_control_active' => 0,
            ),
            69 => 
            array (
                'id' => 70,
                'tour_id' => 2,
                'accommodation_inventory_id' => 27,
                'tour_sales_price' => '45.00',
                'is_template' => 1,
                'tour_component_type' => 'Included',
                'booking_policy' => 'overbook',
                'created_at' => '2022-09-14 09:49:12',
                'updated_at' => '2022-09-14 09:53:18',
                'deleted_at' => '2022-09-14 09:53:18',
                'is_bookable' => 1,
                'stock_control_active' => 0,
            ),
            70 => 
            array (
                'id' => 71,
                'tour_id' => 2,
                'accommodation_inventory_id' => 28,
                'tour_sales_price' => '25.00',
                'is_template' => 0,
                'tour_component_type' => 'Upgrade',
                'booking_policy' => 'overbook',
                'created_at' => '2022-09-14 09:49:12',
                'updated_at' => '2022-09-14 09:53:21',
                'deleted_at' => '2022-09-14 09:53:21',
                'is_bookable' => 1,
                'stock_control_active' => 0,
            ),
            71 => 
            array (
                'id' => 72,
                'tour_id' => 2,
                'accommodation_inventory_id' => 25,
                'tour_sales_price' => '50.00',
                'is_template' => 0,
                'tour_component_type' => 'Included',
                'booking_policy' => 'overbook',
                'created_at' => '2022-09-14 09:49:12',
                'updated_at' => '2022-09-14 09:53:23',
                'deleted_at' => '2022-09-14 09:53:23',
                'is_bookable' => 1,
                'stock_control_active' => 0,
            ),
            72 => 
            array (
                'id' => 73,
                'tour_id' => 2,
                'accommodation_inventory_id' => 26,
                'tour_sales_price' => '75.00',
                'is_template' => 0,
                'tour_component_type' => 'Upgrade',
                'booking_policy' => 'overbook',
                'created_at' => '2022-09-14 09:49:12',
                'updated_at' => '2022-09-14 09:53:25',
                'deleted_at' => '2022-09-14 09:53:25',
                'is_bookable' => 1,
                'stock_control_active' => 0,
            ),
            73 => 
            array (
                'id' => 74,
                'tour_id' => 2,
                'accommodation_inventory_id' => 31,
                'tour_sales_price' => '45.00',
                'is_template' => 1,
                'tour_component_type' => 'Included',
                'booking_policy' => 'overbook',
                'created_at' => '2022-09-14 09:49:12',
                'updated_at' => '2022-09-14 09:53:29',
                'deleted_at' => '2022-09-14 09:53:29',
                'is_bookable' => 1,
                'stock_control_active' => 0,
            ),
            74 => 
            array (
                'id' => 75,
                'tour_id' => 2,
                'accommodation_inventory_id' => 32,
                'tour_sales_price' => '25.00',
                'is_template' => 0,
                'tour_component_type' => 'Upgrade',
                'booking_policy' => 'overbook',
                'created_at' => '2022-09-14 09:49:12',
                'updated_at' => '2022-09-14 09:53:31',
                'deleted_at' => '2022-09-14 09:53:31',
                'is_bookable' => 1,
                'stock_control_active' => 0,
            ),
            75 => 
            array (
                'id' => 76,
                'tour_id' => 2,
                'accommodation_inventory_id' => 29,
                'tour_sales_price' => '50.00',
                'is_template' => 0,
                'tour_component_type' => 'Included',
                'booking_policy' => 'overbook',
                'created_at' => '2022-09-14 09:49:12',
                'updated_at' => '2022-09-14 09:53:33',
                'deleted_at' => '2022-09-14 09:53:33',
                'is_bookable' => 1,
                'stock_control_active' => 0,
            ),
            76 => 
            array (
                'id' => 77,
                'tour_id' => 2,
                'accommodation_inventory_id' => 30,
                'tour_sales_price' => '75.00',
                'is_template' => 0,
                'tour_component_type' => 'Upgrade',
                'booking_policy' => 'overbook',
                'created_at' => '2022-09-14 09:49:12',
                'updated_at' => '2022-09-14 09:53:35',
                'deleted_at' => '2022-09-14 09:53:35',
                'is_bookable' => 1,
                'stock_control_active' => 0,
            ),
            77 => 
            array (
                'id' => 78,
                'tour_id' => 2,
                'accommodation_inventory_id' => 35,
                'tour_sales_price' => '45.00',
                'is_template' => 1,
                'tour_component_type' => 'Included',
                'booking_policy' => 'overbook',
                'created_at' => '2022-09-14 09:49:12',
                'updated_at' => '2022-09-14 09:53:40',
                'deleted_at' => '2022-09-14 09:53:40',
                'is_bookable' => 1,
                'stock_control_active' => 0,
            ),
            78 => 
            array (
                'id' => 79,
                'tour_id' => 2,
                'accommodation_inventory_id' => 36,
                'tour_sales_price' => '25.00',
                'is_template' => 0,
                'tour_component_type' => 'Upgrade',
                'booking_policy' => 'overbook',
                'created_at' => '2022-09-14 09:49:12',
                'updated_at' => '2022-09-14 09:53:41',
                'deleted_at' => '2022-09-14 09:53:41',
                'is_bookable' => 1,
                'stock_control_active' => 0,
            ),
            79 => 
            array (
                'id' => 80,
                'tour_id' => 2,
                'accommodation_inventory_id' => 33,
                'tour_sales_price' => '50.00',
                'is_template' => 0,
                'tour_component_type' => 'Included',
                'booking_policy' => 'overbook',
                'created_at' => '2022-09-14 09:49:12',
                'updated_at' => '2022-09-14 09:53:43',
                'deleted_at' => '2022-09-14 09:53:43',
                'is_bookable' => 1,
                'stock_control_active' => 0,
            ),
            80 => 
            array (
                'id' => 81,
                'tour_id' => 2,
                'accommodation_inventory_id' => 34,
                'tour_sales_price' => '75.00',
                'is_template' => 0,
                'tour_component_type' => 'Upgrade',
                'booking_policy' => 'overbook',
                'created_at' => '2022-09-14 09:49:12',
                'updated_at' => '2022-09-14 09:53:45',
                'deleted_at' => '2022-09-14 09:53:45',
                'is_bookable' => 1,
                'stock_control_active' => 0,
            ),
            81 => 
            array (
                'id' => 82,
                'tour_id' => 2,
                'accommodation_inventory_id' => 9,
                'tour_sales_price' => '50.00',
                'is_template' => 0,
                'tour_component_type' => 'Included',
                'booking_policy' => 'overbook',
                'created_at' => '2022-09-14 09:49:12',
                'updated_at' => '2022-09-14 09:52:28',
                'deleted_at' => '2022-09-14 09:52:28',
                'is_bookable' => 1,
                'stock_control_active' => 0,
            ),
            82 => 
            array (
                'id' => 83,
                'tour_id' => 2,
                'accommodation_inventory_id' => 5,
                'tour_sales_price' => '50.00',
                'is_template' => 0,
                'tour_component_type' => 'Included',
                'booking_policy' => 'overbook',
                'created_at' => '2022-09-14 09:49:12',
                'updated_at' => '2022-09-14 09:54:08',
                'deleted_at' => '2022-09-14 09:54:08',
                'is_bookable' => 1,
                'stock_control_active' => 0,
            ),
            83 => 
            array (
                'id' => 84,
                'tour_id' => 2,
                'accommodation_inventory_id' => 1,
                'tour_sales_price' => '50.00',
                'is_template' => 0,
                'tour_component_type' => 'Included',
                'booking_policy' => 'overbook',
                'created_at' => '2022-09-14 09:49:12',
                'updated_at' => '2022-09-14 09:53:58',
                'deleted_at' => '2022-09-14 09:53:58',
                'is_bookable' => 1,
                'stock_control_active' => 0,
            ),
            84 => 
            array (
                'id' => 85,
                'tour_id' => 2,
                'accommodation_inventory_id' => 33,
                'tour_sales_price' => '50.00',
                'is_template' => 0,
                'tour_component_type' => 'Included',
                'booking_policy' => 'overbook',
                'created_at' => '2022-09-14 09:49:12',
                'updated_at' => '2022-09-14 09:53:47',
                'deleted_at' => '2022-09-14 09:53:47',
                'is_bookable' => 1,
                'stock_control_active' => 0,
            ),
            85 => 
            array (
                'id' => 86,
                'tour_id' => 2,
                'accommodation_inventory_id' => 29,
                'tour_sales_price' => '50.00',
                'is_template' => 0,
                'tour_component_type' => 'Included',
                'booking_policy' => 'overbook',
                'created_at' => '2022-09-14 09:49:12',
                'updated_at' => '2022-09-14 09:53:37',
                'deleted_at' => '2022-09-14 09:53:37',
                'is_bookable' => 1,
                'stock_control_active' => 0,
            ),
            86 => 
            array (
                'id' => 87,
                'tour_id' => 2,
                'accommodation_inventory_id' => 25,
                'tour_sales_price' => '50.00',
                'is_template' => 0,
                'tour_component_type' => 'Included',
                'booking_policy' => 'overbook',
                'created_at' => '2022-09-14 09:49:13',
                'updated_at' => '2022-09-14 09:53:27',
                'deleted_at' => '2022-09-14 09:53:27',
                'is_bookable' => 1,
                'stock_control_active' => 0,
            ),
            87 => 
            array (
                'id' => 88,
                'tour_id' => 2,
                'accommodation_inventory_id' => 21,
                'tour_sales_price' => '50.00',
                'is_template' => 0,
                'tour_component_type' => 'Included',
                'booking_policy' => 'overbook',
                'created_at' => '2022-09-14 09:49:13',
                'updated_at' => '2022-09-14 09:53:14',
                'deleted_at' => '2022-09-14 09:53:14',
                'is_bookable' => 1,
                'stock_control_active' => 0,
            ),
            88 => 
            array (
                'id' => 89,
                'tour_id' => 2,
                'accommodation_inventory_id' => 17,
                'tour_sales_price' => '50.00',
                'is_template' => 0,
                'tour_component_type' => 'Included',
                'booking_policy' => 'overbook',
                'created_at' => '2022-09-14 09:49:13',
                'updated_at' => '2022-09-14 09:53:02',
                'deleted_at' => '2022-09-14 09:53:02',
                'is_bookable' => 1,
                'stock_control_active' => 0,
            ),
            89 => 
            array (
                'id' => 90,
                'tour_id' => 2,
                'accommodation_inventory_id' => 13,
                'tour_sales_price' => '50.00',
                'is_template' => 0,
                'tour_component_type' => 'Included',
                'booking_policy' => 'overbook',
                'created_at' => '2022-09-14 09:49:13',
                'updated_at' => '2022-09-14 09:52:41',
                'deleted_at' => '2022-09-14 09:52:41',
                'is_bookable' => 1,
                'stock_control_active' => 0,
            ),
            90 => 
            array (
                'id' => 91,
                'tour_id' => 2,
                'accommodation_inventory_id' => 37,
                'tour_sales_price' => '25.00',
                'is_template' => 0,
                'tour_component_type' => 'Included',
                'booking_policy' => 'overbook',
                'created_at' => '2022-09-14 09:49:13',
                'updated_at' => '2022-09-14 09:50:02',
                'deleted_at' => '2022-09-14 09:50:02',
                'is_bookable' => 1,
                'stock_control_active' => 0,
            ),
            91 => 
            array (
                'id' => 92,
                'tour_id' => 2,
                'accommodation_inventory_id' => 38,
                'tour_sales_price' => '25.00',
                'is_template' => 0,
                'tour_component_type' => 'Included',
                'booking_policy' => 'overbook',
                'created_at' => '2022-09-14 09:49:13',
                'updated_at' => '2022-09-14 09:50:13',
                'deleted_at' => '2022-09-14 09:50:13',
                'is_bookable' => 1,
                'stock_control_active' => 0,
            ),
            92 => 
            array (
                'id' => 93,
                'tour_id' => 2,
                'accommodation_inventory_id' => 39,
                'tour_sales_price' => '25.00',
                'is_template' => 0,
                'tour_component_type' => 'Included',
                'booking_policy' => 'overbook',
                'created_at' => '2022-09-14 09:49:13',
                'updated_at' => '2022-09-14 09:52:44',
                'deleted_at' => '2022-09-14 09:52:44',
                'is_bookable' => 1,
                'stock_control_active' => 0,
            ),
            93 => 
            array (
                'id' => 94,
                'tour_id' => 2,
                'accommodation_inventory_id' => 40,
                'tour_sales_price' => '25.00',
                'is_template' => 0,
                'tour_component_type' => 'Included',
                'booking_policy' => 'overbook',
                'created_at' => '2022-09-14 09:49:13',
                'updated_at' => '2022-09-14 09:50:06',
                'deleted_at' => '2022-09-14 09:50:06',
                'is_bookable' => 1,
                'stock_control_active' => 0,
            ),
            94 => 
            array (
                'id' => 95,
                'tour_id' => 2,
                'accommodation_inventory_id' => 41,
                'tour_sales_price' => '25.00',
                'is_template' => 0,
                'tour_component_type' => 'Included',
                'booking_policy' => 'overbook',
                'created_at' => '2022-09-14 09:49:13',
                'updated_at' => '2022-09-14 09:50:16',
                'deleted_at' => '2022-09-14 09:50:16',
                'is_bookable' => 1,
                'stock_control_active' => 0,
            ),
            95 => 
            array (
                'id' => 96,
                'tour_id' => 2,
                'accommodation_inventory_id' => 42,
                'tour_sales_price' => '25.00',
                'is_template' => 0,
                'tour_component_type' => 'Included',
                'booking_policy' => 'overbook',
                'created_at' => '2022-09-14 09:49:13',
                'updated_at' => '2022-09-14 09:52:46',
                'deleted_at' => '2022-09-14 09:52:46',
                'is_bookable' => 1,
                'stock_control_active' => 0,
            ),
            96 => 
            array (
                'id' => 97,
                'tour_id' => 2,
                'accommodation_inventory_id' => 43,
                'tour_sales_price' => '25.00',
                'is_template' => 0,
                'tour_component_type' => 'Included',
                'booking_policy' => 'overbook',
                'created_at' => '2022-09-14 09:49:13',
                'updated_at' => '2022-09-14 09:50:09',
                'deleted_at' => '2022-09-14 09:50:09',
                'is_bookable' => 1,
                'stock_control_active' => 0,
            ),
            97 => 
            array (
                'id' => 98,
                'tour_id' => 2,
                'accommodation_inventory_id' => 44,
                'tour_sales_price' => '25.00',
                'is_template' => 0,
                'tour_component_type' => 'Included',
                'booking_policy' => 'overbook',
                'created_at' => '2022-09-14 09:49:13',
                'updated_at' => '2022-09-14 09:50:20',
                'deleted_at' => '2022-09-14 09:50:20',
                'is_bookable' => 1,
                'stock_control_active' => 0,
            ),
            98 => 
            array (
                'id' => 99,
                'tour_id' => 2,
                'accommodation_inventory_id' => 45,
                'tour_sales_price' => '25.00',
                'is_template' => 0,
                'tour_component_type' => 'Included',
                'booking_policy' => 'overbook',
                'created_at' => '2022-09-14 09:49:13',
                'updated_at' => '2022-09-14 09:52:49',
                'deleted_at' => '2022-09-14 09:52:49',
                'is_bookable' => 1,
                'stock_control_active' => 0,
            ),
            99 => 
            array (
                'id' => 100,
                'tour_id' => 2,
                'accommodation_inventory_id' => 47,
                'tour_sales_price' => '45.00',
                'is_template' => 1,
                'tour_component_type' => 'Included',
                'booking_policy' => 'overbook',
                'created_at' => '2022-09-14 10:07:11',
                'updated_at' => '2022-09-14 10:07:11',
                'deleted_at' => NULL,
                'is_bookable' => 1,
                'stock_control_active' => 0,
            ),
            100 => 
            array (
                'id' => 101,
                'tour_id' => 2,
                'accommodation_inventory_id' => 48,
                'tour_sales_price' => '40.00',
                'is_template' => 0,
                'tour_component_type' => 'Included',
                'booking_policy' => 'overbook',
                'created_at' => '2022-09-14 10:07:11',
                'updated_at' => '2022-09-14 10:07:11',
                'deleted_at' => NULL,
                'is_bookable' => 1,
                'stock_control_active' => 0,
            ),
            101 => 
            array (
                'id' => 102,
                'tour_id' => 2,
                'accommodation_inventory_id' => 52,
                'tour_sales_price' => '80.00',
                'is_template' => 1,
                'tour_component_type' => 'Included',
                'booking_policy' => 'overbook',
                'created_at' => '2022-09-14 10:09:16',
                'updated_at' => '2022-09-14 10:09:16',
                'deleted_at' => NULL,
                'is_bookable' => 1,
                'stock_control_active' => 0,
            ),
            102 => 
            array (
                'id' => 103,
                'tour_id' => 2,
                'accommodation_inventory_id' => 54,
                'tour_sales_price' => '80.00',
                'is_template' => 0,
                'tour_component_type' => 'Included',
                'booking_policy' => 'overbook',
                'created_at' => '2022-09-14 10:09:16',
                'updated_at' => '2022-09-14 10:09:16',
                'deleted_at' => NULL,
                'is_bookable' => 1,
                'stock_control_active' => 0,
            ),
            103 => 
            array (
                'id' => 104,
                'tour_id' => 2,
                'accommodation_inventory_id' => 50,
                'tour_sales_price' => '30.00',
                'is_template' => 0,
                'tour_component_type' => 'Upgrade',
                'booking_policy' => 'overbook',
                'created_at' => '2022-09-14 10:10:08',
                'updated_at' => '2022-09-14 10:10:08',
                'deleted_at' => NULL,
                'is_bookable' => 1,
                'stock_control_active' => 0,
            ),
            104 => 
            array (
                'id' => 105,
                'tour_id' => 2,
                'accommodation_inventory_id' => 51,
                'tour_sales_price' => '25.00',
                'is_template' => 0,
                'tour_component_type' => 'Upgrade',
                'booking_policy' => 'overbook',
                'created_at' => '2022-09-14 10:10:41',
                'updated_at' => '2022-09-14 10:10:41',
                'deleted_at' => NULL,
                'is_bookable' => 1,
                'stock_control_active' => 0,
            ),
            105 => 
            array (
                'id' => 106,
                'tour_id' => 2,
                'accommodation_inventory_id' => 53,
                'tour_sales_price' => '90.00',
                'is_template' => 0,
                'tour_component_type' => 'Included',
                'booking_policy' => 'overbook',
                'created_at' => '2022-09-14 12:16:33',
                'updated_at' => '2022-09-14 12:31:06',
                'deleted_at' => NULL,
                'is_bookable' => 0,
                'stock_control_active' => 0,
            ),
            106 => 
            array (
                'id' => 107,
                'tour_id' => 4,
                'accommodation_inventory_id' => 47,
                'tour_sales_price' => '45.00',
                'is_template' => 1,
                'tour_component_type' => 'Included',
                'booking_policy' => 'overbook',
                'created_at' => '2022-09-20 10:39:17',
                'updated_at' => '2022-09-20 10:39:17',
                'deleted_at' => NULL,
                'is_bookable' => 1,
                'stock_control_active' => 0,
            ),
            107 => 
            array (
                'id' => 108,
                'tour_id' => 4,
                'accommodation_inventory_id' => 48,
                'tour_sales_price' => '40.00',
                'is_template' => 0,
                'tour_component_type' => 'Included',
                'booking_policy' => 'overbook',
                'created_at' => '2022-09-20 10:39:17',
                'updated_at' => '2022-09-20 10:39:17',
                'deleted_at' => NULL,
                'is_bookable' => 1,
                'stock_control_active' => 0,
            ),
            108 => 
            array (
                'id' => 109,
                'tour_id' => 4,
                'accommodation_inventory_id' => 52,
                'tour_sales_price' => '80.00',
                'is_template' => 1,
                'tour_component_type' => 'Included',
                'booking_policy' => 'overbook',
                'created_at' => '2022-09-20 10:39:17',
                'updated_at' => '2022-09-20 10:39:17',
                'deleted_at' => NULL,
                'is_bookable' => 1,
                'stock_control_active' => 0,
            ),
            109 => 
            array (
                'id' => 110,
                'tour_id' => 4,
                'accommodation_inventory_id' => 54,
                'tour_sales_price' => '80.00',
                'is_template' => 0,
                'tour_component_type' => 'Included',
                'booking_policy' => 'overbook',
                'created_at' => '2022-09-20 10:39:17',
                'updated_at' => '2022-09-20 10:39:17',
                'deleted_at' => NULL,
                'is_bookable' => 1,
                'stock_control_active' => 0,
            ),
            110 => 
            array (
                'id' => 111,
                'tour_id' => 4,
                'accommodation_inventory_id' => 53,
                'tour_sales_price' => '90.00',
                'is_template' => 0,
                'tour_component_type' => 'Included',
                'booking_policy' => 'overbook',
                'created_at' => '2022-09-20 10:39:17',
                'updated_at' => '2022-09-20 10:39:17',
                'deleted_at' => NULL,
                'is_bookable' => 1,
                'stock_control_active' => 0,
            ),
            111 => 
            array (
                'id' => 112,
                'tour_id' => 5,
                'accommodation_inventory_id' => 56,
                'tour_sales_price' => '150.00',
                'is_template' => 1,
                'tour_component_type' => 'Included',
                'booking_policy' => 'overbook',
                'created_at' => '2022-09-20 19:00:58',
                'updated_at' => '2022-09-20 19:00:58',
                'deleted_at' => NULL,
                'is_bookable' => 1,
                'stock_control_active' => 0,
            ),
            112 => 
            array (
                'id' => 113,
                'tour_id' => 7,
                'accommodation_inventory_id' => 64,
                'tour_sales_price' => '25.00',
                'is_template' => 1,
                'tour_component_type' => 'Included',
                'booking_policy' => 'overbook',
                'created_at' => '2023-09-21 13:57:23',
                'updated_at' => '2023-09-21 13:57:23',
                'deleted_at' => NULL,
                'is_bookable' => 1,
                'stock_control_active' => 0,
            ),
            113 => 
            array (
                'id' => 114,
                'tour_id' => 7,
                'accommodation_inventory_id' => 65,
                'tour_sales_price' => '30.00',
                'is_template' => 0,
                'tour_component_type' => 'Included',
                'booking_policy' => 'overbook',
                'created_at' => '2023-09-21 13:57:23',
                'updated_at' => '2023-09-21 13:57:23',
                'deleted_at' => NULL,
                'is_bookable' => 1,
                'stock_control_active' => 0,
            ),
            114 => 
            array (
                'id' => 115,
                'tour_id' => 7,
                'accommodation_inventory_id' => 66,
                'tour_sales_price' => '20.00',
                'is_template' => 0,
                'tour_component_type' => 'Included',
                'booking_policy' => 'overbook',
                'created_at' => '2023-09-21 13:57:23',
                'updated_at' => '2023-09-21 13:57:23',
                'deleted_at' => NULL,
                'is_bookable' => 1,
                'stock_control_active' => 0,
            ),
            115 => 
            array (
                'id' => 116,
                'tour_id' => 7,
                'accommodation_inventory_id' => 67,
                'tour_sales_price' => '75.00',
                'is_template' => 1,
                'tour_component_type' => 'Included',
                'booking_policy' => 'overbook',
                'created_at' => '2023-09-21 13:57:23',
                'updated_at' => '2023-09-21 13:57:23',
                'deleted_at' => NULL,
                'is_bookable' => 1,
                'stock_control_active' => 0,
            ),
            116 => 
            array (
                'id' => 117,
                'tour_id' => 7,
                'accommodation_inventory_id' => 68,
                'tour_sales_price' => '75.00',
                'is_template' => 0,
                'tour_component_type' => 'Included',
                'booking_policy' => 'overbook',
                'created_at' => '2023-09-21 13:57:23',
                'updated_at' => '2023-09-21 13:57:23',
                'deleted_at' => NULL,
                'is_bookable' => 1,
                'stock_control_active' => 0,
            ),
            117 => 
            array (
                'id' => 118,
                'tour_id' => 7,
                'accommodation_inventory_id' => 69,
                'tour_sales_price' => '100.00',
                'is_template' => 0,
                'tour_component_type' => 'Upgrade',
                'booking_policy' => 'overbook',
                'created_at' => '2023-09-21 13:58:20',
                'updated_at' => '2023-09-21 13:58:20',
                'deleted_at' => NULL,
                'is_bookable' => 1,
                'stock_control_active' => 0,
            ),
            118 => 
            array (
                'id' => 119,
                'tour_id' => 7,
                'accommodation_inventory_id' => 70,
                'tour_sales_price' => '100.00',
                'is_template' => 0,
                'tour_component_type' => 'Upgrade',
                'booking_policy' => 'overbook',
                'created_at' => '2023-09-21 13:58:42',
                'updated_at' => '2023-09-21 13:58:42',
                'deleted_at' => NULL,
                'is_bookable' => 1,
                'stock_control_active' => 0,
            ),
            119 => 
            array (
                'id' => 120,
                'tour_id' => 7,
                'accommodation_inventory_id' => 71,
                'tour_sales_price' => '250.00',
                'is_template' => 0,
                'tour_component_type' => 'Add-on',
                'booking_policy' => 'overbook',
                'created_at' => '2023-09-22 13:19:15',
                'updated_at' => '2023-09-22 13:19:15',
                'deleted_at' => NULL,
                'is_bookable' => 1,
                'stock_control_active' => 0,
            ),
        ));
        
        
    }
}