<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class AddressesTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('addresses')->delete();
        
        \DB::table('addresses')->insert(array (
            0 => 
            array (
                'id' => 1,
                'name' => 'Signature Lux Hotel by ONOMO Foreshore',
                'address_parent_id' => 2,
                'location_type_id' => 1,
                'address_line_1' => '31A Heerengracht Street',
                'address_line_2' => 'Roggebaai Square',
                'address_line_3' => NULL,
                'town' => NULL,
                'region' => 'Cape Town',
                'country_id' => 178,
                'postcode' => '8001',
                'deleted_at' => NULL,
                'created_at' => '2022-01-20 11:47:54',
                'updated_at' => '2022-01-20 11:47:54',
            ),
            1 => 
            array (
                'id' => 2,
                'name' => 'Signature Lux Hotel by ONOMO, Sandton',
                'address_parent_id' => 2,
                'location_type_id' => 1,
                'address_line_1' => '135 West St, , Sandton, 2146, South Africa',
                'address_line_2' => 'Sandown',
                'address_line_3' => NULL,
                'town' => 'Sandton',
                'region' => 'Johannesburg',
                'country_id' => 178,
                'postcode' => '2146',
                'deleted_at' => NULL,
                'created_at' => '2022-01-20 12:44:50',
                'updated_at' => '2022-01-20 12:44:50',
            ),
            2 => 
            array (
                'id' => 3,
                'name' => 'False Bay Braai',
                'address_parent_id' => 3,
                'location_type_id' => 2,
                'address_line_1' => 'False Bay Beach',
                'address_line_2' => NULL,
                'address_line_3' => NULL,
                'town' => NULL,
                'region' => 'Cape Peninsula',
                'country_id' => 178,
                'postcode' => '5601',
                'deleted_at' => NULL,
                'created_at' => '2022-01-20 13:34:06',
                'updated_at' => '2022-01-21 10:54:13',
            ),
            3 => 
            array (
                'id' => 4,
                'name' => 'Vineyards Tour',
                'address_parent_id' => 3,
                'location_type_id' => 3,
                'address_line_1' => 'Vineyard Row',
                'address_line_2' => NULL,
                'address_line_3' => NULL,
                'town' => NULL,
                'region' => 'Cape Town',
                'country_id' => 178,
                'postcode' => '123412',
                'deleted_at' => NULL,
                'created_at' => '2022-01-20 15:32:09',
                'updated_at' => '2022-01-20 15:32:09',
            ),
            4 => 
            array (
                'id' => 5,
                'name' => 'Pregenerated Customer Name',
                'address_parent_id' => 1,
                'location_type_id' => NULL,
                'address_line_1' => '5990 Schiller Alley Apt. 171',
                'address_line_2' => NULL,
                'address_line_3' => NULL,
                'town' => 'Jordytown',
                'region' => 'Nevada',
                'country_id' => 1,
                'postcode' => '28527',
                'deleted_at' => NULL,
                'created_at' => '2022-01-21 10:27:43',
                'updated_at' => '2022-01-21 10:27:43',
            ),
            5 => 
            array (
                'id' => 6,
                'name' => 'Pregenerated Customer Name',
                'address_parent_id' => 1,
                'location_type_id' => NULL,
                'address_line_1' => '5990 Schiller Alley Apt. 171',
                'address_line_2' => NULL,
                'address_line_3' => NULL,
                'town' => 'Jordytown',
                'region' => 'Nevada',
                'country_id' => 1,
                'postcode' => '28527',
                'deleted_at' => NULL,
                'created_at' => '2022-01-21 10:27:43',
                'updated_at' => '2022-01-21 10:27:43',
            ),
            6 => 
            array (
                'id' => 7,
                'name' => 'Pregenerated Customer Name',
                'address_parent_id' => 1,
                'location_type_id' => NULL,
                'address_line_1' => '122 Spencer Summit Suite 319',
                'address_line_2' => NULL,
                'address_line_3' => NULL,
                'town' => 'Rodriguezburgh',
                'region' => 'Texas',
                'country_id' => 1,
                'postcode' => '43103-4059',
                'deleted_at' => NULL,
                'created_at' => '2022-01-21 10:29:13',
                'updated_at' => '2022-01-21 10:29:13',
            ),
            7 => 
            array (
                'id' => 8,
                'name' => 'Pregenerated Customer Name',
                'address_parent_id' => 1,
                'location_type_id' => NULL,
                'address_line_1' => '122 Spencer Summit Suite 319',
                'address_line_2' => NULL,
                'address_line_3' => NULL,
                'town' => 'Rodriguezburgh',
                'region' => 'Texas',
                'country_id' => 1,
                'postcode' => '43103-4059',
                'deleted_at' => NULL,
                'created_at' => '2022-01-21 10:29:13',
                'updated_at' => '2022-01-21 10:29:13',
            ),
            8 => 
            array (
                'id' => 9,
                'name' => 'Pregenerated Customer Name',
                'address_parent_id' => 1,
                'location_type_id' => NULL,
                'address_line_1' => '28072 Gleason River',
                'address_line_2' => NULL,
                'address_line_3' => NULL,
                'town' => 'New Robin',
                'region' => 'District of Columbia',
                'country_id' => 1,
                'postcode' => '36209-2687',
                'deleted_at' => NULL,
                'created_at' => '2022-01-21 10:29:13',
                'updated_at' => '2022-01-21 10:29:13',
            ),
            9 => 
            array (
                'id' => 10,
                'name' => 'Pregenerated Customer Name',
                'address_parent_id' => 1,
                'location_type_id' => NULL,
                'address_line_1' => '28072 Gleason River',
                'address_line_2' => NULL,
                'address_line_3' => NULL,
                'town' => 'New Robin',
                'region' => 'District of Columbia',
                'country_id' => 1,
                'postcode' => '36209-2687',
                'deleted_at' => NULL,
                'created_at' => '2022-01-21 10:29:13',
                'updated_at' => '2022-01-21 10:29:13',
            ),
            10 => 
            array (
                'id' => 11,
                'name' => 'Pregenerated Customer Name',
                'address_parent_id' => 1,
                'location_type_id' => NULL,
                'address_line_1' => '503 Fritsch Island',
                'address_line_2' => NULL,
                'address_line_3' => NULL,
                'town' => 'West Zoilaport',
                'region' => 'North Carolina',
                'country_id' => 1,
                'postcode' => '30132',
                'deleted_at' => NULL,
                'created_at' => '2022-01-21 10:29:13',
                'updated_at' => '2022-01-21 10:29:13',
            ),
            11 => 
            array (
                'id' => 12,
                'name' => 'Pregenerated Customer Name',
                'address_parent_id' => 1,
                'location_type_id' => NULL,
                'address_line_1' => '503 Fritsch Island',
                'address_line_2' => NULL,
                'address_line_3' => NULL,
                'town' => 'West Zoilaport',
                'region' => 'North Carolina',
                'country_id' => 1,
                'postcode' => '30132',
                'deleted_at' => NULL,
                'created_at' => '2022-01-21 10:29:13',
                'updated_at' => '2022-01-21 10:29:13',
            ),
            12 => 
            array (
                'id' => 13,
                'name' => 'Pregenerated Customer Name',
                'address_parent_id' => 1,
                'location_type_id' => NULL,
                'address_line_1' => '413 Hattie Road',
                'address_line_2' => NULL,
                'address_line_3' => NULL,
                'town' => 'Kayleeton',
                'region' => 'Maine',
                'country_id' => 1,
                'postcode' => '24095-5203',
                'deleted_at' => NULL,
                'created_at' => '2022-01-21 10:29:13',
                'updated_at' => '2022-01-21 10:29:13',
            ),
            13 => 
            array (
                'id' => 14,
                'name' => 'Pregenerated Customer Name',
                'address_parent_id' => 1,
                'location_type_id' => NULL,
                'address_line_1' => '413 Hattie Road',
                'address_line_2' => NULL,
                'address_line_3' => NULL,
                'town' => 'Kayleeton',
                'region' => 'Maine',
                'country_id' => 1,
                'postcode' => '24095-5203',
                'deleted_at' => NULL,
                'created_at' => '2022-01-21 10:29:13',
                'updated_at' => '2022-01-21 10:29:13',
            ),
            14 => 
            array (
                'id' => 15,
                'name' => 'Pregenerated Customer Name',
                'address_parent_id' => 1,
                'location_type_id' => NULL,
                'address_line_1' => '97303 Gerlach Green',
                'address_line_2' => NULL,
                'address_line_3' => NULL,
                'town' => 'South Rocky',
                'region' => 'Montana',
                'country_id' => 1,
                'postcode' => '17378',
                'deleted_at' => NULL,
                'created_at' => '2022-01-21 10:29:13',
                'updated_at' => '2022-01-21 10:29:13',
            ),
            15 => 
            array (
                'id' => 16,
                'name' => 'Pregenerated Customer Name',
                'address_parent_id' => 1,
                'location_type_id' => NULL,
                'address_line_1' => '97303 Gerlach Green',
                'address_line_2' => NULL,
                'address_line_3' => NULL,
                'town' => 'South Rocky',
                'region' => 'Montana',
                'country_id' => 1,
                'postcode' => '17378',
                'deleted_at' => NULL,
                'created_at' => '2022-01-21 10:29:13',
                'updated_at' => '2022-01-21 10:29:13',
            ),
            16 => 
            array (
                'id' => 17,
                'name' => 'Pregenerated Customer Name',
                'address_parent_id' => 1,
                'location_type_id' => NULL,
                'address_line_1' => '5332 Federico Shore',
                'address_line_2' => NULL,
                'address_line_3' => NULL,
                'town' => 'East Elnoraview',
                'region' => 'Utah',
                'country_id' => 1,
                'postcode' => '35860',
                'deleted_at' => NULL,
                'created_at' => '2022-01-21 10:29:13',
                'updated_at' => '2022-01-21 10:29:13',
            ),
            17 => 
            array (
                'id' => 18,
                'name' => 'Pregenerated Customer Name',
                'address_parent_id' => 1,
                'location_type_id' => NULL,
                'address_line_1' => '5332 Federico Shore',
                'address_line_2' => NULL,
                'address_line_3' => NULL,
                'town' => 'East Elnoraview',
                'region' => 'Utah',
                'country_id' => 1,
                'postcode' => '35860',
                'deleted_at' => NULL,
                'created_at' => '2022-01-21 10:29:13',
                'updated_at' => '2022-01-21 10:29:13',
            ),
            18 => 
            array (
                'id' => 19,
                'name' => 'Pregenerated Customer Name',
                'address_parent_id' => 1,
                'location_type_id' => NULL,
                'address_line_1' => '622 Earnest Keys',
                'address_line_2' => NULL,
                'address_line_3' => NULL,
                'town' => 'New Fatima',
                'region' => 'Idaho',
                'country_id' => 1,
                'postcode' => '54868',
                'deleted_at' => NULL,
                'created_at' => '2022-01-21 10:29:13',
                'updated_at' => '2022-01-21 10:29:13',
            ),
            19 => 
            array (
                'id' => 20,
                'name' => 'Pregenerated Customer Name',
                'address_parent_id' => 1,
                'location_type_id' => NULL,
                'address_line_1' => '622 Earnest Keys',
                'address_line_2' => NULL,
                'address_line_3' => NULL,
                'town' => 'New Fatima',
                'region' => 'Idaho',
                'country_id' => 1,
                'postcode' => '54868',
                'deleted_at' => NULL,
                'created_at' => '2022-01-21 10:29:13',
                'updated_at' => '2022-01-21 10:29:13',
            ),
            20 => 
            array (
                'id' => 21,
                'name' => 'Pregenerated Customer Name',
                'address_parent_id' => 1,
                'location_type_id' => NULL,
                'address_line_1' => '92575 Kara Junction',
                'address_line_2' => NULL,
                'address_line_3' => NULL,
                'town' => 'Lake Jennyfer',
                'region' => 'Illinois',
                'country_id' => 1,
                'postcode' => '49984-4927',
                'deleted_at' => NULL,
                'created_at' => '2022-01-21 10:29:13',
                'updated_at' => '2022-01-21 10:29:13',
            ),
            21 => 
            array (
                'id' => 22,
                'name' => 'Pregenerated Customer Name',
                'address_parent_id' => 1,
                'location_type_id' => NULL,
                'address_line_1' => '92575 Kara Junction',
                'address_line_2' => NULL,
                'address_line_3' => NULL,
                'town' => 'Lake Jennyfer',
                'region' => 'Illinois',
                'country_id' => 1,
                'postcode' => '49984-4927',
                'deleted_at' => NULL,
                'created_at' => '2022-01-21 10:29:13',
                'updated_at' => '2022-01-21 10:29:13',
            ),
            22 => 
            array (
                'id' => 23,
                'name' => 'Pregenerated Customer Name',
                'address_parent_id' => 1,
                'location_type_id' => NULL,
                'address_line_1' => '655 Jackie Meadow Suite 372',
                'address_line_2' => NULL,
                'address_line_3' => NULL,
                'town' => 'North Hortense',
                'region' => 'Pennsylvania',
                'country_id' => 1,
                'postcode' => '11837-9554',
                'deleted_at' => NULL,
                'created_at' => '2022-01-21 10:29:13',
                'updated_at' => '2022-01-21 10:29:13',
            ),
            23 => 
            array (
                'id' => 24,
                'name' => 'Pregenerated Customer Name',
                'address_parent_id' => 1,
                'location_type_id' => NULL,
                'address_line_1' => '655 Jackie Meadow Suite 372',
                'address_line_2' => NULL,
                'address_line_3' => NULL,
                'town' => 'North Hortense',
                'region' => 'Pennsylvania',
                'country_id' => 1,
                'postcode' => '11837-9554',
                'deleted_at' => NULL,
                'created_at' => '2022-01-21 10:29:13',
                'updated_at' => '2022-01-21 10:29:13',
            ),
            24 => 
            array (
                'id' => 25,
                'name' => 'Pregenerated Customer Name',
                'address_parent_id' => 1,
                'location_type_id' => NULL,
                'address_line_1' => '928 Kevon Glens Suite 279',
                'address_line_2' => NULL,
                'address_line_3' => NULL,
                'town' => 'Lake Connie',
                'region' => 'Kentucky',
                'country_id' => 1,
                'postcode' => '45819-0368',
                'deleted_at' => NULL,
                'created_at' => '2022-01-21 10:29:13',
                'updated_at' => '2022-01-21 10:29:13',
            ),
            25 => 
            array (
                'id' => 26,
                'name' => 'Pregenerated Customer Name',
                'address_parent_id' => 1,
                'location_type_id' => NULL,
                'address_line_1' => '928 Kevon Glens Suite 279',
                'address_line_2' => NULL,
                'address_line_3' => NULL,
                'town' => 'Lake Connie',
                'region' => 'Kentucky',
                'country_id' => 1,
                'postcode' => '45819-0368',
                'deleted_at' => NULL,
                'created_at' => '2022-01-21 10:29:13',
                'updated_at' => '2022-01-21 10:29:13',
            ),
            26 => 
            array (
                'id' => 27,
                'name' => 'Pregenerated Customer Name',
                'address_parent_id' => 1,
                'location_type_id' => NULL,
                'address_line_1' => '64707 Jerde View',
                'address_line_2' => NULL,
                'address_line_3' => NULL,
                'town' => 'Port Erin',
                'region' => 'Arkansas',
                'country_id' => 1,
                'postcode' => '69782',
                'deleted_at' => NULL,
                'created_at' => '2022-01-21 10:29:13',
                'updated_at' => '2022-01-21 10:29:13',
            ),
            27 => 
            array (
                'id' => 28,
                'name' => 'Pregenerated Customer Name',
                'address_parent_id' => 1,
                'location_type_id' => NULL,
                'address_line_1' => '64707 Jerde View',
                'address_line_2' => NULL,
                'address_line_3' => NULL,
                'town' => 'Port Erin',
                'region' => 'Arkansas',
                'country_id' => 1,
                'postcode' => '69782',
                'deleted_at' => NULL,
                'created_at' => '2022-01-21 10:29:13',
                'updated_at' => '2022-01-21 10:29:13',
            ),
            28 => 
            array (
                'id' => 29,
                'name' => 'Pregenerated Customer Name',
                'address_parent_id' => 1,
                'location_type_id' => NULL,
                'address_line_1' => '5605 Swift Meadows Suite 015',
                'address_line_2' => NULL,
                'address_line_3' => NULL,
                'town' => 'West Barton',
                'region' => 'Maryland',
                'country_id' => 1,
                'postcode' => '61652',
                'deleted_at' => NULL,
                'created_at' => '2022-01-21 10:29:13',
                'updated_at' => '2022-01-21 10:29:13',
            ),
            29 => 
            array (
                'id' => 30,
                'name' => 'Pregenerated Customer Name',
                'address_parent_id' => 1,
                'location_type_id' => NULL,
                'address_line_1' => '5605 Swift Meadows Suite 015',
                'address_line_2' => NULL,
                'address_line_3' => NULL,
                'town' => 'West Barton',
                'region' => 'Maryland',
                'country_id' => 1,
                'postcode' => '61652',
                'deleted_at' => NULL,
                'created_at' => '2022-01-21 10:29:13',
                'updated_at' => '2022-01-21 10:29:13',
            ),
            30 => 
            array (
                'id' => 31,
                'name' => 'Pregenerated Customer Name',
                'address_parent_id' => 1,
                'location_type_id' => NULL,
                'address_line_1' => '651 Lindgren Course',
                'address_line_2' => NULL,
                'address_line_3' => NULL,
                'town' => 'East Lilianaville',
                'region' => 'Nevada',
                'country_id' => 1,
                'postcode' => '92492',
                'deleted_at' => NULL,
                'created_at' => '2022-01-21 10:29:13',
                'updated_at' => '2022-01-21 10:29:13',
            ),
            31 => 
            array (
                'id' => 32,
                'name' => 'Pregenerated Customer Name',
                'address_parent_id' => 1,
                'location_type_id' => NULL,
                'address_line_1' => '651 Lindgren Course',
                'address_line_2' => NULL,
                'address_line_3' => NULL,
                'town' => 'East Lilianaville',
                'region' => 'Nevada',
                'country_id' => 1,
                'postcode' => '92492',
                'deleted_at' => NULL,
                'created_at' => '2022-01-21 10:29:13',
                'updated_at' => '2022-01-21 10:29:13',
            ),
            32 => 
            array (
                'id' => 33,
                'name' => 'Pregenerated Customer Name',
                'address_parent_id' => 1,
                'location_type_id' => NULL,
                'address_line_1' => '98935 Fae Wells Apt. 590',
                'address_line_2' => NULL,
                'address_line_3' => NULL,
                'town' => 'Alfredabury',
                'region' => 'Arkansas',
                'country_id' => 1,
                'postcode' => '60990-5711',
                'deleted_at' => NULL,
                'created_at' => '2022-01-21 10:29:13',
                'updated_at' => '2022-01-21 10:29:13',
            ),
            33 => 
            array (
                'id' => 34,
                'name' => 'Pregenerated Customer Name',
                'address_parent_id' => 1,
                'location_type_id' => NULL,
                'address_line_1' => '98935 Fae Wells Apt. 590',
                'address_line_2' => NULL,
                'address_line_3' => NULL,
                'town' => 'Alfredabury',
                'region' => 'Arkansas',
                'country_id' => 1,
                'postcode' => '60990-5711',
                'deleted_at' => NULL,
                'created_at' => '2022-01-21 10:29:13',
                'updated_at' => '2022-01-21 10:29:13',
            ),
            34 => 
            array (
                'id' => 35,
                'name' => 'Pregenerated Customer Name',
                'address_parent_id' => 1,
                'location_type_id' => NULL,
                'address_line_1' => '1776 Powlowski Corner Suite 558',
                'address_line_2' => NULL,
                'address_line_3' => NULL,
                'town' => 'South Carleyport',
                'region' => 'Mississippi',
                'country_id' => 1,
                'postcode' => '84272-0862',
                'deleted_at' => NULL,
                'created_at' => '2022-01-21 10:29:13',
                'updated_at' => '2022-01-21 10:29:13',
            ),
            35 => 
            array (
                'id' => 36,
                'name' => 'Pregenerated Customer Name',
                'address_parent_id' => 1,
                'location_type_id' => NULL,
                'address_line_1' => '1776 Powlowski Corner Suite 558',
                'address_line_2' => NULL,
                'address_line_3' => NULL,
                'town' => 'South Carleyport',
                'region' => 'Mississippi',
                'country_id' => 1,
                'postcode' => '84272-0862',
                'deleted_at' => NULL,
                'created_at' => '2022-01-21 10:29:13',
                'updated_at' => '2022-01-21 10:29:13',
            ),
            36 => 
            array (
                'id' => 37,
                'name' => 'Pregenerated Customer Name',
                'address_parent_id' => 1,
                'location_type_id' => NULL,
                'address_line_1' => '2932 Rylee Mall Apt. 117',
                'address_line_2' => NULL,
                'address_line_3' => NULL,
                'town' => 'South Meghanside',
                'region' => 'South Dakota',
                'country_id' => 1,
                'postcode' => '45223-2882',
                'deleted_at' => NULL,
                'created_at' => '2022-01-21 10:29:13',
                'updated_at' => '2022-01-21 10:29:13',
            ),
            37 => 
            array (
                'id' => 38,
                'name' => 'Pregenerated Customer Name',
                'address_parent_id' => 1,
                'location_type_id' => NULL,
                'address_line_1' => '2932 Rylee Mall Apt. 117',
                'address_line_2' => NULL,
                'address_line_3' => NULL,
                'town' => 'South Meghanside',
                'region' => 'South Dakota',
                'country_id' => 1,
                'postcode' => '45223-2882',
                'deleted_at' => NULL,
                'created_at' => '2022-01-21 10:29:13',
                'updated_at' => '2022-01-21 10:29:13',
            ),
            38 => 
            array (
                'id' => 39,
                'name' => 'Pregenerated Customer Name',
                'address_parent_id' => 1,
                'location_type_id' => NULL,
                'address_line_1' => '43217 Garry Tunnel',
                'address_line_2' => NULL,
                'address_line_3' => NULL,
                'town' => 'Laneville',
                'region' => 'Arizona',
                'country_id' => 1,
                'postcode' => '87593-6772',
                'deleted_at' => NULL,
                'created_at' => '2022-01-21 10:29:13',
                'updated_at' => '2022-01-21 10:29:13',
            ),
            39 => 
            array (
                'id' => 40,
                'name' => 'Pregenerated Customer Name',
                'address_parent_id' => 1,
                'location_type_id' => NULL,
                'address_line_1' => '43217 Garry Tunnel',
                'address_line_2' => NULL,
                'address_line_3' => NULL,
                'town' => 'Laneville',
                'region' => 'Arizona',
                'country_id' => 1,
                'postcode' => '87593-6772',
                'deleted_at' => NULL,
                'created_at' => '2022-01-21 10:29:13',
                'updated_at' => '2022-01-21 10:29:13',
            ),
            40 => 
            array (
                'id' => 41,
                'name' => 'Pregenerated Customer Name',
                'address_parent_id' => 1,
                'location_type_id' => NULL,
                'address_line_1' => '78150 Drew Run Suite 809',
                'address_line_2' => NULL,
                'address_line_3' => NULL,
                'town' => 'Amieberg',
                'region' => 'Connecticut',
                'country_id' => 1,
                'postcode' => '39757',
                'deleted_at' => NULL,
                'created_at' => '2022-01-21 10:29:13',
                'updated_at' => '2022-01-21 10:29:13',
            ),
            41 => 
            array (
                'id' => 42,
                'name' => 'Pregenerated Customer Name',
                'address_parent_id' => 1,
                'location_type_id' => NULL,
                'address_line_1' => '78150 Drew Run Suite 809',
                'address_line_2' => NULL,
                'address_line_3' => NULL,
                'town' => 'Amieberg',
                'region' => 'Connecticut',
                'country_id' => 1,
                'postcode' => '39757',
                'deleted_at' => NULL,
                'created_at' => '2022-01-21 10:29:13',
                'updated_at' => '2022-01-21 10:29:13',
            ),
            42 => 
            array (
                'id' => 43,
                'name' => 'Pregenerated Customer Name',
                'address_parent_id' => 1,
                'location_type_id' => NULL,
                'address_line_1' => '7161 Tyson Flats',
                'address_line_2' => NULL,
                'address_line_3' => NULL,
                'town' => 'Eribertohaven',
                'region' => 'West Virginia',
                'country_id' => 1,
                'postcode' => '18567',
                'deleted_at' => NULL,
                'created_at' => '2022-01-21 10:29:13',
                'updated_at' => '2022-01-21 10:29:13',
            ),
            43 => 
            array (
                'id' => 44,
                'name' => 'Pregenerated Customer Name',
                'address_parent_id' => 1,
                'location_type_id' => NULL,
                'address_line_1' => '7161 Tyson Flats',
                'address_line_2' => NULL,
                'address_line_3' => NULL,
                'town' => 'Eribertohaven',
                'region' => 'West Virginia',
                'country_id' => 1,
                'postcode' => '18567',
                'deleted_at' => NULL,
                'created_at' => '2022-01-21 10:29:13',
                'updated_at' => '2022-01-21 10:29:13',
            ),
            44 => 
            array (
                'id' => 45,
                'name' => 'Pregenerated Customer Name',
                'address_parent_id' => 1,
                'location_type_id' => NULL,
                'address_line_1' => '50339 Krajcik Hill',
                'address_line_2' => NULL,
                'address_line_3' => NULL,
                'town' => 'Bernhardchester',
                'region' => 'Maine',
                'country_id' => 1,
                'postcode' => '67927-8707',
                'deleted_at' => NULL,
                'created_at' => '2022-01-21 10:29:13',
                'updated_at' => '2022-01-21 10:29:13',
            ),
            45 => 
            array (
                'id' => 46,
                'name' => 'Pregenerated Customer Name',
                'address_parent_id' => 1,
                'location_type_id' => NULL,
                'address_line_1' => '50339 Krajcik Hill',
                'address_line_2' => NULL,
                'address_line_3' => NULL,
                'town' => 'Bernhardchester',
                'region' => 'Maine',
                'country_id' => 1,
                'postcode' => '67927-8707',
                'deleted_at' => NULL,
                'created_at' => '2022-01-21 10:29:13',
                'updated_at' => '2022-01-21 10:29:13',
            ),
            46 => 
            array (
                'id' => 47,
                'name' => 'Pregenerated Customer Name',
                'address_parent_id' => 1,
                'location_type_id' => NULL,
                'address_line_1' => '8678 Emil Hills Suite 000',
                'address_line_2' => NULL,
                'address_line_3' => NULL,
                'town' => 'West Fanniefurt',
                'region' => 'Tennessee',
                'country_id' => 1,
                'postcode' => '81305',
                'deleted_at' => NULL,
                'created_at' => '2022-01-21 10:29:13',
                'updated_at' => '2022-01-21 10:29:13',
            ),
            47 => 
            array (
                'id' => 48,
                'name' => 'Pregenerated Customer Name',
                'address_parent_id' => 1,
                'location_type_id' => NULL,
                'address_line_1' => '8678 Emil Hills Suite 000',
                'address_line_2' => NULL,
                'address_line_3' => NULL,
                'town' => 'West Fanniefurt',
                'region' => 'Tennessee',
                'country_id' => 1,
                'postcode' => '81305',
                'deleted_at' => NULL,
                'created_at' => '2022-01-21 10:29:13',
                'updated_at' => '2022-01-21 10:29:13',
            ),
            48 => 
            array (
                'id' => 49,
                'name' => 'Pregenerated Customer Name',
                'address_parent_id' => 1,
                'location_type_id' => NULL,
                'address_line_1' => '118 Beatty Road',
                'address_line_2' => NULL,
                'address_line_3' => NULL,
                'town' => 'Port Eliezer',
                'region' => 'Oklahoma',
                'country_id' => 1,
                'postcode' => '55332-5273',
                'deleted_at' => NULL,
                'created_at' => '2022-01-21 10:29:13',
                'updated_at' => '2022-01-21 10:29:13',
            ),
            49 => 
            array (
                'id' => 50,
                'name' => 'Pregenerated Customer Name',
                'address_parent_id' => 1,
                'location_type_id' => NULL,
                'address_line_1' => '118 Beatty Road',
                'address_line_2' => NULL,
                'address_line_3' => NULL,
                'town' => 'Port Eliezer',
                'region' => 'Oklahoma',
                'country_id' => 1,
                'postcode' => '55332-5273',
                'deleted_at' => NULL,
                'created_at' => '2022-01-21 10:29:13',
                'updated_at' => '2022-01-21 10:29:13',
            ),
            50 => 
            array (
                'id' => 51,
                'name' => 'Pregenerated Customer Name',
                'address_parent_id' => 1,
                'location_type_id' => NULL,
                'address_line_1' => '7416 Dahlia Plains',
                'address_line_2' => NULL,
                'address_line_3' => NULL,
                'town' => 'Altenwerthton',
                'region' => 'Pennsylvania',
                'country_id' => 1,
                'postcode' => '81215',
                'deleted_at' => NULL,
                'created_at' => '2022-01-21 10:29:13',
                'updated_at' => '2022-01-21 10:29:13',
            ),
            51 => 
            array (
                'id' => 52,
                'name' => 'Pregenerated Customer Name',
                'address_parent_id' => 1,
                'location_type_id' => NULL,
                'address_line_1' => '7416 Dahlia Plains',
                'address_line_2' => NULL,
                'address_line_3' => NULL,
                'town' => 'Altenwerthton',
                'region' => 'Pennsylvania',
                'country_id' => 1,
                'postcode' => '81215',
                'deleted_at' => NULL,
                'created_at' => '2022-01-21 10:29:13',
                'updated_at' => '2022-01-21 10:29:13',
            ),
            52 => 
            array (
                'id' => 53,
                'name' => 'Pregenerated Customer Name',
                'address_parent_id' => 1,
                'location_type_id' => NULL,
                'address_line_1' => '6828 Johns Mountain Suite 500',
                'address_line_2' => NULL,
                'address_line_3' => NULL,
                'town' => 'New Lonie',
                'region' => 'Georgia',
                'country_id' => 1,
                'postcode' => '49677',
                'deleted_at' => NULL,
                'created_at' => '2022-01-21 10:29:13',
                'updated_at' => '2022-01-21 10:29:13',
            ),
            53 => 
            array (
                'id' => 54,
                'name' => 'Pregenerated Customer Name',
                'address_parent_id' => 1,
                'location_type_id' => NULL,
                'address_line_1' => '6828 Johns Mountain Suite 500',
                'address_line_2' => NULL,
                'address_line_3' => NULL,
                'town' => 'New Lonie',
                'region' => 'Georgia',
                'country_id' => 1,
                'postcode' => '49677',
                'deleted_at' => NULL,
                'created_at' => '2022-01-21 10:29:13',
                'updated_at' => '2022-01-21 10:29:13',
            ),
            54 => 
            array (
                'id' => 55,
                'name' => 'Pregenerated Customer Name',
                'address_parent_id' => 1,
                'location_type_id' => NULL,
                'address_line_1' => '8731 Lebsack Summit Suite 848',
                'address_line_2' => NULL,
                'address_line_3' => NULL,
                'town' => 'Camrynmouth',
                'region' => 'Washington',
                'country_id' => 1,
                'postcode' => '52642',
                'deleted_at' => NULL,
                'created_at' => '2022-01-21 10:29:13',
                'updated_at' => '2022-01-21 10:29:13',
            ),
            55 => 
            array (
                'id' => 56,
                'name' => 'Pregenerated Customer Name',
                'address_parent_id' => 1,
                'location_type_id' => NULL,
                'address_line_1' => '8731 Lebsack Summit Suite 848',
                'address_line_2' => NULL,
                'address_line_3' => NULL,
                'town' => 'Camrynmouth',
                'region' => 'Washington',
                'country_id' => 1,
                'postcode' => '52642',
                'deleted_at' => NULL,
                'created_at' => '2022-01-21 10:29:13',
                'updated_at' => '2022-01-21 10:29:13',
            ),
            56 => 
            array (
                'id' => 57,
                'name' => 'Pregenerated Customer Name',
                'address_parent_id' => 1,
                'location_type_id' => NULL,
                'address_line_1' => '9184 Lonie Green Suite 134',
                'address_line_2' => NULL,
                'address_line_3' => NULL,
                'town' => 'Kayleemouth',
                'region' => 'Wisconsin',
                'country_id' => 1,
                'postcode' => '93805-7907',
                'deleted_at' => NULL,
                'created_at' => '2022-01-21 10:29:13',
                'updated_at' => '2022-01-21 10:29:13',
            ),
            57 => 
            array (
                'id' => 58,
                'name' => 'Pregenerated Customer Name',
                'address_parent_id' => 1,
                'location_type_id' => NULL,
                'address_line_1' => '9184 Lonie Green Suite 134',
                'address_line_2' => NULL,
                'address_line_3' => NULL,
                'town' => 'Kayleemouth',
                'region' => 'Wisconsin',
                'country_id' => 1,
                'postcode' => '93805-7907',
                'deleted_at' => NULL,
                'created_at' => '2022-01-21 10:29:13',
                'updated_at' => '2022-01-21 10:29:13',
            ),
            58 => 
            array (
                'id' => 59,
                'name' => 'Pregenerated Customer Name',
                'address_parent_id' => 1,
                'location_type_id' => NULL,
                'address_line_1' => '47149 Altenwerth Mission',
                'address_line_2' => NULL,
                'address_line_3' => NULL,
                'town' => 'New Trinity',
                'region' => 'Michigan',
                'country_id' => 1,
                'postcode' => '40792-2036',
                'deleted_at' => NULL,
                'created_at' => '2022-01-21 10:29:13',
                'updated_at' => '2022-01-21 10:29:13',
            ),
            59 => 
            array (
                'id' => 60,
                'name' => 'Pregenerated Customer Name',
                'address_parent_id' => 1,
                'location_type_id' => NULL,
                'address_line_1' => '47149 Altenwerth Mission',
                'address_line_2' => NULL,
                'address_line_3' => NULL,
                'town' => 'New Trinity',
                'region' => 'Michigan',
                'country_id' => 1,
                'postcode' => '40792-2036',
                'deleted_at' => NULL,
                'created_at' => '2022-01-21 10:29:13',
                'updated_at' => '2022-01-21 10:29:13',
            ),
            60 => 
            array (
                'id' => 61,
                'name' => 'Pregenerated Customer Name',
                'address_parent_id' => 1,
                'location_type_id' => NULL,
                'address_line_1' => '1946 Beatty Avenue',
                'address_line_2' => NULL,
                'address_line_3' => NULL,
                'town' => 'Mannside',
                'region' => 'South Dakota',
                'country_id' => 1,
                'postcode' => '17406',
                'deleted_at' => NULL,
                'created_at' => '2022-01-21 10:29:13',
                'updated_at' => '2022-01-21 10:29:13',
            ),
            61 => 
            array (
                'id' => 62,
                'name' => 'Pregenerated Customer Name',
                'address_parent_id' => 1,
                'location_type_id' => NULL,
                'address_line_1' => '1946 Beatty Avenue',
                'address_line_2' => NULL,
                'address_line_3' => NULL,
                'town' => 'Mannside',
                'region' => 'South Dakota',
                'country_id' => 1,
                'postcode' => '17406',
                'deleted_at' => NULL,
                'created_at' => '2022-01-21 10:29:13',
                'updated_at' => '2022-01-21 10:29:13',
            ),
            62 => 
            array (
                'id' => 63,
                'name' => 'Pregenerated Customer Name',
                'address_parent_id' => 1,
                'location_type_id' => NULL,
                'address_line_1' => '19143 Homenick Fall',
                'address_line_2' => NULL,
                'address_line_3' => NULL,
                'town' => 'North Jessbury',
                'region' => 'Mississippi',
                'country_id' => 1,
                'postcode' => '62579-1247',
                'deleted_at' => NULL,
                'created_at' => '2022-01-21 10:29:13',
                'updated_at' => '2022-01-21 10:29:13',
            ),
            63 => 
            array (
                'id' => 64,
                'name' => 'Pregenerated Customer Name',
                'address_parent_id' => 1,
                'location_type_id' => NULL,
                'address_line_1' => '19143 Homenick Fall',
                'address_line_2' => NULL,
                'address_line_3' => NULL,
                'town' => 'North Jessbury',
                'region' => 'Mississippi',
                'country_id' => 1,
                'postcode' => '62579-1247',
                'deleted_at' => NULL,
                'created_at' => '2022-01-21 10:29:13',
                'updated_at' => '2022-01-21 10:29:13',
            ),
            64 => 
            array (
                'id' => 65,
                'name' => 'Pregenerated Customer Name',
                'address_parent_id' => 1,
                'location_type_id' => NULL,
                'address_line_1' => '5001 Clifford Mountains',
                'address_line_2' => NULL,
                'address_line_3' => NULL,
                'town' => 'Wendyland',
                'region' => 'Utah',
                'country_id' => 1,
                'postcode' => '47130-1373',
                'deleted_at' => NULL,
                'created_at' => '2022-01-21 10:29:13',
                'updated_at' => '2022-01-21 10:29:13',
            ),
            65 => 
            array (
                'id' => 66,
                'name' => 'Pregenerated Customer Name',
                'address_parent_id' => 1,
                'location_type_id' => NULL,
                'address_line_1' => '5001 Clifford Mountains',
                'address_line_2' => NULL,
                'address_line_3' => NULL,
                'town' => 'Wendyland',
                'region' => 'Utah',
                'country_id' => 1,
                'postcode' => '47130-1373',
                'deleted_at' => NULL,
                'created_at' => '2022-01-21 10:29:13',
                'updated_at' => '2022-01-21 10:29:13',
            ),
            66 => 
            array (
                'id' => 67,
                'name' => 'Gold Restaurant',
                'address_parent_id' => 3,
                'location_type_id' => 4,
                'address_line_1' => '15 Bennett St',
                'address_line_2' => NULL,
                'address_line_3' => NULL,
                'town' => 'Green Point',
                'region' => 'Cape Town',
                'country_id' => 178,
                'postcode' => '8005',
                'deleted_at' => NULL,
                'created_at' => '2022-01-21 10:45:10',
                'updated_at' => '2022-01-21 10:45:10',
            ),
            67 => 
            array (
                'id' => 68,
                'name' => 'Soweto Tour',
                'address_parent_id' => 3,
                'location_type_id' => 5,
                'address_line_1' => 'Soweto Tourist Centre',
                'address_line_2' => NULL,
                'address_line_3' => NULL,
                'town' => 'Soweto',
                'region' => 'Johannesburg',
                'country_id' => 178,
                'postcode' => '1808',
                'deleted_at' => NULL,
                'created_at' => '2022-01-21 11:01:07',
                'updated_at' => '2022-01-21 11:01:07',
            ),
            68 => 
            array (
                'id' => 69,
                'name' => 'London Heathrow Airport',
                'address_parent_id' => 4,
                'location_type_id' => 6,
                'address_line_1' => 'The Compass Centre',
                'address_line_2' => 'Nelson Road',
                'address_line_3' => NULL,
                'town' => 'Hounslow',
                'region' => 'Middlesex',
                'country_id' => 95,
                'postcode' => 'TW6 2GW',
                'deleted_at' => NULL,
                'created_at' => '2022-01-21 11:17:13',
                'updated_at' => '2022-01-21 11:17:13',
            ),
            69 => 
            array (
                'id' => 70,
                'name' => 'O.R. Tambo International Airport',
                'address_parent_id' => 4,
                'location_type_id' => 6,
                'address_line_1' => '1 Jones Rd',
                'address_line_2' => NULL,
                'address_line_3' => NULL,
                'town' => 'Kempton Park',
                'region' => 'Johannesburg',
                'country_id' => 178,
                'postcode' => '1632',
                'deleted_at' => NULL,
                'created_at' => '2022-01-21 11:19:21',
                'updated_at' => '2022-01-21 11:19:21',
            ),
            70 => 
            array (
                'id' => 71,
                'name' => 'Cape Town International Airport',
                'address_parent_id' => 4,
                'location_type_id' => 6,
                'address_line_1' => 'Matroosfontein',
                'address_line_2' => NULL,
                'address_line_3' => NULL,
                'town' => NULL,
                'region' => 'Cape Town',
                'country_id' => 178,
                'postcode' => '7490',
                'deleted_at' => NULL,
                'created_at' => '2022-01-21 12:32:40',
                'updated_at' => '2022-01-21 12:32:40',
            ),
        ));
        
        
    }
}
