<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class CountriesTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('countries')->delete();
        
        \DB::table('countries')->insert(array (
            0 => 
            array (
                'id' => 1,
                'numeric_code' => '248',
                'alpha_code' => 'ALA',
                'name' => 'Åland Islands',
                'dialing_code' => '+35818',
                'created_at' => '2022-03-11 11:36:11',
                'updated_at' => '2022-03-11 11:36:11',
                'deleted_at' => NULL,
            ),
            1 => 
            array (
                'id' => 2,
                'numeric_code' => '254',
                'alpha_code' => 'GUF',
                'name' => 'French Guiana',
                'dialing_code' => '+594',
                'created_at' => '2022-03-11 11:36:11',
                'updated_at' => '2022-03-11 11:36:11',
                'deleted_at' => NULL,
            ),
            2 => 
            array (
                'id' => 3,
                'numeric_code' => '296',
                'alpha_code' => 'KIR',
                'name' => 'Kiribati',
                'dialing_code' => '+686',
                'created_at' => '2022-03-11 11:36:11',
                'updated_at' => '2022-03-11 11:36:11',
                'deleted_at' => NULL,
            ),
            3 => 
            array (
                'id' => 4,
                'numeric_code' => '204',
                'alpha_code' => 'BEN',
                'name' => 'Benin',
                'dialing_code' => '+229',
                'created_at' => '2022-03-11 11:36:11',
                'updated_at' => '2022-03-11 11:36:11',
                'deleted_at' => NULL,
            ),
            4 => 
            array (
                'id' => 5,
                'numeric_code' => '422',
                'alpha_code' => 'LBN',
                'name' => 'Lebanon',
                'dialing_code' => '+961',
                'created_at' => '2022-03-11 11:36:11',
                'updated_at' => '2022-03-11 11:36:11',
                'deleted_at' => NULL,
            ),
            5 => 
            array (
                'id' => 6,
                'numeric_code' => '663',
                'alpha_code' => 'MAF',
                'name' => 'Saint Martin',
                'dialing_code' => '+590',
                'created_at' => '2022-03-11 11:36:11',
                'updated_at' => '2022-03-11 11:36:11',
                'deleted_at' => NULL,
            ),
            6 => 
            array (
                'id' => 7,
                'numeric_code' => '388',
                'alpha_code' => 'JAM',
                'name' => 'Jamaica',
                'dialing_code' => '+1876',
                'created_at' => '2022-03-11 11:36:11',
                'updated_at' => '2022-03-11 11:36:11',
                'deleted_at' => NULL,
            ),
            7 => 
            array (
                'id' => 8,
                'numeric_code' => '499',
                'alpha_code' => 'MNE',
                'name' => 'Montenegro',
                'dialing_code' => '+382',
                'created_at' => '2022-03-11 11:36:11',
                'updated_at' => '2022-03-11 11:36:11',
                'deleted_at' => NULL,
            ),
            8 => 
            array (
                'id' => 9,
                'numeric_code' => '238',
                'alpha_code' => 'FLK',
                'name' => 'Falkland Islands',
                'dialing_code' => '+500',
                'created_at' => '2022-03-11 11:36:11',
                'updated_at' => '2022-03-11 11:36:11',
                'deleted_at' => NULL,
            ),
            9 => 
            array (
                'id' => 10,
                'numeric_code' => '174',
                'alpha_code' => 'COM',
                'name' => 'Comoros',
                'dialing_code' => '+269',
                'created_at' => '2022-03-11 11:36:11',
                'updated_at' => '2022-03-11 11:36:11',
                'deleted_at' => NULL,
            ),
            10 => 
            array (
                'id' => 11,
                'numeric_code' => '716',
                'alpha_code' => 'ZWE',
                'name' => 'Zimbabwe',
                'dialing_code' => '+263',
                'created_at' => '2022-03-11 11:36:11',
                'updated_at' => '2022-03-11 11:36:11',
                'deleted_at' => NULL,
            ),
            11 => 
            array (
                'id' => 12,
                'numeric_code' => '148',
                'alpha_code' => 'TCD',
                'name' => 'Chad',
                'dialing_code' => '+235',
                'created_at' => '2022-03-11 11:36:11',
                'updated_at' => '2022-03-11 11:36:11',
                'deleted_at' => NULL,
            ),
            12 => 
            array (
                'id' => 13,
                'numeric_code' => '612',
                'alpha_code' => 'PCN',
                'name' => 'Pitcairn Islands',
                'dialing_code' => '+64',
                'created_at' => '2022-03-11 11:36:11',
                'updated_at' => '2022-03-11 11:36:11',
                'deleted_at' => NULL,
            ),
            13 => 
            array (
                'id' => 14,
                'numeric_code' => '231',
                'alpha_code' => 'ETH',
                'name' => 'Ethiopia',
                'dialing_code' => '+251',
                'created_at' => '2022-03-11 11:36:11',
                'updated_at' => '2022-03-11 11:36:11',
                'deleted_at' => NULL,
            ),
            14 => 
            array (
                'id' => 15,
                'numeric_code' => '020',
                'alpha_code' => 'AND',
                'name' => 'Andorra',
                'dialing_code' => '+376',
                'created_at' => '2022-03-11 11:36:11',
                'updated_at' => '2022-03-11 11:36:11',
                'deleted_at' => NULL,
            ),
            15 => 
            array (
                'id' => 16,
                'numeric_code' => '258',
                'alpha_code' => 'PYF',
                'name' => 'French Polynesia',
                'dialing_code' => '+689',
                'created_at' => '2022-03-11 11:36:11',
                'updated_at' => '2022-03-11 11:36:11',
                'deleted_at' => NULL,
            ),
            16 => 
            array (
                'id' => 17,
                'numeric_code' => '028',
                'alpha_code' => 'ATG',
                'name' => 'Antigua and Barbuda',
                'dialing_code' => '+1268',
                'created_at' => '2022-03-11 11:36:11',
                'updated_at' => '2022-03-11 11:36:11',
                'deleted_at' => NULL,
            ),
            17 => 
            array (
                'id' => 18,
                'numeric_code' => '292',
                'alpha_code' => 'GIB',
                'name' => 'Gibraltar',
                'dialing_code' => '+350',
                'created_at' => '2022-03-11 11:36:11',
                'updated_at' => '2022-03-11 11:36:11',
                'deleted_at' => NULL,
            ),
            18 => 
            array (
                'id' => 19,
                'numeric_code' => '840',
                'alpha_code' => 'USA',
                'name' => 'United States',
                'dialing_code' => '+1',
                'created_at' => '2022-03-11 11:36:11',
                'updated_at' => '2022-03-11 11:36:11',
                'deleted_at' => NULL,
            ),
            19 => 
            array (
                'id' => 20,
                'numeric_code' => '624',
                'alpha_code' => 'GNB',
                'name' => 'Guinea-Bissau',
                'dialing_code' => '+245',
                'created_at' => '2022-03-11 11:36:11',
                'updated_at' => '2022-03-11 11:36:11',
                'deleted_at' => NULL,
            ),
            20 => 
            array (
                'id' => 21,
                'numeric_code' => '239',
                'alpha_code' => 'SGS',
                'name' => 'South Georgia',
                'dialing_code' => '+500',
                'created_at' => '2022-03-11 11:36:11',
                'updated_at' => '2022-03-11 11:36:11',
                'deleted_at' => NULL,
            ),
            21 => 
            array (
                'id' => 22,
                'numeric_code' => '124',
                'alpha_code' => 'CAN',
                'name' => 'Canada',
                'dialing_code' => '+1',
                'created_at' => '2022-03-11 11:36:11',
                'updated_at' => '2022-03-11 11:36:11',
                'deleted_at' => NULL,
            ),
            22 => 
            array (
                'id' => 23,
                'numeric_code' => '404',
                'alpha_code' => 'KEN',
                'name' => 'Kenya',
                'dialing_code' => '+254',
                'created_at' => '2022-03-11 11:36:11',
                'updated_at' => '2022-03-11 11:36:11',
                'deleted_at' => NULL,
            ),
            23 => 
            array (
                'id' => 24,
                'numeric_code' => '132',
                'alpha_code' => 'CPV',
                'name' => 'Cape Verde',
                'dialing_code' => '+238',
                'created_at' => '2022-03-11 11:36:11',
                'updated_at' => '2022-03-11 11:36:11',
                'deleted_at' => NULL,
            ),
            24 => 
            array (
                'id' => 25,
                'numeric_code' => '184',
                'alpha_code' => 'COK',
                'name' => 'Cook Islands',
                'dialing_code' => '+682',
                'created_at' => '2022-03-11 11:36:11',
                'updated_at' => '2022-03-11 11:36:11',
                'deleted_at' => NULL,
            ),
            25 => 
            array (
                'id' => 26,
                'numeric_code' => '268',
                'alpha_code' => 'GEO',
                'name' => 'Georgia',
                'dialing_code' => '+995',
                'created_at' => '2022-03-11 11:36:11',
                'updated_at' => '2022-03-11 11:36:11',
                'deleted_at' => NULL,
            ),
            26 => 
            array (
                'id' => 27,
                'numeric_code' => '090',
                'alpha_code' => 'SLB',
                'name' => 'Solomon Islands',
                'dialing_code' => '+677',
                'created_at' => '2022-03-11 11:36:11',
                'updated_at' => '2022-03-11 11:36:11',
                'deleted_at' => NULL,
            ),
            27 => 
            array (
                'id' => 28,
                'numeric_code' => '156',
                'alpha_code' => 'CHN',
                'name' => 'China',
                'dialing_code' => '+86',
                'created_at' => '2022-03-11 11:36:11',
                'updated_at' => '2022-03-11 11:36:11',
                'deleted_at' => NULL,
            ),
            28 => 
            array (
                'id' => 29,
                'numeric_code' => '646',
                'alpha_code' => 'RWA',
                'name' => 'Rwanda',
                'dialing_code' => '+250',
                'created_at' => '2022-03-11 11:36:11',
                'updated_at' => '2022-03-11 11:36:11',
                'deleted_at' => NULL,
            ),
            29 => 
            array (
                'id' => 30,
                'numeric_code' => '112',
                'alpha_code' => 'BLR',
                'name' => 'Belarus',
                'dialing_code' => '+375',
                'created_at' => '2022-03-11 11:36:11',
                'updated_at' => '2022-03-11 11:36:11',
                'deleted_at' => NULL,
            ),
            30 => 
            array (
                'id' => 31,
                'numeric_code' => '474',
                'alpha_code' => 'MTQ',
                'name' => 'Martinique',
                'dialing_code' => '+596',
                'created_at' => '2022-03-11 11:36:11',
                'updated_at' => '2022-03-11 11:36:11',
                'deleted_at' => NULL,
            ),
            31 => 
            array (
                'id' => 32,
                'numeric_code' => '638',
                'alpha_code' => 'REU',
                'name' => 'Réunion',
                'dialing_code' => '+262',
                'created_at' => '2022-03-11 11:36:11',
                'updated_at' => '2022-03-11 11:36:11',
                'deleted_at' => NULL,
            ),
            32 => 
            array (
                'id' => 33,
                'numeric_code' => '586',
                'alpha_code' => 'PAK',
                'name' => 'Pakistan',
                'dialing_code' => '+92',
                'created_at' => '2022-03-11 11:36:11',
                'updated_at' => '2022-03-11 11:36:11',
                'deleted_at' => NULL,
            ),
            33 => 
            array (
                'id' => 34,
                'numeric_code' => '626',
                'alpha_code' => 'TLS',
                'name' => 'Timor-Leste',
                'dialing_code' => '+670',
                'created_at' => '2022-03-11 11:36:11',
                'updated_at' => '2022-03-11 11:36:11',
                'deleted_at' => NULL,
            ),
            34 => 
            array (
                'id' => 35,
                'numeric_code' => '222',
                'alpha_code' => 'SLV',
                'name' => 'El Salvador',
                'dialing_code' => '+503',
                'created_at' => '2022-03-11 11:36:11',
                'updated_at' => '2022-03-11 11:36:11',
                'deleted_at' => NULL,
            ),
            35 => 
            array (
                'id' => 36,
                'numeric_code' => '858',
                'alpha_code' => 'URY',
                'name' => 'Uruguay',
                'dialing_code' => '+598',
                'created_at' => '2022-03-11 11:36:11',
                'updated_at' => '2022-03-11 11:36:11',
                'deleted_at' => NULL,
            ),
            36 => 
            array (
                'id' => 37,
                'numeric_code' => '040',
                'alpha_code' => 'AUT',
                'name' => 'Austria',
                'dialing_code' => '+43',
                'created_at' => '2022-03-11 11:36:11',
                'updated_at' => '2022-03-11 11:36:11',
                'deleted_at' => NULL,
            ),
            37 => 
            array (
                'id' => 38,
                'numeric_code' => '232',
                'alpha_code' => 'ERI',
                'name' => 'Eritrea',
                'dialing_code' => '+291',
                'created_at' => '2022-03-11 11:36:11',
                'updated_at' => '2022-03-11 11:36:11',
                'deleted_at' => NULL,
            ),
            38 => 
            array (
                'id' => 39,
                'numeric_code' => '710',
                'alpha_code' => 'ZAF',
                'name' => 'South Africa',
                'dialing_code' => '+27',
                'created_at' => '2022-03-11 11:36:11',
                'updated_at' => '2022-03-11 11:36:11',
                'deleted_at' => NULL,
            ),
            39 => 
            array (
                'id' => 40,
                'numeric_code' => '894',
                'alpha_code' => 'ZMB',
                'name' => 'Zambia',
                'dialing_code' => '+260',
                'created_at' => '2022-03-11 11:36:11',
                'updated_at' => '2022-03-11 11:36:11',
                'deleted_at' => NULL,
            ),
            40 => 
            array (
                'id' => 41,
                'numeric_code' => '562',
                'alpha_code' => 'NER',
                'name' => 'Niger',
                'dialing_code' => '+227',
                'created_at' => '2022-03-11 11:36:11',
                'updated_at' => '2022-03-11 11:36:11',
                'deleted_at' => NULL,
            ),
            41 => 
            array (
                'id' => 42,
                'numeric_code' => '010',
                'alpha_code' => 'ATA',
                'name' => 'Antarctica',
                'dialing_code' => NULL,
                'created_at' => '2022-03-11 11:36:11',
                'updated_at' => '2022-03-11 11:36:11',
                'deleted_at' => NULL,
            ),
            42 => 
            array (
                'id' => 43,
                'numeric_code' => '418',
                'alpha_code' => 'LAO',
                'name' => 'Laos',
                'dialing_code' => '+856',
                'created_at' => '2022-03-11 11:36:11',
                'updated_at' => '2022-03-11 11:36:11',
                'deleted_at' => NULL,
            ),
            43 => 
            array (
                'id' => 44,
                'numeric_code' => '196',
                'alpha_code' => 'CYP',
                'name' => 'Cyprus',
                'dialing_code' => '+357',
                'created_at' => '2022-03-11 11:36:11',
                'updated_at' => '2022-03-11 11:36:11',
                'deleted_at' => NULL,
            ),
            44 => 
            array (
                'id' => 45,
                'numeric_code' => '218',
                'alpha_code' => 'ECU',
                'name' => 'Ecuador',
                'dialing_code' => '+593',
                'created_at' => '2022-03-11 11:36:11',
                'updated_at' => '2022-03-11 11:36:11',
                'deleted_at' => NULL,
            ),
            45 => 
            array (
                'id' => 46,
                'numeric_code' => '430',
                'alpha_code' => 'LBR',
                'name' => 'Liberia',
                'dialing_code' => '+231',
                'created_at' => '2022-03-11 11:36:11',
                'updated_at' => '2022-03-11 11:36:11',
                'deleted_at' => NULL,
            ),
            46 => 
            array (
                'id' => 47,
                'numeric_code' => '800',
                'alpha_code' => 'UGA',
                'name' => 'Uganda',
                'dialing_code' => '+256',
                'created_at' => '2022-03-11 11:36:11',
                'updated_at' => '2022-03-11 11:36:11',
                'deleted_at' => NULL,
            ),
            47 => 
            array (
                'id' => 48,
                'numeric_code' => '580',
                'alpha_code' => 'MNP',
                'name' => 'Northern Mariana Islands',
                'dialing_code' => '+1670',
                'created_at' => '2022-03-11 11:36:11',
                'updated_at' => '2022-03-11 11:36:11',
                'deleted_at' => NULL,
            ),
            48 => 
            array (
                'id' => 49,
                'numeric_code' => '320',
                'alpha_code' => 'GTM',
                'name' => 'Guatemala',
                'dialing_code' => '+502',
                'created_at' => '2022-03-11 11:36:11',
                'updated_at' => '2022-03-11 11:36:11',
                'deleted_at' => NULL,
            ),
            49 => 
            array (
                'id' => 50,
                'numeric_code' => '744',
                'alpha_code' => 'SJM',
                'name' => 'Svalbard and Jan Mayen',
                'dialing_code' => '+4779',
                'created_at' => '2022-03-11 11:36:11',
                'updated_at' => '2022-03-11 11:36:11',
                'deleted_at' => NULL,
            ),
            50 => 
            array (
                'id' => 51,
                'numeric_code' => '104',
                'alpha_code' => 'MMR',
                'name' => 'Myanmar',
                'dialing_code' => '+95',
                'created_at' => '2022-03-11 11:36:11',
                'updated_at' => '2022-03-11 11:36:11',
                'deleted_at' => NULL,
            ),
            51 => 
            array (
                'id' => 52,
                'numeric_code' => '442',
                'alpha_code' => 'LUX',
                'name' => 'Luxembourg',
                'dialing_code' => '+352',
                'created_at' => '2022-03-11 11:36:11',
                'updated_at' => '2022-03-11 11:36:11',
                'deleted_at' => NULL,
            ),
            52 => 
            array (
                'id' => 53,
                'numeric_code' => '214',
                'alpha_code' => 'DOM',
                'name' => 'Dominican Republic',
                'dialing_code' => '+1',
                'created_at' => '2022-03-11 11:36:11',
                'updated_at' => '2022-03-11 11:36:11',
                'deleted_at' => NULL,
            ),
            53 => 
            array (
                'id' => 54,
                'numeric_code' => '762',
                'alpha_code' => 'TJK',
                'name' => 'Tajikistan',
                'dialing_code' => '+992',
                'created_at' => '2022-03-11 11:36:11',
                'updated_at' => '2022-03-11 11:36:11',
                'deleted_at' => NULL,
            ),
            54 => 
            array (
                'id' => 55,
                'numeric_code' => '581',
                'alpha_code' => 'UMI',
                'name' => 'United States Minor Outlying Islands',
                'dialing_code' => '+268',
                'created_at' => '2022-03-11 11:36:11',
                'updated_at' => '2022-03-11 11:36:11',
                'deleted_at' => NULL,
            ),
            55 => 
            array (
                'id' => 56,
                'numeric_code' => '466',
                'alpha_code' => 'MLI',
                'name' => 'Mali',
                'dialing_code' => '+223',
                'created_at' => '2022-03-11 11:36:11',
                'updated_at' => '2022-03-11 11:36:11',
                'deleted_at' => NULL,
            ),
            56 => 
            array (
                'id' => 57,
                'numeric_code' => '862',
                'alpha_code' => 'VEN',
                'name' => 'Venezuela',
                'dialing_code' => '+58',
                'created_at' => '2022-03-11 11:36:11',
                'updated_at' => '2022-03-11 11:36:11',
                'deleted_at' => NULL,
            ),
            57 => 
            array (
                'id' => 58,
                'numeric_code' => '498',
                'alpha_code' => 'MDA',
                'name' => 'Moldova',
                'dialing_code' => '+373',
                'created_at' => '2022-03-11 11:36:11',
                'updated_at' => '2022-03-11 11:36:11',
                'deleted_at' => NULL,
            ),
            58 => 
            array (
                'id' => 59,
                'numeric_code' => '752',
                'alpha_code' => 'SWE',
                'name' => 'Sweden',
                'dialing_code' => '+46',
                'created_at' => '2022-03-11 11:36:11',
                'updated_at' => '2022-03-11 11:36:11',
                'deleted_at' => NULL,
            ),
            59 => 
            array (
                'id' => 60,
                'numeric_code' => '462',
                'alpha_code' => 'MDV',
                'name' => 'Maldives',
                'dialing_code' => '+960',
                'created_at' => '2022-03-11 11:36:11',
                'updated_at' => '2022-03-11 11:36:11',
                'deleted_at' => NULL,
            ),
            60 => 
            array (
                'id' => 61,
                'numeric_code' => '328',
                'alpha_code' => 'GUY',
                'name' => 'Guyana',
                'dialing_code' => '+592',
                'created_at' => '2022-03-11 11:36:11',
                'updated_at' => '2022-03-11 11:36:11',
                'deleted_at' => NULL,
            ),
            61 => 
            array (
                'id' => 62,
                'numeric_code' => '608',
                'alpha_code' => 'PHL',
                'name' => 'Philippines',
                'dialing_code' => '+63',
                'created_at' => '2022-03-11 11:36:11',
                'updated_at' => '2022-03-11 11:36:11',
                'deleted_at' => NULL,
            ),
            62 => 
            array (
                'id' => 63,
                'numeric_code' => '876',
                'alpha_code' => 'WLF',
                'name' => 'Wallis and Futuna',
                'dialing_code' => '+681',
                'created_at' => '2022-03-11 11:36:11',
                'updated_at' => '2022-03-11 11:36:11',
                'deleted_at' => NULL,
            ),
            63 => 
            array (
                'id' => 64,
                'numeric_code' => '116',
                'alpha_code' => 'KHM',
                'name' => 'Cambodia',
                'dialing_code' => '+855',
                'created_at' => '2022-03-11 11:36:11',
                'updated_at' => '2022-03-11 11:36:11',
                'deleted_at' => NULL,
            ),
            64 => 
            array (
                'id' => 65,
                'numeric_code' => '496',
                'alpha_code' => 'MNG',
                'name' => 'Mongolia',
                'dialing_code' => '+976',
                'created_at' => '2022-03-11 11:36:11',
                'updated_at' => '2022-03-11 11:36:11',
                'deleted_at' => NULL,
            ),
            65 => 
            array (
                'id' => 66,
                'numeric_code' => '760',
                'alpha_code' => 'SYR',
                'name' => 'Syria',
                'dialing_code' => '+963',
                'created_at' => '2022-03-11 11:36:11',
                'updated_at' => '2022-03-11 11:36:11',
                'deleted_at' => NULL,
            ),
            66 => 
            array (
                'id' => 67,
                'numeric_code' => '376',
                'alpha_code' => 'ISR',
                'name' => 'Israel',
                'dialing_code' => '+972',
                'created_at' => '2022-03-11 11:36:11',
                'updated_at' => '2022-03-11 11:36:11',
                'deleted_at' => NULL,
            ),
            67 => 
            array (
                'id' => 68,
                'numeric_code' => '508',
                'alpha_code' => 'MOZ',
                'name' => 'Mozambique',
                'dialing_code' => '+258',
                'created_at' => '2022-03-11 11:36:11',
                'updated_at' => '2022-03-11 11:36:11',
                'deleted_at' => NULL,
            ),
            68 => 
            array (
                'id' => 69,
                'numeric_code' => '036',
                'alpha_code' => 'AUS',
                'name' => 'Australia',
                'dialing_code' => '+61',
                'created_at' => '2022-03-11 11:36:11',
                'updated_at' => '2022-03-11 11:36:11',
                'deleted_at' => NULL,
            ),
            69 => 
            array (
                'id' => 70,
                'numeric_code' => '051',
                'alpha_code' => 'ARM',
                'name' => 'Armenia',
                'dialing_code' => '+374',
                'created_at' => '2022-03-11 11:36:11',
                'updated_at' => '2022-03-11 11:36:11',
                'deleted_at' => NULL,
            ),
            70 => 
            array (
                'id' => 71,
                'numeric_code' => '882',
                'alpha_code' => 'WSM',
                'name' => 'Samoa',
                'dialing_code' => '+685',
                'created_at' => '2022-03-11 11:36:11',
                'updated_at' => '2022-03-11 11:36:11',
                'deleted_at' => NULL,
            ),
            71 => 
            array (
                'id' => 72,
                'numeric_code' => '242',
                'alpha_code' => 'FJI',
                'name' => 'Fiji',
                'dialing_code' => '+679',
                'created_at' => '2022-03-11 11:36:11',
                'updated_at' => '2022-03-11 11:36:11',
                'deleted_at' => NULL,
            ),
            72 => 
            array (
                'id' => 73,
                'numeric_code' => '458',
                'alpha_code' => 'MYS',
                'name' => 'Malaysia',
                'dialing_code' => '+60',
                'created_at' => '2022-03-11 11:36:11',
                'updated_at' => '2022-03-11 11:36:11',
                'deleted_at' => NULL,
            ),
            73 => 
            array (
                'id' => 74,
                'numeric_code' => '776',
                'alpha_code' => 'TON',
                'name' => 'Tonga',
                'dialing_code' => '+676',
                'created_at' => '2022-03-11 11:36:11',
                'updated_at' => '2022-03-11 11:36:11',
                'deleted_at' => NULL,
            ),
            74 => 
            array (
                'id' => 75,
                'numeric_code' => '250',
                'alpha_code' => 'FRA',
                'name' => 'France',
                'dialing_code' => '+33',
                'created_at' => '2022-03-11 11:36:11',
                'updated_at' => '2022-03-11 11:36:11',
                'deleted_at' => NULL,
            ),
            75 => 
            array (
                'id' => 76,
                'numeric_code' => '662',
                'alpha_code' => 'LCA',
                'name' => 'Saint Lucia',
                'dialing_code' => '+1758',
                'created_at' => '2022-03-11 11:36:11',
                'updated_at' => '2022-03-11 11:36:11',
                'deleted_at' => NULL,
            ),
            76 => 
            array (
                'id' => 77,
                'numeric_code' => '740',
                'alpha_code' => 'SUR',
                'name' => 'Suriname',
                'dialing_code' => '+597',
                'created_at' => '2022-03-11 11:36:11',
                'updated_at' => '2022-03-11 11:36:11',
                'deleted_at' => NULL,
            ),
            77 => 
            array (
                'id' => 78,
                'numeric_code' => '100',
                'alpha_code' => 'BGR',
                'name' => 'Bulgaria',
                'dialing_code' => '+359',
                'created_at' => '2022-03-11 11:36:11',
                'updated_at' => '2022-03-11 11:36:11',
                'deleted_at' => NULL,
            ),
            78 => 
            array (
                'id' => 79,
                'numeric_code' => '076',
                'alpha_code' => 'BRA',
                'name' => 'Brazil',
                'dialing_code' => '+55',
                'created_at' => '2022-03-11 11:36:11',
                'updated_at' => '2022-03-11 11:36:11',
                'deleted_at' => NULL,
            ),
            79 => 
            array (
                'id' => 80,
                'numeric_code' => '360',
                'alpha_code' => 'IDN',
                'name' => 'Indonesia',
                'dialing_code' => '+62',
                'created_at' => '2022-03-11 11:36:11',
                'updated_at' => '2022-03-11 11:36:11',
                'deleted_at' => NULL,
            ),
            80 => 
            array (
                'id' => 81,
                'numeric_code' => '798',
                'alpha_code' => 'TUV',
                'name' => 'Tuvalu',
                'dialing_code' => '+688',
                'created_at' => '2022-03-11 11:36:11',
                'updated_at' => '2022-03-11 11:36:11',
                'deleted_at' => NULL,
            ),
            81 => 
            array (
                'id' => 82,
                'numeric_code' => '585',
                'alpha_code' => 'PLW',
                'name' => 'Palau',
                'dialing_code' => '+680',
                'created_at' => '2022-03-11 11:36:11',
                'updated_at' => '2022-03-11 11:36:11',
                'deleted_at' => NULL,
            ),
            82 => 
            array (
                'id' => 83,
                'numeric_code' => '060',
                'alpha_code' => 'BMU',
                'name' => 'Bermuda',
                'dialing_code' => '+1441',
                'created_at' => '2022-03-11 11:36:11',
                'updated_at' => '2022-03-11 11:36:11',
                'deleted_at' => NULL,
            ),
            83 => 
            array (
                'id' => 84,
                'numeric_code' => '234',
                'alpha_code' => 'FRO',
                'name' => 'Faroe Islands',
                'dialing_code' => '+298',
                'created_at' => '2022-03-11 11:36:11',
                'updated_at' => '2022-03-11 11:36:11',
                'deleted_at' => NULL,
            ),
            84 => 
            array (
                'id' => 85,
                'numeric_code' => '392',
                'alpha_code' => 'JPN',
                'name' => 'Japan',
                'dialing_code' => '+81',
                'created_at' => '2022-03-11 11:36:11',
                'updated_at' => '2022-03-11 11:36:11',
                'deleted_at' => NULL,
            ),
            85 => 
            array (
                'id' => 86,
                'numeric_code' => '630',
                'alpha_code' => 'PRI',
                'name' => 'Puerto Rico',
                'dialing_code' => '+1',
                'created_at' => '2022-03-11 11:36:11',
                'updated_at' => '2022-03-11 11:36:11',
                'deleted_at' => NULL,
            ),
            86 => 
            array (
                'id' => 87,
                'numeric_code' => '056',
                'alpha_code' => 'BEL',
                'name' => 'Belgium',
                'dialing_code' => '+32',
                'created_at' => '2022-03-11 11:36:11',
                'updated_at' => '2022-03-11 11:36:11',
                'deleted_at' => NULL,
            ),
            87 => 
            array (
                'id' => 88,
                'numeric_code' => '724',
                'alpha_code' => 'ESP',
                'name' => 'Spain',
                'dialing_code' => '+34',
                'created_at' => '2022-03-11 11:36:11',
                'updated_at' => '2022-03-11 11:36:11',
                'deleted_at' => NULL,
            ),
            88 => 
            array (
                'id' => 89,
                'numeric_code' => '175',
                'alpha_code' => 'MYT',
                'name' => 'Mayotte',
                'dialing_code' => '+262',
                'created_at' => '2022-03-11 11:36:11',
                'updated_at' => '2022-03-11 11:36:11',
                'deleted_at' => NULL,
            ),
            89 => 
            array (
                'id' => 90,
                'numeric_code' => '352',
                'alpha_code' => 'ISL',
                'name' => 'Iceland',
                'dialing_code' => '+354',
                'created_at' => '2022-03-11 11:36:11',
                'updated_at' => '2022-03-11 11:36:11',
                'deleted_at' => NULL,
            ),
            90 => 
            array (
                'id' => 91,
                'numeric_code' => '372',
                'alpha_code' => 'IRL',
                'name' => 'Ireland',
                'dialing_code' => '+353',
                'created_at' => '2022-03-11 11:36:11',
                'updated_at' => '2022-03-11 11:36:11',
                'deleted_at' => NULL,
            ),
            91 => 
            array (
                'id' => 92,
                'numeric_code' => '417',
                'alpha_code' => 'KGZ',
                'name' => 'Kyrgyzstan',
                'dialing_code' => '+996',
                'created_at' => '2022-03-11 11:36:11',
                'updated_at' => '2022-03-11 11:36:11',
                'deleted_at' => NULL,
            ),
            92 => 
            array (
                'id' => 93,
                'numeric_code' => '748',
                'alpha_code' => 'SWZ',
                'name' => 'Eswatini',
                'dialing_code' => '+268',
                'created_at' => '2022-03-11 11:36:11',
                'updated_at' => '2022-03-11 11:36:11',
                'deleted_at' => NULL,
            ),
            93 => 
            array (
                'id' => 94,
                'numeric_code' => '308',
                'alpha_code' => 'GRD',
                'name' => 'Grenada',
                'dialing_code' => '+1473',
                'created_at' => '2022-03-11 11:36:11',
                'updated_at' => '2022-03-11 11:36:11',
                'deleted_at' => NULL,
            ),
            94 => 
            array (
                'id' => 95,
                'numeric_code' => '108',
                'alpha_code' => 'BDI',
                'name' => 'Burundi',
                'dialing_code' => '+257',
                'created_at' => '2022-03-11 11:36:11',
                'updated_at' => '2022-03-11 11:36:11',
                'deleted_at' => NULL,
            ),
            95 => 
            array (
                'id' => 96,
                'numeric_code' => '780',
                'alpha_code' => 'TTO',
                'name' => 'Trinidad and Tobago',
                'dialing_code' => '+1868',
                'created_at' => '2022-03-11 11:36:11',
                'updated_at' => '2022-03-11 11:36:11',
                'deleted_at' => NULL,
            ),
            96 => 
            array (
                'id' => 97,
                'numeric_code' => '312',
                'alpha_code' => 'GLP',
                'name' => 'Guadeloupe',
                'dialing_code' => '+590',
                'created_at' => '2022-03-11 11:36:11',
                'updated_at' => '2022-03-11 11:36:11',
                'deleted_at' => NULL,
            ),
            97 => 
            array (
                'id' => 98,
                'numeric_code' => '400',
                'alpha_code' => 'JOR',
                'name' => 'Jordan',
                'dialing_code' => '+962',
                'created_at' => '2022-03-11 11:36:11',
                'updated_at' => '2022-03-11 11:36:11',
                'deleted_at' => NULL,
            ),
            98 => 
            array (
                'id' => 99,
                'numeric_code' => '166',
                'alpha_code' => 'CCK',
            'name' => 'Cocos (Keeling) Islands',
                'dialing_code' => '+61',
                'created_at' => '2022-03-11 11:36:11',
                'updated_at' => '2022-03-11 11:36:11',
                'deleted_at' => NULL,
            ),
            99 => 
            array (
                'id' => 100,
                'numeric_code' => '440',
                'alpha_code' => 'LTU',
                'name' => 'Lithuania',
                'dialing_code' => '+370',
                'created_at' => '2022-03-11 11:36:11',
                'updated_at' => '2022-03-11 11:36:11',
                'deleted_at' => NULL,
            ),
            100 => 
            array (
                'id' => 101,
                'numeric_code' => '504',
                'alpha_code' => 'MAR',
                'name' => 'Morocco',
                'dialing_code' => '+212',
                'created_at' => '2022-03-11 11:36:11',
                'updated_at' => '2022-03-11 11:36:11',
                'deleted_at' => NULL,
            ),
            101 => 
            array (
                'id' => 102,
                'numeric_code' => '528',
                'alpha_code' => 'NLD',
                'name' => 'Netherlands',
                'dialing_code' => '+31',
                'created_at' => '2022-03-11 11:36:11',
                'updated_at' => '2022-03-11 11:36:11',
                'deleted_at' => NULL,
            ),
            102 => 
            array (
                'id' => 103,
                'numeric_code' => '086',
                'alpha_code' => 'IOT',
                'name' => 'British Indian Ocean Territory',
                'dialing_code' => '+246',
                'created_at' => '2022-03-11 11:36:11',
                'updated_at' => '2022-03-11 11:36:11',
                'deleted_at' => NULL,
            ),
            103 => 
            array (
                'id' => 104,
                'numeric_code' => '275',
                'alpha_code' => 'PSE',
                'name' => 'Palestine',
                'dialing_code' => '+970',
                'created_at' => '2022-03-11 11:36:11',
                'updated_at' => '2022-03-11 11:36:11',
                'deleted_at' => NULL,
            ),
            104 => 
            array (
                'id' => 105,
                'numeric_code' => '170',
                'alpha_code' => 'COL',
                'name' => 'Colombia',
                'dialing_code' => '+57',
                'created_at' => '2022-03-11 11:36:11',
                'updated_at' => '2022-03-11 11:36:11',
                'deleted_at' => NULL,
            ),
            105 => 
            array (
                'id' => 106,
                'numeric_code' => '531',
                'alpha_code' => 'CUW',
                'name' => 'Curaçao',
                'dialing_code' => '+599',
                'created_at' => '2022-03-11 11:36:11',
                'updated_at' => '2022-03-11 11:36:11',
                'deleted_at' => NULL,
            ),
            106 => 
            array (
                'id' => 107,
                'numeric_code' => '535',
                'alpha_code' => 'BES',
                'name' => 'Caribbean Netherlands',
                'dialing_code' => '+599',
                'created_at' => '2022-03-11 11:36:11',
                'updated_at' => '2022-03-11 11:36:11',
                'deleted_at' => NULL,
            ),
            107 => 
            array (
                'id' => 108,
                'numeric_code' => '084',
                'alpha_code' => 'BLZ',
                'name' => 'Belize',
                'dialing_code' => '+501',
                'created_at' => '2022-03-11 11:36:11',
                'updated_at' => '2022-03-11 11:36:11',
                'deleted_at' => NULL,
            ),
            108 => 
            array (
                'id' => 109,
                'numeric_code' => '666',
                'alpha_code' => 'SPM',
                'name' => 'Saint Pierre and Miquelon',
                'dialing_code' => '+508',
                'created_at' => '2022-03-11 11:36:11',
                'updated_at' => '2022-03-11 11:36:11',
                'deleted_at' => NULL,
            ),
            109 => 
            array (
                'id' => 110,
                'numeric_code' => '480',
                'alpha_code' => 'MUS',
                'name' => 'Mauritius',
                'dialing_code' => '+230',
                'created_at' => '2022-03-11 11:36:11',
                'updated_at' => '2022-03-11 11:36:11',
                'deleted_at' => NULL,
            ),
            110 => 
            array (
                'id' => 111,
                'numeric_code' => '796',
                'alpha_code' => 'TCA',
                'name' => 'Turks and Caicos Islands',
                'dialing_code' => '+1649',
                'created_at' => '2022-03-11 11:36:11',
                'updated_at' => '2022-03-11 11:36:11',
                'deleted_at' => NULL,
            ),
            111 => 
            array (
                'id' => 112,
                'numeric_code' => '064',
                'alpha_code' => 'BTN',
                'name' => 'Bhutan',
                'dialing_code' => '+975',
                'created_at' => '2022-03-11 11:36:11',
                'updated_at' => '2022-03-11 11:36:11',
                'deleted_at' => NULL,
            ),
            112 => 
            array (
                'id' => 113,
                'numeric_code' => '732',
                'alpha_code' => 'ESH',
                'name' => 'Western Sahara',
                'dialing_code' => '+2',
                'created_at' => '2022-03-11 11:36:11',
                'updated_at' => '2022-03-11 11:36:11',
                'deleted_at' => NULL,
            ),
            113 => 
            array (
                'id' => 114,
                'numeric_code' => '262',
                'alpha_code' => 'DJI',
                'name' => 'Djibouti',
                'dialing_code' => '+253',
                'created_at' => '2022-03-11 11:36:11',
                'updated_at' => '2022-03-11 11:36:11',
                'deleted_at' => NULL,
            ),
            114 => 
            array (
                'id' => 115,
                'numeric_code' => '233',
                'alpha_code' => 'EST',
                'name' => 'Estonia',
                'dialing_code' => '+372',
                'created_at' => '2022-03-11 11:36:11',
                'updated_at' => '2022-03-11 11:36:11',
                'deleted_at' => NULL,
            ),
            115 => 
            array (
                'id' => 116,
                'numeric_code' => '854',
                'alpha_code' => 'BFA',
                'name' => 'Burkina Faso',
                'dialing_code' => '+226',
                'created_at' => '2022-03-11 11:36:11',
                'updated_at' => '2022-03-11 11:36:11',
                'deleted_at' => NULL,
            ),
            116 => 
            array (
                'id' => 117,
                'numeric_code' => '336',
                'alpha_code' => 'VAT',
                'name' => 'Vatican City',
                'dialing_code' => '+3',
                'created_at' => '2022-03-11 11:36:11',
                'updated_at' => '2022-03-11 11:36:11',
                'deleted_at' => NULL,
            ),
            117 => 
            array (
                'id' => 118,
                'numeric_code' => '324',
                'alpha_code' => 'GIN',
                'name' => 'Guinea',
                'dialing_code' => '+224',
                'created_at' => '2022-03-11 11:36:11',
                'updated_at' => '2022-03-11 11:36:11',
                'deleted_at' => NULL,
            ),
            118 => 
            array (
                'id' => 119,
                'numeric_code' => '534',
                'alpha_code' => 'SXM',
                'name' => 'Sint Maarten',
                'dialing_code' => '+1721',
                'created_at' => '2022-03-11 11:36:11',
                'updated_at' => '2022-03-11 11:36:11',
                'deleted_at' => NULL,
            ),
            119 => 
            array (
                'id' => 120,
                'numeric_code' => '833',
                'alpha_code' => 'IMN',
                'name' => 'Isle of Man',
                'dialing_code' => '+44',
                'created_at' => '2022-03-11 11:36:11',
                'updated_at' => '2022-03-11 11:36:11',
                'deleted_at' => NULL,
            ),
            120 => 
            array (
                'id' => 121,
                'numeric_code' => '804',
                'alpha_code' => 'UKR',
                'name' => 'Ukraine',
                'dialing_code' => '+380',
                'created_at' => '2022-03-11 11:36:12',
                'updated_at' => '2022-03-11 11:36:12',
                'deleted_at' => NULL,
            ),
            121 => 
            array (
                'id' => 122,
                'numeric_code' => '674',
                'alpha_code' => 'SMR',
                'name' => 'San Marino',
                'dialing_code' => '+378',
                'created_at' => '2022-03-11 11:36:12',
                'updated_at' => '2022-03-11 11:36:12',
                'deleted_at' => NULL,
            ),
            122 => 
            array (
                'id' => 123,
                'numeric_code' => '616',
                'alpha_code' => 'POL',
                'name' => 'Poland',
                'dialing_code' => '+48',
                'created_at' => '2022-03-11 11:36:12',
                'updated_at' => '2022-03-11 11:36:12',
                'deleted_at' => NULL,
            ),
            123 => 
            array (
                'id' => 124,
                'numeric_code' => '591',
                'alpha_code' => 'PAN',
                'name' => 'Panama',
                'dialing_code' => '+507',
                'created_at' => '2022-03-11 11:36:12',
                'updated_at' => '2022-03-11 11:36:12',
                'deleted_at' => NULL,
            ),
            124 => 
            array (
                'id' => 125,
                'numeric_code' => '152',
                'alpha_code' => 'CHL',
                'name' => 'Chile',
                'dialing_code' => '+56',
                'created_at' => '2022-03-11 11:36:12',
                'updated_at' => '2022-03-11 11:36:12',
                'deleted_at' => NULL,
            ),
            125 => 
            array (
                'id' => 126,
                'numeric_code' => '620',
                'alpha_code' => 'PRT',
                'name' => 'Portugal',
                'dialing_code' => '+351',
                'created_at' => '2022-03-11 11:36:12',
                'updated_at' => '2022-03-11 11:36:12',
                'deleted_at' => NULL,
            ),
            126 => 
            array (
                'id' => 127,
                'numeric_code' => '072',
                'alpha_code' => 'BWA',
                'name' => 'Botswana',
                'dialing_code' => '+267',
                'created_at' => '2022-03-11 11:36:12',
                'updated_at' => '2022-03-11 11:36:12',
                'deleted_at' => NULL,
            ),
            127 => 
            array (
                'id' => 128,
                'numeric_code' => '266',
                'alpha_code' => 'GAB',
                'name' => 'Gabon',
                'dialing_code' => '+241',
                'created_at' => '2022-03-11 11:36:12',
                'updated_at' => '2022-03-11 11:36:12',
                'deleted_at' => NULL,
            ),
            128 => 
            array (
                'id' => 129,
                'numeric_code' => '574',
                'alpha_code' => 'NFK',
                'name' => 'Norfolk Island',
                'dialing_code' => '+672',
                'created_at' => '2022-03-11 11:36:12',
                'updated_at' => '2022-03-11 11:36:12',
                'deleted_at' => NULL,
            ),
            129 => 
            array (
                'id' => 130,
                'numeric_code' => '795',
                'alpha_code' => 'TKM',
                'name' => 'Turkmenistan',
                'dialing_code' => '+993',
                'created_at' => '2022-03-11 11:36:12',
                'updated_at' => '2022-03-11 11:36:12',
                'deleted_at' => NULL,
            ),
            130 => 
            array (
                'id' => 131,
                'numeric_code' => '316',
                'alpha_code' => 'GUM',
                'name' => 'Guam',
                'dialing_code' => '+1671',
                'created_at' => '2022-03-11 11:36:12',
                'updated_at' => '2022-03-11 11:36:12',
                'deleted_at' => NULL,
            ),
            131 => 
            array (
                'id' => 132,
                'numeric_code' => '380',
                'alpha_code' => 'ITA',
                'name' => 'Italy',
                'dialing_code' => '+39',
                'created_at' => '2022-03-11 11:36:12',
                'updated_at' => '2022-03-11 11:36:12',
                'deleted_at' => NULL,
            ),
            132 => 
            array (
                'id' => 133,
                'numeric_code' => '450',
                'alpha_code' => 'MDG',
                'name' => 'Madagascar',
                'dialing_code' => '+261',
                'created_at' => '2022-03-11 11:36:12',
                'updated_at' => '2022-03-11 11:36:12',
                'deleted_at' => NULL,
            ),
            133 => 
            array (
                'id' => 134,
                'numeric_code' => '304',
                'alpha_code' => 'GRL',
                'name' => 'Greenland',
                'dialing_code' => '+299',
                'created_at' => '2022-03-11 11:36:12',
                'updated_at' => '2022-03-11 11:36:12',
                'deleted_at' => NULL,
            ),
            134 => 
            array (
                'id' => 135,
                'numeric_code' => '180',
                'alpha_code' => 'COD',
                'name' => 'DR Congo',
                'dialing_code' => '+243',
                'created_at' => '2022-03-11 11:36:12',
                'updated_at' => '2022-03-11 11:36:12',
                'deleted_at' => NULL,
            ),
            135 => 
            array (
                'id' => 136,
                'numeric_code' => '704',
                'alpha_code' => 'VNM',
                'name' => 'Vietnam',
                'dialing_code' => '+84',
                'created_at' => '2022-03-11 11:36:12',
                'updated_at' => '2022-03-11 11:36:12',
                'deleted_at' => NULL,
            ),
            136 => 
            array (
                'id' => 137,
                'numeric_code' => '212',
                'alpha_code' => 'DMA',
                'name' => 'Dominica',
                'dialing_code' => '+1767',
                'created_at' => '2022-03-11 11:36:12',
                'updated_at' => '2022-03-11 11:36:12',
                'deleted_at' => NULL,
            ),
            137 => 
            array (
                'id' => 138,
                'numeric_code' => '583',
                'alpha_code' => 'FSM',
                'name' => 'Micronesia',
                'dialing_code' => '+691',
                'created_at' => '2022-03-11 11:36:12',
                'updated_at' => '2022-03-11 11:36:12',
                'deleted_at' => NULL,
            ),
            138 => 
            array (
                'id' => 139,
                'numeric_code' => '792',
                'alpha_code' => 'TUR',
                'name' => 'Turkey',
                'dialing_code' => '+90',
                'created_at' => '2022-03-11 11:36:12',
                'updated_at' => '2022-03-11 11:36:12',
                'deleted_at' => NULL,
            ),
            139 => 
            array (
                'id' => 140,
                'numeric_code' => '398',
                'alpha_code' => 'KAZ',
                'name' => 'Kazakhstan',
                'dialing_code' => '+7',
                'created_at' => '2022-03-11 11:36:12',
                'updated_at' => '2022-03-11 11:36:12',
                'deleted_at' => NULL,
            ),
            140 => 
            array (
                'id' => 141,
                'numeric_code' => '074',
                'alpha_code' => 'BVT',
                'name' => 'Bouvet Island',
                'dialing_code' => '+47',
                'created_at' => '2022-03-11 11:36:12',
                'updated_at' => '2022-03-11 11:36:12',
                'deleted_at' => NULL,
            ),
            141 => 
            array (
                'id' => 142,
                'numeric_code' => '540',
                'alpha_code' => 'NCL',
                'name' => 'New Caledonia',
                'dialing_code' => '+687',
                'created_at' => '2022-03-11 11:36:12',
                'updated_at' => '2022-03-11 11:36:12',
                'deleted_at' => NULL,
            ),
            142 => 
            array (
                'id' => 143,
                'numeric_code' => '642',
                'alpha_code' => 'ROU',
                'name' => 'Romania',
                'dialing_code' => '+40',
                'created_at' => '2022-03-11 11:36:12',
                'updated_at' => '2022-03-11 11:36:12',
                'deleted_at' => NULL,
            ),
            143 => 
            array (
                'id' => 144,
                'numeric_code' => '428',
                'alpha_code' => 'LVA',
                'name' => 'Latvia',
                'dialing_code' => '+371',
                'created_at' => '2022-03-11 11:36:12',
                'updated_at' => '2022-03-11 11:36:12',
                'deleted_at' => NULL,
            ),
            144 => 
            array (
                'id' => 145,
                'numeric_code' => '788',
                'alpha_code' => 'TUN',
                'name' => 'Tunisia',
                'dialing_code' => '+216',
                'created_at' => '2022-03-11 11:36:12',
                'updated_at' => '2022-03-11 11:36:12',
                'deleted_at' => NULL,
            ),
            145 => 
            array (
                'id' => 146,
                'numeric_code' => '208',
                'alpha_code' => 'DNK',
                'name' => 'Denmark',
                'dialing_code' => '+45',
                'created_at' => '2022-03-11 11:36:12',
                'updated_at' => '2022-03-11 11:36:12',
                'deleted_at' => NULL,
            ),
            146 => 
            array (
                'id' => 147,
                'numeric_code' => '348',
                'alpha_code' => 'HUN',
                'name' => 'Hungary',
                'dialing_code' => '+36',
                'created_at' => '2022-03-11 11:36:12',
                'updated_at' => '2022-03-11 11:36:12',
                'deleted_at' => NULL,
            ),
            147 => 
            array (
                'id' => 148,
                'numeric_code' => '860',
                'alpha_code' => 'UZB',
                'name' => 'Uzbekistan',
                'dialing_code' => '+998',
                'created_at' => '2022-03-11 11:36:12',
                'updated_at' => '2022-03-11 11:36:12',
                'deleted_at' => NULL,
            ),
            148 => 
            array (
                'id' => 149,
                'numeric_code' => '643',
                'alpha_code' => 'RUS',
                'name' => 'Russia',
                'dialing_code' => '+7',
                'created_at' => '2022-03-11 11:36:12',
                'updated_at' => '2022-03-11 11:36:12',
                'deleted_at' => NULL,
            ),
            149 => 
            array (
                'id' => 150,
                'numeric_code' => '288',
                'alpha_code' => 'GHA',
                'name' => 'Ghana',
                'dialing_code' => '+233',
                'created_at' => '2022-03-11 11:36:12',
                'updated_at' => '2022-03-11 11:36:12',
                'deleted_at' => NULL,
            ),
            150 => 
            array (
                'id' => 151,
                'numeric_code' => '178',
                'alpha_code' => 'COG',
                'name' => 'Republic of the Congo',
                'dialing_code' => '+242',
                'created_at' => '2022-03-11 11:36:12',
                'updated_at' => '2022-03-11 11:36:12',
                'deleted_at' => NULL,
            ),
            151 => 
            array (
                'id' => 152,
                'numeric_code' => '334',
                'alpha_code' => 'HMD',
                'name' => 'Heard Island and McDonald Islands',
                'dialing_code' => NULL,
                'created_at' => '2022-03-11 11:36:12',
                'updated_at' => '2022-03-11 11:36:12',
                'deleted_at' => NULL,
            ),
            152 => 
            array (
                'id' => 153,
                'numeric_code' => '533',
                'alpha_code' => 'ABW',
                'name' => 'Aruba',
                'dialing_code' => '+297',
                'created_at' => '2022-03-11 11:36:12',
                'updated_at' => '2022-03-11 11:36:12',
                'deleted_at' => NULL,
            ),
            153 => 
            array (
                'id' => 154,
                'numeric_code' => '024',
                'alpha_code' => 'AGO',
                'name' => 'Angola',
                'dialing_code' => '+244',
                'created_at' => '2022-03-11 11:36:12',
                'updated_at' => '2022-03-11 11:36:12',
                'deleted_at' => NULL,
            ),
            154 => 
            array (
                'id' => 155,
                'numeric_code' => '756',
                'alpha_code' => 'CHE',
                'name' => 'Switzerland',
                'dialing_code' => '+41',
                'created_at' => '2022-03-11 11:36:12',
                'updated_at' => '2022-03-11 11:36:12',
                'deleted_at' => NULL,
            ),
            155 => 
            array (
                'id' => 156,
                'numeric_code' => '158',
                'alpha_code' => 'TWN',
                'name' => 'Taiwan',
                'dialing_code' => '+886',
                'created_at' => '2022-03-11 11:36:12',
                'updated_at' => '2022-03-11 11:36:12',
                'deleted_at' => NULL,
            ),
            156 => 
            array (
                'id' => 157,
                'numeric_code' => '807',
                'alpha_code' => 'MKD',
                'name' => 'North Macedonia',
                'dialing_code' => '+389',
                'created_at' => '2022-03-11 11:36:12',
                'updated_at' => '2022-03-11 11:36:12',
                'deleted_at' => NULL,
            ),
            157 => 
            array (
                'id' => 158,
                'numeric_code' => '694',
                'alpha_code' => 'SLE',
                'name' => 'Sierra Leone',
                'dialing_code' => '+232',
                'created_at' => '2022-03-11 11:36:12',
                'updated_at' => '2022-03-11 11:36:12',
                'deleted_at' => NULL,
            ),
            158 => 
            array (
                'id' => 159,
                'numeric_code' => '203',
                'alpha_code' => 'CZE',
                'name' => 'Czechia',
                'dialing_code' => '+420',
                'created_at' => '2022-03-11 11:36:12',
                'updated_at' => '2022-03-11 11:36:12',
                'deleted_at' => NULL,
            ),
            159 => 
            array (
                'id' => 160,
                'numeric_code' => '500',
                'alpha_code' => 'MSR',
                'name' => 'Montserrat',
                'dialing_code' => '+1664',
                'created_at' => '2022-03-11 11:36:12',
                'updated_at' => '2022-03-11 11:36:12',
                'deleted_at' => NULL,
            ),
            160 => 
            array (
                'id' => 161,
                'numeric_code' => '604',
                'alpha_code' => 'PER',
                'name' => 'Peru',
                'dialing_code' => '+51',
                'created_at' => '2022-03-11 11:36:12',
                'updated_at' => '2022-03-11 11:36:12',
                'deleted_at' => NULL,
            ),
            161 => 
            array (
                'id' => 162,
                'numeric_code' => '096',
                'alpha_code' => 'BRN',
                'name' => 'Brunei',
                'dialing_code' => '+673',
                'created_at' => '2022-03-11 11:36:12',
                'updated_at' => '2022-03-11 11:36:12',
                'deleted_at' => NULL,
            ),
            162 => 
            array (
                'id' => 163,
                'numeric_code' => '887',
                'alpha_code' => 'YEM',
                'name' => 'Yemen',
                'dialing_code' => '+967',
                'created_at' => '2022-03-11 11:36:12',
                'updated_at' => '2022-03-11 11:36:12',
                'deleted_at' => NULL,
            ),
            163 => 
            array (
                'id' => 164,
                'numeric_code' => '191',
                'alpha_code' => 'HRV',
                'name' => 'Croatia',
                'dialing_code' => '+385',
                'created_at' => '2022-03-11 11:36:12',
                'updated_at' => '2022-03-11 11:36:12',
                'deleted_at' => NULL,
            ),
            164 => 
            array (
                'id' => 165,
                'numeric_code' => '434',
                'alpha_code' => 'LBY',
                'name' => 'Libya',
                'dialing_code' => '+218',
                'created_at' => '2022-03-11 11:36:12',
                'updated_at' => '2022-03-11 11:36:12',
                'deleted_at' => NULL,
            ),
            165 => 
            array (
                'id' => 166,
                'numeric_code' => '600',
                'alpha_code' => 'PRY',
                'name' => 'Paraguay',
                'dialing_code' => '+595',
                'created_at' => '2022-03-11 11:36:12',
                'updated_at' => '2022-03-11 11:36:12',
                'deleted_at' => NULL,
            ),
            166 => 
            array (
                'id' => 167,
                'numeric_code' => '438',
                'alpha_code' => 'LIE',
                'name' => 'Liechtenstein',
                'dialing_code' => '+423',
                'created_at' => '2022-03-11 11:36:12',
                'updated_at' => '2022-03-11 11:36:12',
                'deleted_at' => NULL,
            ),
            167 => 
            array (
                'id' => 168,
                'numeric_code' => '703',
                'alpha_code' => 'SVK',
                'name' => 'Slovakia',
                'dialing_code' => '+421',
                'created_at' => '2022-03-11 11:36:12',
                'updated_at' => '2022-03-11 11:36:12',
                'deleted_at' => NULL,
            ),
            168 => 
            array (
                'id' => 169,
                'numeric_code' => '818',
                'alpha_code' => 'EGY',
                'name' => 'Egypt',
                'dialing_code' => '+20',
                'created_at' => '2022-03-11 11:36:12',
                'updated_at' => '2022-03-11 11:36:12',
                'deleted_at' => NULL,
            ),
            169 => 
            array (
                'id' => 170,
                'numeric_code' => '144',
                'alpha_code' => 'LKA',
                'name' => 'Sri Lanka',
                'dialing_code' => '+94',
                'created_at' => '2022-03-11 11:36:12',
                'updated_at' => '2022-03-11 11:36:12',
                'deleted_at' => NULL,
            ),
            170 => 
            array (
                'id' => 171,
                'numeric_code' => '688',
                'alpha_code' => 'SRB',
                'name' => 'Serbia',
                'dialing_code' => '+381',
                'created_at' => '2022-03-11 11:36:12',
                'updated_at' => '2022-03-11 11:36:12',
                'deleted_at' => NULL,
            ),
            171 => 
            array (
                'id' => 172,
                'numeric_code' => '831',
                'alpha_code' => 'GGY',
                'name' => 'Guernsey',
                'dialing_code' => '+44',
                'created_at' => '2022-03-11 11:36:12',
                'updated_at' => '2022-03-11 11:36:12',
                'deleted_at' => NULL,
            ),
            172 => 
            array (
                'id' => 173,
                'numeric_code' => '686',
                'alpha_code' => 'SEN',
                'name' => 'Senegal',
                'dialing_code' => '+221',
                'created_at' => '2022-03-11 11:36:12',
                'updated_at' => '2022-03-11 11:36:12',
                'deleted_at' => NULL,
            ),
            173 => 
            array (
                'id' => 174,
                'numeric_code' => '554',
                'alpha_code' => 'NZL',
                'name' => 'New Zealand',
                'dialing_code' => '+64',
                'created_at' => '2022-03-11 11:36:12',
                'updated_at' => '2022-03-11 11:36:12',
                'deleted_at' => NULL,
            ),
            174 => 
            array (
                'id' => 175,
                'numeric_code' => '832',
                'alpha_code' => 'JEY',
                'name' => 'Jersey',
                'dialing_code' => '+44',
                'created_at' => '2022-03-11 11:36:12',
                'updated_at' => '2022-03-11 11:36:12',
                'deleted_at' => NULL,
            ),
            175 => 
            array (
                'id' => 176,
                'numeric_code' => '408',
                'alpha_code' => 'PRK',
                'name' => 'North Korea',
                'dialing_code' => '+850',
                'created_at' => '2022-03-11 11:36:12',
                'updated_at' => '2022-03-11 11:36:12',
                'deleted_at' => NULL,
            ),
            176 => 
            array (
                'id' => 177,
                'numeric_code' => '260',
                'alpha_code' => 'ATF',
                'name' => 'French Southern and Antarctic Lands',
                'dialing_code' => '+262',
                'created_at' => '2022-03-11 11:36:12',
                'updated_at' => '2022-03-11 11:36:12',
                'deleted_at' => NULL,
            ),
            177 => 
            array (
                'id' => 178,
                'numeric_code' => '012',
                'alpha_code' => 'DZA',
                'name' => 'Algeria',
                'dialing_code' => '+213',
                'created_at' => '2022-03-11 11:36:12',
                'updated_at' => '2022-03-11 11:36:12',
                'deleted_at' => NULL,
            ),
            178 => 
            array (
                'id' => 179,
                'numeric_code' => '016',
                'alpha_code' => 'ASM',
                'name' => 'American Samoa',
                'dialing_code' => '+1684',
                'created_at' => '2022-03-11 11:36:12',
                'updated_at' => '2022-03-11 11:36:12',
                'deleted_at' => NULL,
            ),
            179 => 
            array (
                'id' => 180,
                'numeric_code' => '706',
                'alpha_code' => 'SOM',
                'name' => 'Somalia',
                'dialing_code' => '+252',
                'created_at' => '2022-03-11 11:36:12',
                'updated_at' => '2022-03-11 11:36:12',
                'deleted_at' => NULL,
            ),
            180 => 
            array (
                'id' => 181,
                'numeric_code' => '570',
                'alpha_code' => 'NIU',
                'name' => 'Niue',
                'dialing_code' => '+683',
                'created_at' => '2022-03-11 11:36:12',
                'updated_at' => '2022-03-11 11:36:12',
                'deleted_at' => NULL,
            ),
            181 => 
            array (
                'id' => 182,
                'numeric_code' => '729',
                'alpha_code' => 'SDN',
                'name' => 'Sudan',
                'dialing_code' => '+249',
                'created_at' => '2022-03-11 11:36:12',
                'updated_at' => '2022-03-11 11:36:12',
                'deleted_at' => NULL,
            ),
            182 => 
            array (
                'id' => 183,
                'numeric_code' => '566',
                'alpha_code' => 'NGA',
                'name' => 'Nigeria',
                'dialing_code' => '+234',
                'created_at' => '2022-03-11 11:36:12',
                'updated_at' => '2022-03-11 11:36:12',
                'deleted_at' => NULL,
            ),
            183 => 
            array (
                'id' => 184,
                'numeric_code' => '584',
                'alpha_code' => 'MHL',
                'name' => 'Marshall Islands',
                'dialing_code' => '+692',
                'created_at' => '2022-03-11 11:36:12',
                'updated_at' => '2022-03-11 11:36:12',
                'deleted_at' => NULL,
            ),
            184 => 
            array (
                'id' => 185,
                'numeric_code' => '008',
                'alpha_code' => 'ALB',
                'name' => 'Albania',
                'dialing_code' => '+355',
                'created_at' => '2022-03-11 11:36:12',
                'updated_at' => '2022-03-11 11:36:12',
                'deleted_at' => NULL,
            ),
            185 => 
            array (
                'id' => 186,
                'numeric_code' => '068',
                'alpha_code' => 'BOL',
                'name' => 'Bolivia',
                'dialing_code' => '+591',
                'created_at' => '2022-03-11 11:36:12',
                'updated_at' => '2022-03-11 11:36:12',
                'deleted_at' => NULL,
            ),
            186 => 
            array (
                'id' => 187,
                'numeric_code' => '598',
                'alpha_code' => 'PNG',
                'name' => 'Papua New Guinea',
                'dialing_code' => '+675',
                'created_at' => '2022-03-11 11:36:12',
                'updated_at' => '2022-03-11 11:36:12',
                'deleted_at' => NULL,
            ),
            187 => 
            array (
                'id' => 188,
                'numeric_code' => '634',
                'alpha_code' => 'QAT',
                'name' => 'Qatar',
                'dialing_code' => '+974',
                'created_at' => '2022-03-11 11:36:12',
                'updated_at' => '2022-03-11 11:36:12',
                'deleted_at' => NULL,
            ),
            188 => 
            array (
                'id' => 189,
                'numeric_code' => '052',
                'alpha_code' => 'BRB',
                'name' => 'Barbados',
                'dialing_code' => '+1246',
                'created_at' => '2022-03-11 11:36:12',
                'updated_at' => '2022-03-11 11:36:12',
                'deleted_at' => NULL,
            ),
            189 => 
            array (
                'id' => 190,
                'numeric_code' => '188',
                'alpha_code' => 'CRI',
                'name' => 'Costa Rica',
                'dialing_code' => '+506',
                'created_at' => '2022-03-11 11:36:12',
                'updated_at' => '2022-03-11 11:36:12',
                'deleted_at' => NULL,
            ),
            190 => 
            array (
                'id' => 191,
                'numeric_code' => '690',
                'alpha_code' => 'SYC',
                'name' => 'Seychelles',
                'dialing_code' => '+248',
                'created_at' => '2022-03-11 11:36:12',
                'updated_at' => '2022-03-11 11:36:12',
                'deleted_at' => NULL,
            ),
            191 => 
            array (
                'id' => 192,
                'numeric_code' => '092',
                'alpha_code' => 'VGB',
                'name' => 'British Virgin Islands',
                'dialing_code' => '+1284',
                'created_at' => '2022-03-11 11:36:12',
                'updated_at' => '2022-03-11 11:36:12',
                'deleted_at' => NULL,
            ),
            192 => 
            array (
                'id' => 193,
                'numeric_code' => '344',
                'alpha_code' => 'HKG',
                'name' => 'Hong Kong',
                'dialing_code' => '+852',
                'created_at' => '2022-03-11 11:36:12',
                'updated_at' => '2022-03-11 11:36:12',
                'deleted_at' => NULL,
            ),
            193 => 
            array (
                'id' => 194,
                'numeric_code' => '004',
                'alpha_code' => 'AFG',
                'name' => 'Afghanistan',
                'dialing_code' => '+93',
                'created_at' => '2022-03-11 11:36:12',
                'updated_at' => '2022-03-11 11:36:12',
                'deleted_at' => NULL,
            ),
            194 => 
            array (
                'id' => 195,
                'numeric_code' => '520',
                'alpha_code' => 'NRU',
                'name' => 'Nauru',
                'dialing_code' => '+674',
                'created_at' => '2022-03-11 11:36:12',
                'updated_at' => '2022-03-11 11:36:12',
                'deleted_at' => NULL,
            ),
            195 => 
            array (
                'id' => 196,
                'numeric_code' => '300',
                'alpha_code' => 'GRC',
                'name' => 'Greece',
                'dialing_code' => '+30',
                'created_at' => '2022-03-11 11:36:12',
                'updated_at' => '2022-03-11 11:36:12',
                'deleted_at' => NULL,
            ),
            196 => 
            array (
                'id' => 197,
                'numeric_code' => '558',
                'alpha_code' => 'NIC',
                'name' => 'Nicaragua',
                'dialing_code' => '+505',
                'created_at' => '2022-03-11 11:36:12',
                'updated_at' => '2022-03-11 11:36:12',
                'deleted_at' => NULL,
            ),
            197 => 
            array (
                'id' => 198,
                'numeric_code' => '784',
                'alpha_code' => 'ARE',
                'name' => 'United Arab Emirates',
                'dialing_code' => '+971',
                'created_at' => '2022-03-11 11:36:12',
                'updated_at' => '2022-03-11 11:36:12',
                'deleted_at' => NULL,
            ),
            198 => 
            array (
                'id' => 199,
                'numeric_code' => '120',
                'alpha_code' => 'CMR',
                'name' => 'Cameroon',
                'dialing_code' => '+237',
                'created_at' => '2022-03-11 11:36:12',
                'updated_at' => '2022-03-11 11:36:12',
                'deleted_at' => NULL,
            ),
            199 => 
            array (
                'id' => 200,
                'numeric_code' => '850',
                'alpha_code' => 'VIR',
                'name' => 'United States Virgin Islands',
                'dialing_code' => '+1340',
                'created_at' => '2022-03-11 11:36:12',
                'updated_at' => '2022-03-11 11:36:12',
                'deleted_at' => NULL,
            ),
            200 => 
            array (
                'id' => 201,
                'numeric_code' => '364',
                'alpha_code' => 'IRN',
                'name' => 'Iran',
                'dialing_code' => '+98',
                'created_at' => '2022-03-11 11:36:12',
                'updated_at' => '2022-03-11 11:36:12',
                'deleted_at' => NULL,
            ),
            201 => 
            array (
                'id' => 202,
                'numeric_code' => '492',
                'alpha_code' => 'MCO',
                'name' => 'Monaco',
                'dialing_code' => '+377',
                'created_at' => '2022-03-11 11:36:12',
                'updated_at' => '2022-03-11 11:36:12',
                'deleted_at' => NULL,
            ),
            202 => 
            array (
                'id' => 203,
                'numeric_code' => '032',
                'alpha_code' => 'ARG',
                'name' => 'Argentina',
                'dialing_code' => '+54',
                'created_at' => '2022-03-11 11:36:12',
                'updated_at' => '2022-03-11 11:36:12',
                'deleted_at' => NULL,
            ),
            203 => 
            array (
                'id' => 204,
                'numeric_code' => '484',
                'alpha_code' => 'MEX',
                'name' => 'Mexico',
                'dialing_code' => '+52',
                'created_at' => '2022-03-11 11:36:12',
                'updated_at' => '2022-03-11 11:36:12',
                'deleted_at' => NULL,
            ),
            204 => 
            array (
                'id' => 205,
                'numeric_code' => '478',
                'alpha_code' => 'MRT',
                'name' => 'Mauritania',
                'dialing_code' => '+222',
                'created_at' => '2022-03-11 11:36:12',
                'updated_at' => '2022-03-11 11:36:12',
                'deleted_at' => NULL,
            ),
            205 => 
            array (
                'id' => 206,
                'numeric_code' => '356',
                'alpha_code' => 'IND',
                'name' => 'India',
                'dialing_code' => '+91',
                'created_at' => '2022-03-11 11:36:12',
                'updated_at' => '2022-03-11 11:36:12',
                'deleted_at' => NULL,
            ),
            206 => 
            array (
                'id' => 207,
                'numeric_code' => '031',
                'alpha_code' => 'AZE',
                'name' => 'Azerbaijan',
                'dialing_code' => '+994',
                'created_at' => '2022-03-11 11:36:12',
                'updated_at' => '2022-03-11 11:36:12',
                'deleted_at' => NULL,
            ),
            207 => 
            array (
                'id' => 208,
                'numeric_code' => '340',
                'alpha_code' => 'HND',
                'name' => 'Honduras',
                'dialing_code' => '+504',
                'created_at' => '2022-03-11 11:36:12',
                'updated_at' => '2022-03-11 11:36:12',
                'deleted_at' => NULL,
            ),
            208 => 
            array (
                'id' => 209,
                'numeric_code' => '834',
                'alpha_code' => 'TZA',
                'name' => 'Tanzania',
                'dialing_code' => '+255',
                'created_at' => '2022-03-11 11:36:12',
                'updated_at' => '2022-03-11 11:36:12',
                'deleted_at' => NULL,
            ),
            209 => 
            array (
                'id' => 210,
                'numeric_code' => '368',
                'alpha_code' => 'IRQ',
                'name' => 'Iraq',
                'dialing_code' => '+964',
                'created_at' => '2022-03-11 11:36:12',
                'updated_at' => '2022-03-11 11:36:12',
                'deleted_at' => NULL,
            ),
            210 => 
            array (
                'id' => 211,
                'numeric_code' => '048',
                'alpha_code' => 'BHR',
                'name' => 'Bahrain',
                'dialing_code' => '+973',
                'created_at' => '2022-03-11 11:36:12',
                'updated_at' => '2022-03-11 11:36:12',
                'deleted_at' => NULL,
            ),
            211 => 
            array (
                'id' => 212,
                'numeric_code' => '410',
                'alpha_code' => 'KOR',
                'name' => 'South Korea',
                'dialing_code' => '+82',
                'created_at' => '2022-03-11 11:36:12',
                'updated_at' => '2022-03-11 11:36:12',
                'deleted_at' => NULL,
            ),
            212 => 
            array (
                'id' => 213,
                'numeric_code' => '652',
                'alpha_code' => 'BLM',
                'name' => 'Saint Barthélemy',
                'dialing_code' => '+590',
                'created_at' => '2022-03-11 11:36:12',
                'updated_at' => '2022-03-11 11:36:12',
                'deleted_at' => NULL,
            ),
            213 => 
            array (
                'id' => 214,
                'numeric_code' => '136',
                'alpha_code' => 'CYM',
                'name' => 'Cayman Islands',
                'dialing_code' => '+1345',
                'created_at' => '2022-03-11 11:36:12',
                'updated_at' => '2022-03-11 11:36:12',
                'deleted_at' => NULL,
            ),
            214 => 
            array (
                'id' => 215,
                'numeric_code' => '226',
                'alpha_code' => 'GNQ',
                'name' => 'Equatorial Guinea',
                'dialing_code' => '+240',
                'created_at' => '2022-03-11 11:36:12',
                'updated_at' => '2022-03-11 11:36:12',
                'deleted_at' => NULL,
            ),
            215 => 
            array (
                'id' => 216,
                'numeric_code' => '426',
                'alpha_code' => 'LSO',
                'name' => 'Lesotho',
                'dialing_code' => '+266',
                'created_at' => '2022-03-11 11:36:12',
                'updated_at' => '2022-03-11 11:36:12',
                'deleted_at' => NULL,
            ),
            216 => 
            array (
                'id' => 217,
                'numeric_code' => '524',
                'alpha_code' => 'NPL',
                'name' => 'Nepal',
                'dialing_code' => '+977',
                'created_at' => '2022-03-11 11:36:12',
                'updated_at' => '2022-03-11 11:36:12',
                'deleted_at' => NULL,
            ),
            217 => 
            array (
                'id' => 218,
                'numeric_code' => '512',
                'alpha_code' => 'OMN',
                'name' => 'Oman',
                'dialing_code' => '+968',
                'created_at' => '2022-03-11 11:36:12',
                'updated_at' => '2022-03-11 11:36:12',
                'deleted_at' => NULL,
            ),
            218 => 
            array (
                'id' => 219,
                'numeric_code' => '276',
                'alpha_code' => 'DEU',
                'name' => 'Germany',
                'dialing_code' => '+49',
                'created_at' => '2022-03-11 11:36:12',
                'updated_at' => '2022-03-11 11:36:12',
                'deleted_at' => NULL,
            ),
            219 => 
            array (
                'id' => 220,
                'numeric_code' => '070',
                'alpha_code' => 'BIH',
                'name' => 'Bosnia and Herzegovina',
                'dialing_code' => '+387',
                'created_at' => '2022-03-11 11:36:12',
                'updated_at' => '2022-03-11 11:36:12',
                'deleted_at' => NULL,
            ),
            220 => 
            array (
                'id' => 221,
                'numeric_code' => '659',
                'alpha_code' => 'KNA',
                'name' => 'Saint Kitts and Nevis',
                'dialing_code' => '+1869',
                'created_at' => '2022-03-11 11:36:12',
                'updated_at' => '2022-03-11 11:36:12',
                'deleted_at' => NULL,
            ),
            221 => 
            array (
                'id' => 222,
                'numeric_code' => '678',
                'alpha_code' => 'STP',
                'name' => 'São Tomé and Príncipe',
                'dialing_code' => '+239',
                'created_at' => '2022-03-11 11:36:12',
                'updated_at' => '2022-03-11 11:36:12',
                'deleted_at' => NULL,
            ),
            222 => 
            array (
                'id' => 223,
                'numeric_code' => '044',
                'alpha_code' => 'BHS',
                'name' => 'Bahamas',
                'dialing_code' => '+1242',
                'created_at' => '2022-03-11 11:36:12',
                'updated_at' => '2022-03-11 11:36:12',
                'deleted_at' => NULL,
            ),
            223 => 
            array (
                'id' => 224,
                'numeric_code' => '578',
                'alpha_code' => 'NOR',
                'name' => 'Norway',
                'dialing_code' => '+47',
                'created_at' => '2022-03-11 11:36:12',
                'updated_at' => '2022-03-11 11:36:12',
                'deleted_at' => NULL,
            ),
            224 => 
            array (
                'id' => 225,
                'numeric_code' => '516',
                'alpha_code' => 'NAM',
                'name' => 'Namibia',
                'dialing_code' => '+264',
                'created_at' => '2022-03-11 11:36:12',
                'updated_at' => '2022-03-11 11:36:12',
                'deleted_at' => NULL,
            ),
            225 => 
            array (
                'id' => 226,
                'numeric_code' => '772',
                'alpha_code' => 'TKL',
                'name' => 'Tokelau',
                'dialing_code' => '+690',
                'created_at' => '2022-03-11 11:36:12',
                'updated_at' => '2022-03-11 11:36:12',
                'deleted_at' => NULL,
            ),
            226 => 
            array (
                'id' => 227,
                'numeric_code' => '548',
                'alpha_code' => 'VUT',
                'name' => 'Vanuatu',
                'dialing_code' => '+678',
                'created_at' => '2022-03-11 11:36:12',
                'updated_at' => '2022-03-11 11:36:12',
                'deleted_at' => NULL,
            ),
            227 => 
            array (
                'id' => 228,
                'numeric_code' => '660',
                'alpha_code' => 'AIA',
                'name' => 'Anguilla',
                'dialing_code' => '+1264',
                'created_at' => '2022-03-11 11:36:12',
                'updated_at' => '2022-03-11 11:36:12',
                'deleted_at' => NULL,
            ),
            228 => 
            array (
                'id' => 229,
                'numeric_code' => '768',
                'alpha_code' => 'TGO',
                'name' => 'Togo',
                'dialing_code' => '+228',
                'created_at' => '2022-03-11 11:36:12',
                'updated_at' => '2022-03-11 11:36:12',
                'deleted_at' => NULL,
            ),
            229 => 
            array (
                'id' => 230,
                'numeric_code' => '702',
                'alpha_code' => 'SGP',
                'name' => 'Singapore',
                'dialing_code' => '+65',
                'created_at' => '2022-03-11 11:36:12',
                'updated_at' => '2022-03-11 11:36:12',
                'deleted_at' => NULL,
            ),
            230 => 
            array (
                'id' => 231,
                'numeric_code' => '162',
                'alpha_code' => 'CXR',
                'name' => 'Christmas Island',
                'dialing_code' => '+61',
                'created_at' => '2022-03-11 11:36:12',
                'updated_at' => '2022-03-11 11:36:12',
                'deleted_at' => NULL,
            ),
            231 => 
            array (
                'id' => 232,
                'numeric_code' => '654',
                'alpha_code' => 'SHN',
                'name' => 'Saint Helena, Ascension and Tristan da Cunha',
                'dialing_code' => '+2',
                'created_at' => '2022-03-11 11:36:12',
                'updated_at' => '2022-03-11 11:36:12',
                'deleted_at' => NULL,
            ),
            232 => 
            array (
                'id' => 233,
                'numeric_code' => '050',
                'alpha_code' => 'BGD',
                'name' => 'Bangladesh',
                'dialing_code' => '+880',
                'created_at' => '2022-03-11 11:36:12',
                'updated_at' => '2022-03-11 11:36:12',
                'deleted_at' => NULL,
            ),
            233 => 
            array (
                'id' => 234,
                'numeric_code' => '270',
                'alpha_code' => 'GMB',
                'name' => 'Gambia',
                'dialing_code' => '+220',
                'created_at' => '2022-03-11 11:36:12',
                'updated_at' => '2022-03-11 11:36:12',
                'deleted_at' => NULL,
            ),
            234 => 
            array (
                'id' => 235,
                'numeric_code' => '705',
                'alpha_code' => 'SVN',
                'name' => 'Slovenia',
                'dialing_code' => '+386',
                'created_at' => '2022-03-11 11:36:12',
                'updated_at' => '2022-03-11 11:36:12',
                'deleted_at' => NULL,
            ),
            235 => 
            array (
                'id' => 236,
                'numeric_code' => '446',
                'alpha_code' => 'MAC',
                'name' => 'Macau',
                'dialing_code' => '+853',
                'created_at' => '2022-03-11 11:36:12',
                'updated_at' => '2022-03-11 11:36:12',
                'deleted_at' => NULL,
            ),
            236 => 
            array (
                'id' => 237,
                'numeric_code' => '384',
                'alpha_code' => 'CIV',
                'name' => 'Ivory Coast',
                'dialing_code' => '+225',
                'created_at' => '2022-03-11 11:36:12',
                'updated_at' => '2022-03-11 11:36:12',
                'deleted_at' => NULL,
            ),
            237 => 
            array (
                'id' => 238,
                'numeric_code' => '192',
                'alpha_code' => 'CUB',
                'name' => 'Cuba',
                'dialing_code' => '+53',
                'created_at' => '2022-03-11 11:36:12',
                'updated_at' => '2022-03-11 11:36:12',
                'deleted_at' => NULL,
            ),
            238 => 
            array (
                'id' => 239,
                'numeric_code' => '470',
                'alpha_code' => 'MLT',
                'name' => 'Malta',
                'dialing_code' => '+356',
                'created_at' => '2022-03-11 11:36:12',
                'updated_at' => '2022-03-11 11:36:12',
                'deleted_at' => NULL,
            ),
            239 => 
            array (
                'id' => 240,
                'numeric_code' => '246',
                'alpha_code' => 'FIN',
                'name' => 'Finland',
                'dialing_code' => '+358',
                'created_at' => '2022-03-11 11:36:12',
                'updated_at' => '2022-03-11 11:36:12',
                'deleted_at' => NULL,
            ),
            240 => 
            array (
                'id' => 241,
                'numeric_code' => '728',
                'alpha_code' => 'SSD',
                'name' => 'South Sudan',
                'dialing_code' => '+211',
                'created_at' => '2022-03-11 11:36:12',
                'updated_at' => '2022-03-11 11:36:12',
                'deleted_at' => NULL,
            ),
            241 => 
            array (
                'id' => 242,
                'numeric_code' => '454',
                'alpha_code' => 'MWI',
                'name' => 'Malawi',
                'dialing_code' => '+265',
                'created_at' => '2022-03-11 11:36:12',
                'updated_at' => '2022-03-11 11:36:12',
                'deleted_at' => NULL,
            ),
            242 => 
            array (
                'id' => 243,
                'numeric_code' => '332',
                'alpha_code' => 'HTI',
                'name' => 'Haiti',
                'dialing_code' => '+509',
                'created_at' => '2022-03-11 11:36:12',
                'updated_at' => '2022-03-11 11:36:12',
                'deleted_at' => NULL,
            ),
            243 => 
            array (
                'id' => 244,
                'numeric_code' => '826',
                'alpha_code' => 'GBR',
                'name' => 'United Kingdom',
                'dialing_code' => '+44',
                'created_at' => '2022-03-11 11:36:12',
                'updated_at' => '2022-03-11 11:36:12',
                'deleted_at' => NULL,
            ),
            244 => 
            array (
                'id' => 245,
                'numeric_code' => '682',
                'alpha_code' => 'SAU',
                'name' => 'Saudi Arabia',
                'dialing_code' => '+966',
                'created_at' => '2022-03-11 11:36:12',
                'updated_at' => '2022-03-11 11:36:12',
                'deleted_at' => NULL,
            ),
            245 => 
            array (
                'id' => 246,
                'numeric_code' => '414',
                'alpha_code' => 'KWT',
                'name' => 'Kuwait',
                'dialing_code' => '+965',
                'created_at' => '2022-03-11 11:36:12',
                'updated_at' => '2022-03-11 11:36:12',
                'deleted_at' => NULL,
            ),
            246 => 
            array (
                'id' => 247,
                'numeric_code' => '140',
                'alpha_code' => 'CAF',
                'name' => 'Central African Republic',
                'dialing_code' => '+236',
                'created_at' => '2022-03-11 11:36:12',
                'updated_at' => '2022-03-11 11:36:12',
                'deleted_at' => NULL,
            ),
            247 => 
            array (
                'id' => 248,
                'numeric_code' => '670',
                'alpha_code' => 'VCT',
                'name' => 'Saint Vincent and the Grenadines',
                'dialing_code' => '+1784',
                'created_at' => '2022-03-11 11:36:12',
                'updated_at' => '2022-03-11 11:36:12',
                'deleted_at' => NULL,
            ),
            248 => 
            array (
                'id' => 249,
                'numeric_code' => '764',
                'alpha_code' => 'THA',
                'name' => 'Thailand',
                'dialing_code' => '+66',
                'created_at' => '2022-03-11 11:36:12',
                'updated_at' => '2022-03-11 11:36:12',
                'deleted_at' => NULL,
            ),
        ));
        
        
    }
}