<?php
namespace Database\Seeders;
use Illuminate\Database\Seeder;

class DataTypesTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('data_types')->delete();
        
        \DB::table('data_types')->insert(array (
            0 => 
            array (
                'id' => 1,
                'name' => 'users',
                'slug' => 'users',
                'display_name_singular' => 'User',
                'display_name_plural' => 'Users',
                'icon' => 'voyager-person',
                'model_name' => 'TCG\\Voyager\\Models\\User',
                'policy_name' => 'TCG\\Voyager\\Policies\\UserPolicy',
                'controller' => 'TCG\\Voyager\\Http\\Controllers\\VoyagerUserController',
                'description' => NULL,
                'generate_permissions' => 1,
                'server_side' => 1,
                'details' => '{"order_column":null,"order_display_column":null,"order_direction":"desc","default_search_key":null,"scope":null}',
                'created_at' => '2020-10-13 13:08:27',
                'updated_at' => '2020-10-30 12:38:41',
            ),
            1 => 
            array (
                'id' => 2,
                'name' => 'menus',
                'slug' => 'menus',
                'display_name_singular' => 'Menu',
                'display_name_plural' => 'Menus',
                'icon' => 'voyager-list',
                'model_name' => 'TCG\\Voyager\\Models\\Menu',
                'policy_name' => NULL,
                'controller' => '',
                'description' => '',
                'generate_permissions' => 1,
                'server_side' => 0,
                'details' => NULL,
                'created_at' => '2020-10-13 13:08:27',
                'updated_at' => '2020-10-13 13:08:27',
            ),
            2 => 
            array (
                'id' => 3,
                'name' => 'roles',
                'slug' => 'roles',
                'display_name_singular' => 'Role',
                'display_name_plural' => 'Roles',
                'icon' => 'voyager-lock',
                'model_name' => 'TCG\\Voyager\\Models\\Role',
                'policy_name' => NULL,
                'controller' => 'TCG\\Voyager\\Http\\Controllers\\VoyagerRoleController',
                'description' => '',
                'generate_permissions' => 1,
                'server_side' => 0,
                'details' => NULL,
                'created_at' => '2020-10-13 13:08:27',
                'updated_at' => '2020-10-13 13:08:27',
            ),
            3 => 
            array (
                'id' => 9,
                'name' => 'accommodation_inventory',
                'slug' => 'accommodation-inventory',
                'display_name_singular' => 'Accommodation Inventory',
                'display_name_plural' => 'Accommodation Inventories',
                'icon' => NULL,
                'model_name' => 'App\\Models\\AccommodationInventory',
                'policy_name' => NULL,
                'controller' => NULL,
                'description' => NULL,
                'generate_permissions' => 1,
                'server_side' => 0,
                'details' => '{"order_column":null,"order_display_column":null,"order_direction":"asc","default_search_key":null}',
                'created_at' => '2020-10-15 09:18:14',
                'updated_at' => '2020-10-15 09:18:14',
            ),
            4 => 
            array (
                'id' => 11,
                'name' => 'accommodation_inventories',
                'slug' => 'accommodation-inventories',
                'display_name_singular' => 'Accommodation Inventory',
                'display_name_plural' => 'Accommodation Inventories',
                'icon' => NULL,
                'model_name' => 'App\\Models\\AccommodationInventory',
                'policy_name' => NULL,
                'controller' => NULL,
                'description' => NULL,
                'generate_permissions' => 1,
                'server_side' => 1,
                'details' => '{"order_column":null,"order_display_column":null,"order_direction":"asc","default_search_key":null,"scope":null}',
                'created_at' => '2020-10-15 09:20:59',
                'updated_at' => '2020-11-20 12:36:30',
            ),
            5 => 
            array (
                'id' => 13,
                'name' => 'board_types',
                'slug' => 'board-types',
                'display_name_singular' => 'Board Type',
                'display_name_plural' => 'Board Types',
                'icon' => NULL,
                'model_name' => 'App\\Models\\BoardType',
                'policy_name' => NULL,
                'controller' => '',
                'description' => NULL,
                'generate_permissions' => 1,
                'server_side' => 1,
                'details' => '{"order_column":null,"order_display_column":null,"order_direction":"asc","default_search_key":null,"scope":null}',
                'created_at' => '2020-10-15 10:03:54',
                'updated_at' => '2020-10-30 12:48:15',
            ),
            6 => 
            array (
                'id' => 14,
                'name' => 'room_types',
                'slug' => 'room-types',
                'display_name_singular' => 'Room Type',
                'display_name_plural' => 'Room Types',
                'icon' => NULL,
                'model_name' => 'App\\Models\\RoomType',
                'policy_name' => NULL,
                'controller' => '',
                'description' => NULL,
                'generate_permissions' => 1,
                'server_side' => 1,
                'details' => '{"order_column":null,"order_display_column":null,"order_direction":"asc","default_search_key":null,"scope":null}',
                'created_at' => '2020-10-15 11:16:35',
                'updated_at' => '2020-10-30 12:37:51',
            ),
            7 => 
            array (
                'id' => 20,
                'name' => 'regions',
                'slug' => 'regions',
                'display_name_singular' => 'Region',
                'display_name_plural' => 'Regions',
                'icon' => NULL,
                'model_name' => 'App\\Models\\Region',
                'policy_name' => NULL,
                'controller' => '',
                'description' => NULL,
                'generate_permissions' => 1,
                'server_side' => 1,
                'details' => '{"order_column":null,"order_display_column":null,"order_direction":"asc","default_search_key":null,"scope":null}',
                'created_at' => '2020-10-22 12:22:09',
                'updated_at' => '2020-10-30 12:37:39',
            ),
            8 => 
            array (
                'id' => 21,
                'name' => 'countries',
                'slug' => 'countries',
                'display_name_singular' => 'Country',
                'display_name_plural' => 'Countries',
                'icon' => NULL,
                'model_name' => 'App\\Models\\Country',
                'policy_name' => NULL,
                'controller' => '',
                'description' => NULL,
                'generate_permissions' => 1,
                'server_side' => 1,
                'details' => '{"order_column":null,"order_display_column":null,"order_direction":"asc","default_search_key":null,"scope":null}',
                'created_at' => '2020-10-22 12:25:43',
                'updated_at' => '2020-10-30 12:48:38',
            ),
            9 => 
            array (
                'id' => 26,
                'name' => 'location_types',
                'slug' => 'location-types',
                'display_name_singular' => 'Location Type',
                'display_name_plural' => 'Location Types',
                'icon' => NULL,
                'model_name' => 'App\\Models\\LocationType',
                'policy_name' => NULL,
                'controller' => '',
                'description' => NULL,
                'generate_permissions' => 1,
                'server_side' => 1,
                'details' => '{"order_column":null,"order_display_column":null,"order_direction":"asc","default_search_key":null,"scope":null}',
                'created_at' => '2020-10-22 12:52:30',
                'updated_at' => '2020-10-30 12:40:04',
            ),
            10 => 
            array (
                'id' => 27,
                'name' => 'locations',
                'slug' => 'locations',
                'display_name_singular' => 'Location',
                'display_name_plural' => 'Locations',
                'icon' => NULL,
                'model_name' => 'App\\Models\\Location',
                'policy_name' => NULL,
                'controller' => '',
                'description' => NULL,
                'generate_permissions' => 1,
                'server_side' => 1,
                'details' => '{"order_column":null,"order_display_column":null,"order_direction":"asc","default_search_key":null,"scope":null}',
                'created_at' => '2020-10-22 13:00:12',
                'updated_at' => '2020-10-30 12:39:46',
            ),
            11 => 
            array (
                'id' => 30,
                'name' => 'accommodations',
                'slug' => 'accommodations',
                'display_name_singular' => 'Accommodation',
                'display_name_plural' => 'Accommodations',
                'icon' => NULL,
                'model_name' => 'App\\Models\\Accommodation',
                'policy_name' => NULL,
                'controller' => NULL,
                'description' => NULL,
                'generate_permissions' => 1,
                'server_side' => 1,
                'details' => '{"order_column":null,"order_display_column":null,"order_direction":"asc","default_search_key":null,"scope":null}',
                'created_at' => '2020-10-22 14:27:11',
                'updated_at' => '2020-11-17 09:36:47',
            ),
            12 => 
            array (
                'id' => 43,
                'name' => 'airlines',
                'slug' => 'airlines',
                'display_name_singular' => 'Airline',
                'display_name_plural' => 'Airlines',
                'icon' => NULL,
                'model_name' => 'App\\Models\\Airline',
                'policy_name' => NULL,
                'controller' => NULL,
                'description' => NULL,
                'generate_permissions' => 1,
                'server_side' => 1,
                'details' => '{"order_column":null,"order_display_column":null,"order_direction":"asc","default_search_key":null}',
                'created_at' => '2020-11-03 10:45:18',
                'updated_at' => '2020-11-03 10:45:18',
            ),
            13 => 
            array (
                'id' => 44,
                'name' => 'airports',
                'slug' => 'airports',
                'display_name_singular' => 'Airport',
                'display_name_plural' => 'Airports',
                'icon' => NULL,
                'model_name' => 'App\\Models\\Airport',
                'policy_name' => NULL,
                'controller' => NULL,
                'description' => NULL,
                'generate_permissions' => 1,
                'server_side' => 1,
                'details' => '{"order_column":null,"order_display_column":null,"order_direction":"asc","default_search_key":null,"scope":null}',
                'created_at' => '2020-11-03 10:47:14',
                'updated_at' => '2020-11-03 18:53:03',
            ),
            14 => 
            array (
                'id' => 45,
                'name' => 'flights',
                'slug' => 'flights',
                'display_name_singular' => 'Flight',
                'display_name_plural' => 'Flights',
                'icon' => NULL,
                'model_name' => 'App\\Models\\Flight',
                'policy_name' => NULL,
                'controller' => NULL,
                'description' => NULL,
                'generate_permissions' => 1,
                'server_side' => 1,
                'details' => '{"order_column":null,"order_display_column":null,"order_direction":"asc","default_search_key":null,"scope":null}',
                'created_at' => '2020-11-03 10:47:42',
                'updated_at' => '2020-11-13 16:28:44',
            ),
            15 => 
            array (
                'id' => 46,
                'name' => 'travel_classes',
                'slug' => 'travel-classes',
                'display_name_singular' => 'Travel Class',
                'display_name_plural' => 'Travel Classes',
                'icon' => NULL,
                'model_name' => 'App\\Models\\TravelClass',
                'policy_name' => NULL,
                'controller' => NULL,
                'description' => NULL,
                'generate_permissions' => 1,
                'server_side' => 0,
                'details' => '{"order_column":null,"order_display_column":null,"order_direction":"asc","default_search_key":null}',
                'created_at' => '2020-11-03 16:06:58',
                'updated_at' => '2020-11-03 16:06:58',
            ),
            16 => 
            array (
                'id' => 49,
                'name' => 'flight_inventories',
                'slug' => 'flight-inventories',
                'display_name_singular' => 'Flight Inventory',
                'display_name_plural' => 'Flight Inventories',
                'icon' => NULL,
                'model_name' => 'App\\Models\\FlightInventory',
                'policy_name' => NULL,
                'controller' => NULL,
                'description' => NULL,
                'generate_permissions' => 1,
                'server_side' => 1,
                'details' => '{"order_column":null,"order_display_column":null,"order_direction":"asc","default_search_key":null,"scope":null}',
                'created_at' => '2020-11-03 18:21:33',
                'updated_at' => '2020-11-20 12:37:12',
            ),
            17 => 
            array (
                'id' => 52,
                'name' => 'activity_types',
                'slug' => 'activity-types',
                'display_name_singular' => 'Activity Type',
                'display_name_plural' => 'Activity Types',
                'icon' => NULL,
                'model_name' => 'App\\Models\\ActivityType',
                'policy_name' => NULL,
                'controller' => NULL,
                'description' => NULL,
                'generate_permissions' => 1,
                'server_side' => 1,
                'details' => '{"order_column":null,"order_display_column":null,"order_direction":"asc","default_search_key":null,"scope":null}',
                'created_at' => '2020-11-04 14:48:19',
                'updated_at' => '2020-11-04 18:30:57',
            ),
            18 => 
            array (
                'id' => 54,
                'name' => 'ticket_types',
                'slug' => 'ticket-types',
                'display_name_singular' => 'Ticket Type',
                'display_name_plural' => 'Ticket Types',
                'icon' => NULL,
                'model_name' => 'App\\Models\\TicketType',
                'policy_name' => NULL,
                'controller' => NULL,
                'description' => NULL,
                'generate_permissions' => 1,
                'server_side' => 1,
                'details' => '{"order_column":null,"order_display_column":null,"order_direction":"asc","default_search_key":null}',
                'created_at' => '2020-11-04 16:01:42',
                'updated_at' => '2020-11-04 16:01:42',
            ),
            19 => 
            array (
                'id' => 55,
                'name' => 'activities',
                'slug' => 'activities',
                'display_name_singular' => 'Activity',
                'display_name_plural' => 'Activities',
                'icon' => NULL,
                'model_name' => 'App\\Models\\Activity',
                'policy_name' => NULL,
                'controller' => NULL,
                'description' => NULL,
                'generate_permissions' => 1,
                'server_side' => 1,
                'details' => '{"order_column":null,"order_display_column":null,"order_direction":"asc","default_search_key":null,"scope":null}',
                'created_at' => '2020-11-04 16:02:46',
                'updated_at' => '2020-11-05 08:57:43',
            ),
            20 => 
            array (
                'id' => 56,
                'name' => 'activity_inventories',
                'slug' => 'activity-inventories',
                'display_name_singular' => 'Activity Inventory',
                'display_name_plural' => 'Activity Inventories',
                'icon' => NULL,
                'model_name' => 'App\\Models\\ActivityInventory',
                'policy_name' => NULL,
                'controller' => NULL,
                'description' => NULL,
                'generate_permissions' => 1,
                'server_side' => 1,
                'details' => '{"order_column":null,"order_display_column":null,"order_direction":"asc","default_search_key":null,"scope":null}',
                'created_at' => '2020-11-04 18:08:44',
                'updated_at' => '2020-11-05 09:01:08',
            ),
            21 => 
            array (
                'id' => 57,
                'name' => 'transports',
                'slug' => 'transports',
                'display_name_singular' => 'Transport',
                'display_name_plural' => 'Transports',
                'icon' => NULL,
                'model_name' => 'App\\Models\\Transport',
                'policy_name' => NULL,
                'controller' => NULL,
                'description' => NULL,
                'generate_permissions' => 1,
                'server_side' => 1,
                'details' => '{"order_column":null,"order_display_column":null,"order_direction":"asc","default_search_key":null,"scope":null}',
                'created_at' => '2020-11-05 12:08:07',
                'updated_at' => '2020-11-19 13:17:12',
            ),
            22 => 
            array (
                'id' => 63,
                'name' => 'transport_types',
                'slug' => 'transport-types',
                'display_name_singular' => 'Transport Type',
                'display_name_plural' => 'Transport Types',
                'icon' => NULL,
                'model_name' => 'App\\Models\\TransportType',
                'policy_name' => NULL,
                'controller' => NULL,
                'description' => NULL,
                'generate_permissions' => 1,
                'server_side' => 1,
                'details' => '{"order_column":null,"order_display_column":null,"order_direction":"asc","default_search_key":null}',
                'created_at' => '2020-11-05 12:11:44',
                'updated_at' => '2020-11-05 12:11:44',
            ),
            23 => 
            array (
                'id' => 64,
                'name' => 'operators',
                'slug' => 'operators',
                'display_name_singular' => 'Operator',
                'display_name_plural' => 'Operators',
                'icon' => NULL,
                'model_name' => 'App\\Models\\Operator',
                'policy_name' => NULL,
                'controller' => NULL,
                'description' => NULL,
                'generate_permissions' => 1,
                'server_side' => 1,
                'details' => '{"order_column":null,"order_display_column":null,"order_direction":"asc","default_search_key":null}',
                'created_at' => '2020-11-05 12:36:33',
                'updated_at' => '2020-11-05 12:36:33',
            ),
            24 => 
            array (
                'id' => 65,
                'name' => 'transport_inventories',
                'slug' => 'transport-inventories',
                'display_name_singular' => 'Transport Inventory',
                'display_name_plural' => 'Transport Inventories',
                'icon' => NULL,
                'model_name' => 'App\\Models\\TransportInventory',
                'policy_name' => NULL,
                'controller' => NULL,
                'description' => NULL,
                'generate_permissions' => 1,
                'server_side' => 1,
                'details' => '{"order_column":null,"order_display_column":null,"order_direction":"asc","default_search_key":null,"scope":null}',
                'created_at' => '2020-11-05 12:38:06',
                'updated_at' => '2020-11-19 14:45:41',
            ),
            25 => 
            array (
                'id' => 67,
                'name' => 'tours',
                'slug' => 'tours',
                'display_name_singular' => 'Tour',
                'display_name_plural' => 'Tours',
                'icon' => NULL,
                'model_name' => 'App\\Models\\Tour',
                'policy_name' => NULL,
                'controller' => NULL,
                'description' => NULL,
                'generate_permissions' => 1,
                'server_side' => 1,
                'details' => '{"order_column":null,"order_display_column":null,"order_direction":"asc","default_search_key":null,"scope":null}',
                'created_at' => '2020-11-16 08:43:02',
                'updated_at' => '2020-11-23 14:12:40',
            ),
            26 => 
            array (
                'id' => 68,
                'name' => 'events',
                'slug' => 'events',
                'display_name_singular' => 'Event',
                'display_name_plural' => 'Events',
                'icon' => NULL,
                'model_name' => 'App\\Models\\Event',
                'policy_name' => NULL,
                'controller' => NULL,
                'description' => NULL,
                'generate_permissions' => 1,
                'server_side' => 1,
                'details' => '{"order_column":null,"order_display_column":null,"order_direction":"asc","default_search_key":null,"scope":null}',
                'created_at' => '2020-11-20 17:12:37',
                'updated_at' => '2020-11-20 17:16:14',
            ),
            27 => 
            array (
                'id' => 73,
                'name' => 'payment_schedules',
                'slug' => 'payment-schedules',
                'display_name_singular' => 'Payment Schedule',
                'display_name_plural' => 'Payment Schedules',
                'icon' => NULL,
                'model_name' => 'App\\Models\\PaymentSchedule',
                'policy_name' => NULL,
                'controller' => NULL,
                'description' => NULL,
                'generate_permissions' => 1,
                'server_side' => 1,
                'details' => '{"order_column":null,"order_display_column":null,"order_direction":"asc","default_search_key":null,"scope":null}',
                'created_at' => '2020-11-23 14:02:22',
                'updated_at' => '2020-11-23 14:09:43',
            ),
            28 => 
            array (
                'id' => 75,
                'name' => 'payment_installments',
                'slug' => 'payment-installments',
                'display_name_singular' => 'Payment Installment',
                'display_name_plural' => 'Payment Installments',
                'icon' => NULL,
                'model_name' => 'App\\Models\\PaymentInstallment',
                'policy_name' => NULL,
                'controller' => NULL,
                'description' => NULL,
                'generate_permissions' => 1,
                'server_side' => 1,
                'details' => '{"order_column":null,"order_display_column":null,"order_direction":"asc","default_search_key":null,"scope":null}',
                'created_at' => '2020-11-23 14:03:41',
                'updated_at' => '2020-11-23 14:07:37',
            ),
            29 => 
            array (
                'id' => 76,
                'name' => 'orders',
                'slug' => 'orders',
                'display_name_singular' => 'Order',
                'display_name_plural' => 'Orders',
                'icon' => NULL,
                'model_name' => 'App\\Models\\Order',
                'policy_name' => NULL,
                'controller' => NULL,
                'description' => NULL,
                'generate_permissions' => 1,
                'server_side' => 0,
                'details' => '{"order_column":null,"order_display_column":null,"order_direction":"asc","default_search_key":null,"scope":null}',
                'created_at' => '2020-11-25 15:38:18',
                'updated_at' => '2020-11-26 08:49:36',
            ),
            30 => 
            array (
                'id' => 78,
                'name' => 'orders_customers',
                'slug' => 'orders-customers',
                'display_name_singular' => 'Orders Customer',
                'display_name_plural' => 'Orders Customers',
                'icon' => NULL,
                'model_name' => 'App\\Models\\OrdersCustomer',
                'policy_name' => NULL,
                'controller' => NULL,
                'description' => NULL,
                'generate_permissions' => 1,
                'server_side' => 1,
                'details' => '{"order_column":null,"order_display_column":null,"order_direction":"asc","default_search_key":null,"scope":null}',
                'created_at' => '2020-11-25 16:08:05',
                'updated_at' => '2020-11-25 16:16:16',
            ),
            31 => 
            array (
                'id' => 80,
                'name' => 'order_statuses',
                'slug' => 'order-statuses',
                'display_name_singular' => 'Order Status',
                'display_name_plural' => 'Order Statuses',
                'icon' => NULL,
                'model_name' => 'App\\Models\\OrderStatus',
                'policy_name' => NULL,
                'controller' => NULL,
                'description' => NULL,
                'generate_permissions' => 1,
                'server_side' => 1,
                'details' => '{"order_column":null,"order_display_column":null,"order_direction":"asc","default_search_key":null}',
                'created_at' => '2020-11-26 08:51:04',
                'updated_at' => '2020-11-26 08:51:04',
            ),
            32 => 
            array (
                'id' => 82,
                'name' => 'customers',
                'slug' => 'customers',
                'display_name_singular' => 'Customer',
                'display_name_plural' => 'Customers',
                'icon' => NULL,
                'model_name' => 'App\\Models\\Customer',
                'policy_name' => NULL,
                'controller' => NULL,
                'description' => NULL,
                'generate_permissions' => 1,
                'server_side' => 0,
                'details' => '{"order_column":null,"order_display_column":null,"order_direction":"asc","default_search_key":null,"scope":null}',
                'created_at' => '2020-11-26 09:18:56',
                'updated_at' => '2020-11-27 08:56:16',
            ),
            33 => 
            array (
                'id' => 84,
                'name' => 'invoices',
                'slug' => 'invoices',
                'display_name_singular' => 'Invoice',
                'display_name_plural' => 'Invoices',
                'icon' => NULL,
                'model_name' => 'App\\Models\\Invoice',
                'policy_name' => NULL,
                'controller' => NULL,
                'description' => NULL,
                'generate_permissions' => 1,
                'server_side' => 1,
                'details' => '{"order_column":null,"order_display_column":null,"order_direction":"asc","default_search_key":null}',
                'created_at' => '2020-11-27 09:18:30',
                'updated_at' => '2020-11-27 09:18:30',
            ),
        ));
        
        
    }
}