<?php

use Illuminate\Database\Seeder;

class MenuItemsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('menu_items')->delete();
        
        \DB::table('menu_items')->insert(array (
            0 => 
            array (
                'id' => 1,
                'menu_id' => 1,
                'title' => 'Dashboard',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-boat',
                'color' => NULL,
                'parent_id' => NULL,
                'order' => 1,
                'created_at' => '2020-10-13 13:08:28',
                'updated_at' => '2020-10-13 13:08:28',
                'route' => 'voyager.dashboard',
                'parameters' => NULL,
            ),
            1 => 
            array (
                'id' => 2,
                'menu_id' => 1,
                'title' => 'Media',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-images',
                'color' => NULL,
                'parent_id' => NULL,
                'order' => 4,
                'created_at' => '2020-10-13 13:08:28',
                'updated_at' => '2020-10-22 13:59:56',
                'route' => 'voyager.media.index',
                'parameters' => NULL,
            ),
            2 => 
            array (
                'id' => 3,
                'menu_id' => 1,
                'title' => 'Users',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-person',
                'color' => NULL,
                'parent_id' => NULL,
                'order' => 3,
                'created_at' => '2020-10-13 13:08:28',
                'updated_at' => '2020-10-13 13:08:28',
                'route' => 'voyager.users.index',
                'parameters' => NULL,
            ),
            3 => 
            array (
                'id' => 4,
                'menu_id' => 1,
                'title' => 'Roles',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-lock',
                'color' => NULL,
                'parent_id' => NULL,
                'order' => 2,
                'created_at' => '2020-10-13 13:08:28',
                'updated_at' => '2020-10-13 13:08:28',
                'route' => 'voyager.roles.index',
                'parameters' => NULL,
            ),
            4 => 
            array (
                'id' => 5,
                'menu_id' => 1,
                'title' => 'Tools',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-tools',
                'color' => NULL,
                'parent_id' => NULL,
                'order' => 5,
                'created_at' => '2020-10-13 13:08:28',
                'updated_at' => '2020-10-22 13:59:56',
                'route' => NULL,
                'parameters' => NULL,
            ),
            5 => 
            array (
                'id' => 6,
                'menu_id' => 1,
                'title' => 'Menu Builder',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-list',
                'color' => NULL,
                'parent_id' => 5,
                'order' => 1,
                'created_at' => '2020-10-13 13:08:28',
                'updated_at' => '2020-10-22 13:59:56',
                'route' => 'voyager.menus.index',
                'parameters' => NULL,
            ),
            6 => 
            array (
                'id' => 7,
                'menu_id' => 1,
                'title' => 'Database',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-data',
                'color' => NULL,
                'parent_id' => 5,
                'order' => 2,
                'created_at' => '2020-10-13 13:08:28',
                'updated_at' => '2020-10-22 13:59:56',
                'route' => 'voyager.database.index',
                'parameters' => NULL,
            ),
            7 => 
            array (
                'id' => 8,
                'menu_id' => 1,
                'title' => 'Compass',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-compass',
                'color' => NULL,
                'parent_id' => 5,
                'order' => 3,
                'created_at' => '2020-10-13 13:08:28',
                'updated_at' => '2020-10-22 13:59:56',
                'route' => 'voyager.compass.index',
                'parameters' => NULL,
            ),
            8 => 
            array (
                'id' => 9,
                'menu_id' => 1,
                'title' => 'BREAD',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-bread',
                'color' => NULL,
                'parent_id' => 5,
                'order' => 4,
                'created_at' => '2020-10-13 13:08:28',
                'updated_at' => '2020-10-22 13:59:56',
                'route' => 'voyager.bread.index',
                'parameters' => NULL,
            ),
            9 => 
            array (
                'id' => 10,
                'menu_id' => 1,
                'title' => 'Settings',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-settings',
                'color' => NULL,
                'parent_id' => NULL,
                'order' => 6,
                'created_at' => '2020-10-13 13:08:28',
                'updated_at' => '2020-10-22 13:59:56',
                'route' => 'voyager.settings.index',
                'parameters' => NULL,
            ),
            10 => 
            array (
                'id' => 11,
                'menu_id' => 1,
                'title' => 'Hooks',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-hook',
                'color' => NULL,
                'parent_id' => 5,
                'order' => 5,
                'created_at' => '2020-10-13 13:08:28',
                'updated_at' => '2020-10-22 13:59:56',
                'route' => 'voyager.hooks',
                'parameters' => NULL,
            ),
            11 => 
            array (
                'id' => 14,
                'menu_id' => 1,
                'title' => 'Accommodation Inventories',
                'url' => '',
                'target' => '_self',
                'icon_class' => NULL,
                'color' => NULL,
                'parent_id' => 25,
                'order' => 2,
                'created_at' => '2020-10-15 09:21:00',
                'updated_at' => '2020-10-22 14:00:48',
                'route' => 'voyager.accommodation-inventories.index',
                'parameters' => NULL,
            ),
            12 => 
            array (
                'id' => 15,
                'menu_id' => 1,
                'title' => 'Board Types',
                'url' => '',
                'target' => '_self',
                'icon_class' => NULL,
                'color' => NULL,
                'parent_id' => 25,
                'order' => 3,
                'created_at' => '2020-10-15 10:03:54',
                'updated_at' => '2020-10-22 14:00:56',
                'route' => 'voyager.board-types.index',
                'parameters' => NULL,
            ),
            13 => 
            array (
                'id' => 16,
                'menu_id' => 1,
                'title' => 'Room Types',
                'url' => '',
                'target' => '_self',
                'icon_class' => NULL,
                'color' => NULL,
                'parent_id' => 25,
                'order' => 4,
                'created_at' => '2020-10-15 11:16:35',
                'updated_at' => '2020-10-22 14:00:59',
                'route' => 'voyager.room-types.index',
                'parameters' => NULL,
            ),
            14 => 
            array (
                'id' => 17,
                'menu_id' => 1,
                'title' => 'Model Logs',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-logbook',
                'color' => NULL,
                'parent_id' => NULL,
                'order' => 9,
                'created_at' => '2020-10-15 14:41:14',
                'updated_at' => '2020-10-22 14:00:59',
                'route' => 'voyager.model_log.index',
                'parameters' => NULL,
            ),
            15 => 
            array (
                'id' => 19,
                'menu_id' => 1,
                'title' => 'Regions',
                'url' => '',
                'target' => '_self',
                'icon_class' => NULL,
                'color' => NULL,
                'parent_id' => 24,
                'order' => 4,
                'created_at' => '2020-10-22 12:22:09',
                'updated_at' => '2020-10-22 14:00:13',
                'route' => 'voyager.regions.index',
                'parameters' => NULL,
            ),
            16 => 
            array (
                'id' => 20,
                'menu_id' => 1,
                'title' => 'Countries',
                'url' => '',
                'target' => '_self',
                'icon_class' => NULL,
                'color' => NULL,
                'parent_id' => 24,
                'order' => 3,
                'created_at' => '2020-10-22 12:25:43',
                'updated_at' => '2020-10-22 14:00:13',
                'route' => 'voyager.countries.index',
                'parameters' => NULL,
            ),
            17 => 
            array (
                'id' => 21,
                'menu_id' => 1,
                'title' => 'Location Types',
                'url' => '',
                'target' => '_self',
                'icon_class' => NULL,
                'color' => NULL,
                'parent_id' => 24,
                'order' => 2,
                'created_at' => '2020-10-22 12:52:30',
                'updated_at' => '2020-10-22 14:00:13',
                'route' => 'voyager.location-types.index',
                'parameters' => NULL,
            ),
            18 => 
            array (
                'id' => 22,
                'menu_id' => 1,
                'title' => 'Locations',
                'url' => '',
                'target' => '_self',
                'icon_class' => NULL,
                'color' => NULL,
                'parent_id' => 24,
                'order' => 1,
                'created_at' => '2020-10-22 13:00:12',
                'updated_at' => '2020-10-22 14:00:02',
                'route' => 'voyager.locations.index',
                'parameters' => NULL,
            ),
            19 => 
            array (
                'id' => 24,
                'menu_id' => 1,
                'title' => 'Locations',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-world',
                'color' => '#000000',
                'parent_id' => NULL,
                'order' => 7,
                'created_at' => '2020-10-22 13:59:43',
                'updated_at' => '2020-10-22 14:02:01',
                'route' => NULL,
                'parameters' => '',
            ),
            20 => 
            array (
                'id' => 25,
                'menu_id' => 1,
                'title' => 'Accommodations',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-company',
                'color' => '#000000',
                'parent_id' => NULL,
                'order' => 8,
                'created_at' => '2020-10-22 14:00:33',
                'updated_at' => '2020-10-22 14:02:28',
                'route' => NULL,
                'parameters' => '',
            ),
            21 => 
            array (
                'id' => 26,
                'menu_id' => 1,
                'title' => 'Accommodations',
                'url' => '',
                'target' => '_self',
                'icon_class' => NULL,
                'color' => NULL,
                'parent_id' => 25,
                'order' => 1,
                'created_at' => '2020-10-22 14:27:11',
                'updated_at' => '2020-10-22 14:29:55',
                'route' => 'voyager.accommodations.index',
                'parameters' => NULL,
            ),
        ));
        
        
    }
}