<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class OrderCustomersTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('order_customers')->delete();
        
        \DB::table('order_customers')->insert(array (
            0 => 
            array (
                'id' => 1,
                'order_id' => 1,
                'customer_id' => 1,
                'tour_cost' => '3498.00',
                'single_occupancy_surcharge' => '419.67',
                'travel_insurer' => NULL,
                'policy_number' => NULL,
                'created_at' => '2022-01-23 13:02:34',
                'updated_at' => '2022-01-23 13:02:34',
                'deleted_at' => NULL,
                'internal_notes' => NULL,
                'external_notes' => NULL,
                'accommodation_notes' => NULL,
                'activity_notes' => NULL,
                'flight_notes' => NULL,
                'transport_notes' => NULL,
                'is_travelling' => 1,
                'is_charged' => 1,
            ),
            1 => 
            array (
                'id' => 2,
                'order_id' => 2,
                'customer_id' => 4,
                'tour_cost' => '3498.00',
                'single_occupancy_surcharge' => '419.67',
                'travel_insurer' => NULL,
                'policy_number' => NULL,
                'created_at' => '2022-01-23 13:21:17',
                'updated_at' => '2022-01-23 13:21:17',
                'deleted_at' => NULL,
                'internal_notes' => NULL,
                'external_notes' => NULL,
                'accommodation_notes' => NULL,
                'activity_notes' => NULL,
                'flight_notes' => NULL,
                'transport_notes' => NULL,
                'is_travelling' => 1,
                'is_charged' => 1,
            ),
            2 => 
            array (
                'id' => 3,
                'order_id' => 3,
                'customer_id' => 3,
                'tour_cost' => '3498.00',
                'single_occupancy_surcharge' => '419.67',
                'travel_insurer' => NULL,
                'policy_number' => NULL,
                'created_at' => '2022-01-23 13:25:11',
                'updated_at' => '2022-01-23 13:25:11',
                'deleted_at' => NULL,
                'internal_notes' => NULL,
                'external_notes' => NULL,
                'accommodation_notes' => NULL,
                'activity_notes' => NULL,
                'flight_notes' => NULL,
                'transport_notes' => NULL,
                'is_travelling' => 1,
                'is_charged' => 1,
            ),
            3 => 
            array (
                'id' => 4,
                'order_id' => 3,
                'customer_id' => 18,
                'tour_cost' => '3498.00',
                'single_occupancy_surcharge' => '1250.00',
                'travel_insurer' => 'ASCI',
                'policy_number' => 'ABDF',
                'created_at' => '2022-01-23 13:38:49',
                'updated_at' => '2022-01-23 13:38:49',
                'deleted_at' => NULL,
                'internal_notes' => NULL,
                'external_notes' => NULL,
                'accommodation_notes' => NULL,
                'activity_notes' => NULL,
                'flight_notes' => NULL,
                'transport_notes' => NULL,
                'is_travelling' => 1,
                'is_charged' => 1,
            ),
            4 => 
            array (
                'id' => 5,
                'order_id' => 4,
                'customer_id' => 5,
                'tour_cost' => '3498.00',
                'single_occupancy_surcharge' => '419.67',
                'travel_insurer' => NULL,
                'policy_number' => NULL,
                'created_at' => '2022-01-23 13:47:50',
                'updated_at' => '2022-01-23 13:47:50',
                'deleted_at' => NULL,
                'internal_notes' => NULL,
                'external_notes' => NULL,
                'accommodation_notes' => NULL,
                'activity_notes' => NULL,
                'flight_notes' => NULL,
                'transport_notes' => NULL,
                'is_travelling' => 1,
                'is_charged' => 1,
            ),
            5 => 
            array (
                'id' => 6,
                'order_id' => 5,
                'customer_id' => 15,
                'tour_cost' => '3498.00',
                'single_occupancy_surcharge' => '419.67',
                'travel_insurer' => NULL,
                'policy_number' => NULL,
                'created_at' => '2022-06-29 07:59:19',
                'updated_at' => '2022-06-29 07:59:19',
                'deleted_at' => NULL,
                'internal_notes' => NULL,
                'external_notes' => NULL,
                'accommodation_notes' => NULL,
                'activity_notes' => NULL,
                'flight_notes' => NULL,
                'transport_notes' => NULL,
                'is_travelling' => 1,
                'is_charged' => 1,
            ),
            6 => 
            array (
                'id' => 7,
                'order_id' => 5,
                'customer_id' => 5,
                'tour_cost' => '3498.00',
                'single_occupancy_surcharge' => '419.67',
                'travel_insurer' => NULL,
                'policy_number' => NULL,
                'created_at' => '2022-06-29 07:59:22',
                'updated_at' => '2022-06-29 07:59:22',
                'deleted_at' => NULL,
                'internal_notes' => NULL,
                'external_notes' => NULL,
                'accommodation_notes' => NULL,
                'activity_notes' => NULL,
                'flight_notes' => NULL,
                'transport_notes' => NULL,
                'is_travelling' => 1,
                'is_charged' => 1,
            ),
            7 => 
            array (
                'id' => 8,
                'order_id' => 5,
                'customer_id' => 22,
                'tour_cost' => '3498.00',
                'single_occupancy_surcharge' => '419.67',
                'travel_insurer' => NULL,
                'policy_number' => NULL,
                'created_at' => '2022-06-29 07:59:23',
                'updated_at' => '2022-06-29 07:59:23',
                'deleted_at' => NULL,
                'internal_notes' => NULL,
                'external_notes' => NULL,
                'accommodation_notes' => NULL,
                'activity_notes' => NULL,
                'flight_notes' => NULL,
                'transport_notes' => NULL,
                'is_travelling' => 1,
                'is_charged' => 1,
            ),
            8 => 
            array (
                'id' => 9,
                'order_id' => 6,
                'customer_id' => 13,
                'tour_cost' => '3498.00',
                'single_occupancy_surcharge' => '419.67',
                'travel_insurer' => NULL,
                'policy_number' => NULL,
                'created_at' => '2022-06-29 08:21:03',
                'updated_at' => '2022-06-29 08:21:03',
                'deleted_at' => NULL,
                'internal_notes' => NULL,
                'external_notes' => NULL,
                'accommodation_notes' => NULL,
                'activity_notes' => NULL,
                'flight_notes' => NULL,
                'transport_notes' => NULL,
                'is_travelling' => 1,
                'is_charged' => 1,
            ),
            9 => 
            array (
                'id' => 10,
                'order_id' => 6,
                'customer_id' => 16,
                'tour_cost' => '3498.00',
                'single_occupancy_surcharge' => '419.67',
                'travel_insurer' => NULL,
                'policy_number' => NULL,
                'created_at' => '2022-06-29 08:21:04',
                'updated_at' => '2022-06-29 08:21:04',
                'deleted_at' => NULL,
                'internal_notes' => NULL,
                'external_notes' => NULL,
                'accommodation_notes' => NULL,
                'activity_notes' => NULL,
                'flight_notes' => NULL,
                'transport_notes' => NULL,
                'is_travelling' => 1,
                'is_charged' => 1,
            ),
            10 => 
            array (
                'id' => 11,
                'order_id' => 6,
                'customer_id' => 3,
                'tour_cost' => '3498.00',
                'single_occupancy_surcharge' => '419.67',
                'travel_insurer' => NULL,
                'policy_number' => NULL,
                'created_at' => '2022-06-29 08:21:06',
                'updated_at' => '2022-06-29 08:21:06',
                'deleted_at' => NULL,
                'internal_notes' => NULL,
                'external_notes' => NULL,
                'accommodation_notes' => NULL,
                'activity_notes' => NULL,
                'flight_notes' => NULL,
                'transport_notes' => NULL,
                'is_travelling' => 1,
                'is_charged' => 1,
            ),
            11 => 
            array (
                'id' => 12,
                'order_id' => 6,
                'customer_id' => 27,
                'tour_cost' => '3498.00',
                'single_occupancy_surcharge' => '419.67',
                'travel_insurer' => NULL,
                'policy_number' => NULL,
                'created_at' => '2022-06-29 08:21:07',
                'updated_at' => '2022-06-29 08:21:07',
                'deleted_at' => NULL,
                'internal_notes' => NULL,
                'external_notes' => NULL,
                'accommodation_notes' => NULL,
                'activity_notes' => NULL,
                'flight_notes' => NULL,
                'transport_notes' => NULL,
                'is_travelling' => 1,
                'is_charged' => 1,
            ),
            12 => 
            array (
                'id' => 13,
                'order_id' => 6,
                'customer_id' => 21,
                'tour_cost' => '3498.00',
                'single_occupancy_surcharge' => '419.67',
                'travel_insurer' => NULL,
                'policy_number' => NULL,
                'created_at' => '2022-06-29 08:21:09',
                'updated_at' => '2022-06-29 08:21:09',
                'deleted_at' => NULL,
                'internal_notes' => NULL,
                'external_notes' => NULL,
                'accommodation_notes' => NULL,
                'activity_notes' => NULL,
                'flight_notes' => NULL,
                'transport_notes' => NULL,
                'is_travelling' => 1,
                'is_charged' => 1,
            ),
            13 => 
            array (
                'id' => 14,
                'order_id' => 7,
                'customer_id' => 13,
                'tour_cost' => '3498.00',
                'single_occupancy_surcharge' => '419.67',
                'travel_insurer' => NULL,
                'policy_number' => NULL,
                'created_at' => '2022-09-14 11:22:23',
                'updated_at' => '2022-09-20 10:28:22',
                'deleted_at' => NULL,
                'internal_notes' => NULL,
                'external_notes' => NULL,
                'accommodation_notes' => 'twin room please if possible',
                'activity_notes' => NULL,
                'flight_notes' => NULL,
                'transport_notes' => NULL,
                'is_travelling' => 1,
                'is_charged' => 1,
            ),
            14 => 
            array (
                'id' => 15,
                'order_id' => 7,
                'customer_id' => 31,
                'tour_cost' => '3498.00',
                'single_occupancy_surcharge' => '419.67',
                'travel_insurer' => NULL,
                'policy_number' => NULL,
                'created_at' => '2022-09-14 11:22:24',
                'updated_at' => '2022-09-14 11:22:24',
                'deleted_at' => NULL,
                'internal_notes' => NULL,
                'external_notes' => NULL,
                'accommodation_notes' => NULL,
                'activity_notes' => NULL,
                'flight_notes' => NULL,
                'transport_notes' => NULL,
                'is_travelling' => 1,
                'is_charged' => 1,
            ),
            15 => 
            array (
                'id' => 16,
                'order_id' => 8,
                'customer_id' => 16,
                'tour_cost' => '3498.00',
                'single_occupancy_surcharge' => '0.00',
                'travel_insurer' => NULL,
                'policy_number' => NULL,
                'created_at' => '2022-09-20 10:39:17',
                'updated_at' => '2022-09-20 10:39:17',
                'deleted_at' => NULL,
                'internal_notes' => NULL,
                'external_notes' => NULL,
                'accommodation_notes' => NULL,
                'activity_notes' => NULL,
                'flight_notes' => NULL,
                'transport_notes' => NULL,
                'is_travelling' => 1,
                'is_charged' => 1,
            ),
            16 => 
            array (
                'id' => 17,
                'order_id' => 8,
                'customer_id' => 32,
                'tour_cost' => '3498.00',
                'single_occupancy_surcharge' => '0.00',
                'travel_insurer' => NULL,
                'policy_number' => NULL,
                'created_at' => '2022-09-20 10:39:17',
                'updated_at' => '2022-09-20 10:39:17',
                'deleted_at' => NULL,
                'internal_notes' => NULL,
                'external_notes' => NULL,
                'accommodation_notes' => NULL,
                'activity_notes' => NULL,
                'flight_notes' => NULL,
                'transport_notes' => NULL,
                'is_travelling' => 1,
                'is_charged' => 0,
            ),
            17 => 
            array (
                'id' => 18,
                'order_id' => 8,
                'customer_id' => 33,
                'tour_cost' => '3498.00',
                'single_occupancy_surcharge' => '0.00',
                'travel_insurer' => NULL,
                'policy_number' => NULL,
                'created_at' => '2022-09-20 10:39:18',
                'updated_at' => '2022-09-20 10:39:18',
                'deleted_at' => NULL,
                'internal_notes' => NULL,
                'external_notes' => NULL,
                'accommodation_notes' => NULL,
                'activity_notes' => NULL,
                'flight_notes' => NULL,
                'transport_notes' => NULL,
                'is_travelling' => 1,
                'is_charged' => 1,
            ),
            18 => 
            array (
                'id' => 19,
                'order_id' => 9,
                'customer_id' => 34,
                'tour_cost' => '1199.00',
                'single_occupancy_surcharge' => '295.00',
                'travel_insurer' => NULL,
                'policy_number' => NULL,
                'created_at' => '2022-09-20 19:33:03',
                'updated_at' => '2022-09-20 19:33:03',
                'deleted_at' => NULL,
                'internal_notes' => NULL,
                'external_notes' => NULL,
                'accommodation_notes' => NULL,
                'activity_notes' => NULL,
                'flight_notes' => NULL,
                'transport_notes' => NULL,
                'is_travelling' => 1,
                'is_charged' => 1,
            ),
            19 => 
            array (
                'id' => 20,
                'order_id' => 9,
                'customer_id' => 35,
                'tour_cost' => '1199.00',
                'single_occupancy_surcharge' => '295.00',
                'travel_insurer' => NULL,
                'policy_number' => NULL,
                'created_at' => '2022-09-20 19:33:03',
                'updated_at' => '2022-09-20 19:33:03',
                'deleted_at' => NULL,
                'internal_notes' => NULL,
                'external_notes' => NULL,
                'accommodation_notes' => NULL,
                'activity_notes' => NULL,
                'flight_notes' => NULL,
                'transport_notes' => NULL,
                'is_travelling' => 1,
                'is_charged' => 1,
            ),
            20 => 
            array (
                'id' => 21,
                'order_id' => 10,
                'customer_id' => 36,
                'tour_cost' => '150.00',
                'single_occupancy_surcharge' => '0.00',
                'travel_insurer' => NULL,
                'policy_number' => NULL,
                'created_at' => '2022-09-21 09:24:11',
                'updated_at' => '2022-09-21 09:24:11',
                'deleted_at' => NULL,
                'internal_notes' => NULL,
                'external_notes' => NULL,
                'accommodation_notes' => NULL,
                'activity_notes' => NULL,
                'flight_notes' => NULL,
                'transport_notes' => NULL,
                'is_travelling' => 1,
                'is_charged' => 1,
            ),
            21 => 
            array (
                'id' => 22,
                'order_id' => 11,
                'customer_id' => 37,
                'tour_cost' => '150.00',
                'single_occupancy_surcharge' => '0.00',
                'travel_insurer' => NULL,
                'policy_number' => NULL,
                'created_at' => '2022-09-21 09:27:53',
                'updated_at' => '2022-09-21 09:27:53',
                'deleted_at' => NULL,
                'internal_notes' => NULL,
                'external_notes' => NULL,
                'accommodation_notes' => NULL,
                'activity_notes' => NULL,
                'flight_notes' => NULL,
                'transport_notes' => NULL,
                'is_travelling' => 1,
                'is_charged' => 1,
            ),
            22 => 
            array (
                'id' => 23,
                'order_id' => 12,
                'customer_id' => 38,
                'tour_cost' => '150.00',
                'single_occupancy_surcharge' => '0.00',
                'travel_insurer' => NULL,
                'policy_number' => NULL,
                'created_at' => '2022-09-21 09:30:33',
                'updated_at' => '2022-09-21 09:30:33',
                'deleted_at' => NULL,
                'internal_notes' => NULL,
                'external_notes' => NULL,
                'accommodation_notes' => NULL,
                'activity_notes' => NULL,
                'flight_notes' => NULL,
                'transport_notes' => NULL,
                'is_travelling' => 1,
                'is_charged' => 1,
            ),
            23 => 
            array (
                'id' => 24,
                'order_id' => 13,
                'customer_id' => 39,
                'tour_cost' => '150.00',
                'single_occupancy_surcharge' => '0.00',
                'travel_insurer' => NULL,
                'policy_number' => NULL,
                'created_at' => '2022-09-21 09:31:56',
                'updated_at' => '2022-09-21 09:31:56',
                'deleted_at' => NULL,
                'internal_notes' => NULL,
                'external_notes' => NULL,
                'accommodation_notes' => NULL,
                'activity_notes' => NULL,
                'flight_notes' => NULL,
                'transport_notes' => NULL,
                'is_travelling' => 1,
                'is_charged' => 1,
            ),
            24 => 
            array (
                'id' => 25,
                'order_id' => 13,
                'customer_id' => 40,
                'tour_cost' => '150.00',
                'single_occupancy_surcharge' => '0.00',
                'travel_insurer' => NULL,
                'policy_number' => NULL,
                'created_at' => '2022-09-21 09:31:57',
                'updated_at' => '2022-09-21 09:31:57',
                'deleted_at' => NULL,
                'internal_notes' => NULL,
                'external_notes' => NULL,
                'accommodation_notes' => NULL,
                'activity_notes' => NULL,
                'flight_notes' => NULL,
                'transport_notes' => NULL,
                'is_travelling' => 1,
                'is_charged' => 1,
            ),
            25 => 
            array (
                'id' => 26,
                'order_id' => 14,
                'customer_id' => 41,
                'tour_cost' => '1199.00',
                'single_occupancy_surcharge' => '295.00',
                'travel_insurer' => NULL,
                'policy_number' => NULL,
                'created_at' => '2022-09-21 11:45:17',
                'updated_at' => '2022-09-21 11:45:17',
                'deleted_at' => NULL,
                'internal_notes' => NULL,
                'external_notes' => NULL,
                'accommodation_notes' => NULL,
                'activity_notes' => NULL,
                'flight_notes' => NULL,
                'transport_notes' => NULL,
                'is_travelling' => 1,
                'is_charged' => 1,
            ),
            26 => 
            array (
                'id' => 27,
                'order_id' => 15,
                'customer_id' => 6,
                'tour_cost' => '1199.00',
                'single_occupancy_surcharge' => '295.00',
                'travel_insurer' => NULL,
                'policy_number' => NULL,
                'created_at' => '2022-09-21 12:44:00',
                'updated_at' => '2022-09-21 12:44:00',
                'deleted_at' => NULL,
                'internal_notes' => NULL,
                'external_notes' => NULL,
                'accommodation_notes' => NULL,
                'activity_notes' => NULL,
                'flight_notes' => NULL,
                'transport_notes' => NULL,
                'is_travelling' => 1,
                'is_charged' => 1,
            ),
        ));
        
        
    }
}