@include('partials.fields.text', ['name' => 'Name', 'field' => 'name', 'value' => $name ?? null,])
@include('partials.fields.text', ['name' => 'Email Address', 'field' => 'email', 'value' => $email ?? null, ])
@include('partials.fields.password', ['name' => 'Password', 'field' => 'password', ])
@include('partials.fields.password', ['name' => 'Confirm Password', 'field' => 'password_confirmed', ])
@include('partials.fields.file', ['name' => 'Avatar', 'field' => 'avatar',])
@include('partials.fields.submit')
