<?php

namespace Database\Seeders;
use Illuminate\Database\Seeder;

class MenuItemsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('menu_items')->delete();
        
        \DB::table('menu_items')->insert(array (
            0 => 
            array (
                'id' => 1,
                'menu_id' => 1,
                'title' => 'Dashboard',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-boat',
                'color' => NULL,
                'parent_id' => NULL,
                'order' => 1,
                'created_at' => '2020-10-13 13:08:28',
                'updated_at' => '2020-10-13 13:08:28',
                'route' => 'voyager.dashboard',
                'parameters' => NULL,
            ),
            1 => 
            array (
                'id' => 2,
                'menu_id' => 1,
                'title' => 'Media',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-images',
                'color' => NULL,
                'parent_id' => 1,
                'order' => 4,
                'created_at' => '2020-10-13 13:08:28',
                'updated_at' => '2021-02-04 07:41:28',
                'route' => 'voyager.media.index',
                'parameters' => NULL,
            ),
            2 => 
            array (
                'id' => 3,
                'menu_id' => 1,
                'title' => 'Users',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-person',
                'color' => NULL,
                'parent_id' => 1,
                'order' => 3,
                'created_at' => '2020-10-13 13:08:28',
                'updated_at' => '2021-02-04 07:41:28',
                'route' => 'voyager.users.index',
                'parameters' => NULL,
            ),
            3 => 
            array (
                'id' => 4,
                'menu_id' => 1,
                'title' => 'Roles',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-lock',
                'color' => NULL,
                'parent_id' => 1,
                'order' => 2,
                'created_at' => '2020-10-13 13:08:28',
                'updated_at' => '2021-02-04 07:41:28',
                'route' => 'voyager.roles.index',
                'parameters' => NULL,
            ),
            4 => 
            array (
                'id' => 5,
                'menu_id' => 1,
                'title' => 'Tools',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-tools',
                'color' => NULL,
                'parent_id' => NULL,
                'order' => 2,
                'created_at' => '2020-10-13 13:08:28',
                'updated_at' => '2021-02-04 07:46:06',
                'route' => NULL,
                'parameters' => NULL,
            ),
            5 => 
            array (
                'id' => 6,
                'menu_id' => 1,
                'title' => 'Menu Builder',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-list',
                'color' => NULL,
                'parent_id' => 5,
                'order' => 1,
                'created_at' => '2020-10-13 13:08:28',
                'updated_at' => '2020-10-22 13:59:56',
                'route' => 'voyager.menus.index',
                'parameters' => NULL,
            ),
            6 => 
            array (
                'id' => 7,
                'menu_id' => 1,
                'title' => 'Database',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-data',
                'color' => NULL,
                'parent_id' => 5,
                'order' => 2,
                'created_at' => '2020-10-13 13:08:28',
                'updated_at' => '2021-02-04 07:47:15',
                'route' => 'voyager.database.index',
                'parameters' => NULL,
            ),
            7 => 
            array (
                'id' => 8,
                'menu_id' => 1,
                'title' => 'Compass',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-compass',
                'color' => NULL,
                'parent_id' => 5,
                'order' => 4,
                'created_at' => '2020-10-13 13:08:28',
                'updated_at' => '2021-02-04 07:47:13',
                'route' => 'voyager.compass.index',
                'parameters' => NULL,
            ),
            8 => 
            array (
                'id' => 9,
                'menu_id' => 1,
                'title' => 'BREAD',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-bread',
                'color' => NULL,
                'parent_id' => 5,
                'order' => 3,
                'created_at' => '2020-10-13 13:08:28',
                'updated_at' => '2021-02-04 07:47:15',
                'route' => 'voyager.bread.index',
                'parameters' => NULL,
            ),
            9 => 
            array (
                'id' => 10,
                'menu_id' => 1,
                'title' => 'Settings',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-settings',
                'color' => NULL,
                'parent_id' => 1,
                'order' => 1,
                'created_at' => '2020-10-13 13:08:28',
                'updated_at' => '2021-02-04 07:41:28',
                'route' => 'voyager.settings.index',
                'parameters' => NULL,
            ),
            10 => 
            array (
                'id' => 11,
                'menu_id' => 1,
                'title' => 'Hooks',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-hook',
                'color' => NULL,
                'parent_id' => 5,
                'order' => 5,
                'created_at' => '2020-10-13 13:08:28',
                'updated_at' => '2020-10-22 13:59:56',
                'route' => 'voyager.hooks',
                'parameters' => NULL,
            ),
            11 => 
            array (
                'id' => 14,
                'menu_id' => 1,
                'title' => 'Accommodation Inventories',
                'url' => '',
                'target' => '_self',
                'icon_class' => NULL,
                'color' => NULL,
                'parent_id' => 25,
                'order' => 4,
                'created_at' => '2020-10-15 09:21:00',
                'updated_at' => '2021-02-04 22:44:59',
                'route' => 'voyager.accommodation-inventories.index',
                'parameters' => NULL,
            ),
            12 => 
            array (
                'id' => 15,
                'menu_id' => 1,
                'title' => 'Board Types',
                'url' => '',
                'target' => '_self',
                'icon_class' => NULL,
                'color' => NULL,
                'parent_id' => 25,
                'order' => 1,
                'created_at' => '2020-10-15 10:03:54',
                'updated_at' => '2021-02-04 22:44:57',
                'route' => 'voyager.board-types.index',
                'parameters' => NULL,
            ),
            13 => 
            array (
                'id' => 16,
                'menu_id' => 1,
                'title' => 'Room Types',
                'url' => '',
                'target' => '_self',
                'icon_class' => NULL,
                'color' => NULL,
                'parent_id' => 25,
                'order' => 2,
                'created_at' => '2020-10-15 11:16:35',
                'updated_at' => '2021-02-04 22:44:59',
                'route' => 'voyager.room-types.index',
                'parameters' => NULL,
            ),
            14 => 
            array (
                'id' => 17,
                'menu_id' => 1,
                'title' => 'Model Logs',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-logbook',
                'color' => NULL,
                'parent_id' => 5,
                'order' => 6,
                'created_at' => '2020-10-15 14:41:14',
                'updated_at' => '2021-02-04 07:47:04',
                'route' => 'voyager.model_log.index',
                'parameters' => NULL,
            ),
            15 => 
            array (
                'id' => 19,
                'menu_id' => 1,
                'title' => 'Regions',
                'url' => '',
                'target' => '_self',
                'icon_class' => NULL,
                'color' => NULL,
                'parent_id' => 24,
                'order' => 2,
                'created_at' => '2020-10-22 12:22:09',
                'updated_at' => '2021-02-04 22:45:35',
                'route' => 'voyager.regions.index',
                'parameters' => NULL,
            ),
            16 => 
            array (
                'id' => 20,
                'menu_id' => 1,
                'title' => 'Countries',
                'url' => '',
                'target' => '_self',
                'icon_class' => NULL,
                'color' => NULL,
                'parent_id' => 24,
                'order' => 1,
                'created_at' => '2020-10-22 12:25:43',
                'updated_at' => '2021-02-04 22:45:33',
                'route' => 'voyager.countries.index',
                'parameters' => NULL,
            ),
            17 => 
            array (
                'id' => 21,
                'menu_id' => 1,
                'title' => 'Location Types',
                'url' => '',
                'target' => '_self',
                'icon_class' => NULL,
                'color' => NULL,
                'parent_id' => 24,
                'order' => 3,
                'created_at' => '2020-10-22 12:52:30',
                'updated_at' => '2021-02-04 22:45:35',
                'route' => 'voyager.location-types.index',
                'parameters' => NULL,
            ),
            18 => 
            array (
                'id' => 22,
                'menu_id' => 1,
                'title' => 'Locations',
                'url' => '',
                'target' => '_self',
                'icon_class' => NULL,
                'color' => NULL,
                'parent_id' => 24,
                'order' => 4,
                'created_at' => '2020-10-22 13:00:12',
                'updated_at' => '2021-02-04 22:45:35',
                'route' => 'voyager.locations.index',
                'parameters' => NULL,
            ),
            19 => 
            array (
                'id' => 24,
                'menu_id' => 1,
                'title' => 'Locations',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-world',
                'color' => '#000000',
                'parent_id' => NULL,
                'order' => 6,
                'created_at' => '2020-10-22 13:59:43',
                'updated_at' => '2021-02-12 08:49:02',
                'route' => NULL,
                'parameters' => '',
            ),
            20 => 
            array (
                'id' => 25,
                'menu_id' => 1,
                'title' => 'Accommodation',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-company',
                'color' => '#000000',
                'parent_id' => NULL,
                'order' => 9,
                'created_at' => '2020-10-22 14:00:33',
                'updated_at' => '2021-02-09 06:20:15',
                'route' => NULL,
                'parameters' => '',
            ),
            21 => 
            array (
                'id' => 26,
                'menu_id' => 1,
                'title' => 'Accommodation',
                'url' => '',
                'target' => '_self',
                'icon_class' => NULL,
                'color' => '#000000',
                'parent_id' => 25,
                'order' => 3,
                'created_at' => '2020-10-22 14:27:11',
                'updated_at' => '2021-02-04 22:44:59',
                'route' => 'voyager.accommodations.index',
                'parameters' => 'null',
            ),
            22 => 
            array (
                'id' => 30,
                'menu_id' => 1,
                'title' => 'Airlines',
                'url' => '',
                'target' => '_self',
                'icon_class' => NULL,
                'color' => NULL,
                'parent_id' => 33,
                'order' => 2,
                'created_at' => '2020-11-03 10:45:18',
                'updated_at' => '2021-02-04 22:45:07',
                'route' => 'voyager.airlines.index',
                'parameters' => NULL,
            ),
            23 => 
            array (
                'id' => 31,
                'menu_id' => 1,
                'title' => 'Airports',
                'url' => '',
                'target' => '_self',
                'icon_class' => NULL,
                'color' => NULL,
                'parent_id' => 33,
                'order' => 3,
                'created_at' => '2020-11-03 10:47:14',
                'updated_at' => '2021-02-04 22:45:09',
                'route' => 'voyager.airports.index',
                'parameters' => NULL,
            ),
            24 => 
            array (
                'id' => 32,
                'menu_id' => 1,
                'title' => 'Flights',
                'url' => '',
                'target' => '_self',
                'icon_class' => NULL,
                'color' => NULL,
                'parent_id' => 33,
                'order' => 4,
                'created_at' => '2020-11-03 10:47:42',
                'updated_at' => '2021-02-04 22:45:09',
                'route' => 'voyager.flights.index',
                'parameters' => NULL,
            ),
            25 => 
            array (
                'id' => 33,
                'menu_id' => 1,
                'title' => 'Flights',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-paper-plane',
                'color' => '#000000',
                'parent_id' => NULL,
                'order' => 10,
                'created_at' => '2020-11-03 11:02:49',
                'updated_at' => '2021-02-09 06:20:15',
                'route' => NULL,
                'parameters' => '',
            ),
            26 => 
            array (
                'id' => 34,
                'menu_id' => 1,
                'title' => 'Travel Classes',
                'url' => '',
                'target' => '_self',
                'icon_class' => NULL,
                'color' => NULL,
                'parent_id' => 33,
                'order' => 1,
                'created_at' => '2020-11-03 16:06:58',
                'updated_at' => '2021-02-04 22:45:04',
                'route' => 'voyager.travel-classes.index',
                'parameters' => NULL,
            ),
            27 => 
            array (
                'id' => 35,
                'menu_id' => 1,
                'title' => 'Flight Inventories',
                'url' => '',
                'target' => '_self',
                'icon_class' => NULL,
                'color' => NULL,
                'parent_id' => 33,
                'order' => 5,
                'created_at' => '2020-11-03 18:21:33',
                'updated_at' => '2021-02-04 22:45:09',
                'route' => 'voyager.flight-inventories.index',
                'parameters' => NULL,
            ),
            28 => 
            array (
                'id' => 36,
                'menu_id' => 1,
                'title' => 'Activity Types',
                'url' => '',
                'target' => '_self',
                'icon_class' => NULL,
                'color' => NULL,
                'parent_id' => 40,
                'order' => 1,
                'created_at' => '2020-11-04 14:48:19',
                'updated_at' => '2021-02-04 22:44:49',
                'route' => 'voyager.activity-types.index',
                'parameters' => NULL,
            ),
            29 => 
            array (
                'id' => 37,
                'menu_id' => 1,
                'title' => 'Ticket Types',
                'url' => '',
                'target' => '_self',
                'icon_class' => NULL,
                'color' => NULL,
                'parent_id' => 40,
                'order' => 2,
                'created_at' => '2020-11-04 16:01:42',
                'updated_at' => '2021-02-09 06:20:04',
                'route' => 'voyager.ticket-types.index',
                'parameters' => NULL,
            ),
            30 => 
            array (
                'id' => 38,
                'menu_id' => 1,
                'title' => 'Activities',
                'url' => '',
                'target' => '_self',
                'icon_class' => NULL,
                'color' => NULL,
                'parent_id' => 40,
                'order' => 3,
                'created_at' => '2020-11-04 16:02:46',
                'updated_at' => '2021-02-09 06:20:04',
                'route' => 'voyager.activities.index',
                'parameters' => NULL,
            ),
            31 => 
            array (
                'id' => 39,
                'menu_id' => 1,
                'title' => 'Activity Inventories',
                'url' => '',
                'target' => '_self',
                'icon_class' => NULL,
                'color' => NULL,
                'parent_id' => 40,
                'order' => 4,
                'created_at' => '2020-11-04 18:08:44',
                'updated_at' => '2021-02-09 06:20:04',
                'route' => 'voyager.activity-inventories.index',
                'parameters' => NULL,
            ),
            32 => 
            array (
                'id' => 40,
                'menu_id' => 1,
                'title' => 'Activities',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-beer',
                'color' => '#000000',
                'parent_id' => NULL,
                'order' => 8,
                'created_at' => '2020-11-04 18:59:32',
                'updated_at' => '2021-02-09 06:20:15',
                'route' => NULL,
                'parameters' => '',
            ),
            33 => 
            array (
                'id' => 41,
                'menu_id' => 1,
                'title' => 'Transports',
                'url' => '',
                'target' => '_self',
                'icon_class' => NULL,
                'color' => '#000000',
                'parent_id' => 45,
                'order' => 3,
                'created_at' => '2020-11-05 12:08:07',
                'updated_at' => '2021-02-04 22:45:18',
                'route' => 'voyager.transports.index',
                'parameters' => 'null',
            ),
            34 => 
            array (
                'id' => 42,
                'menu_id' => 1,
                'title' => 'Transport Types',
                'url' => '',
                'target' => '_self',
                'icon_class' => NULL,
                'color' => NULL,
                'parent_id' => 45,
                'order' => 2,
                'created_at' => '2020-11-05 12:11:44',
                'updated_at' => '2021-02-04 22:45:18',
                'route' => 'voyager.transport-types.index',
                'parameters' => NULL,
            ),
            35 => 
            array (
                'id' => 43,
                'menu_id' => 1,
                'title' => 'Operators',
                'url' => '',
                'target' => '_self',
                'icon_class' => NULL,
                'color' => NULL,
                'parent_id' => 45,
                'order' => 1,
                'created_at' => '2020-11-05 12:36:33',
                'updated_at' => '2021-02-04 22:45:18',
                'route' => 'voyager.operators.index',
                'parameters' => NULL,
            ),
            36 => 
            array (
                'id' => 44,
                'menu_id' => 1,
                'title' => 'Transport Inventories',
                'url' => '',
                'target' => '_self',
                'icon_class' => NULL,
                'color' => NULL,
                'parent_id' => 45,
                'order' => 4,
                'created_at' => '2020-11-05 12:38:06',
                'updated_at' => '2020-11-05 12:44:43',
                'route' => 'voyager.transport-inventories.index',
                'parameters' => NULL,
            ),
            37 => 
            array (
                'id' => 45,
                'menu_id' => 1,
                'title' => 'Transports',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-truck',
                'color' => '#000000',
                'parent_id' => NULL,
                'order' => 11,
                'created_at' => '2020-11-05 12:44:30',
                'updated_at' => '2021-02-09 06:20:15',
                'route' => NULL,
                'parameters' => '',
            ),
            38 => 
            array (
                'id' => 47,
                'menu_id' => 1,
                'title' => 'Tours',
                'url' => '',
                'target' => '_self',
                'icon_class' => NULL,
                'color' => NULL,
                'parent_id' => 53,
                'order' => 2,
                'created_at' => '2020-11-16 08:43:02',
                'updated_at' => '2021-02-04 22:44:46',
                'route' => 'voyager.tours.index',
                'parameters' => NULL,
            ),
            39 => 
            array (
                'id' => 48,
                'menu_id' => 1,
                'title' => 'Events',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-tag',
                'color' => '#000000',
                'parent_id' => NULL,
                'order' => 5,
                'created_at' => '2020-11-20 17:12:37',
                'updated_at' => '2021-02-12 08:49:02',
                'route' => 'voyager.events.index',
                'parameters' => 'null',
            ),
            40 => 
            array (
                'id' => 51,
                'menu_id' => 1,
                'title' => 'Payment Schedules',
                'url' => '',
                'target' => '_self',
                'icon_class' => NULL,
                'color' => NULL,
                'parent_id' => 60,
                'order' => 4,
                'created_at' => '2020-11-23 14:02:22',
                'updated_at' => '2021-02-12 08:48:43',
                'route' => 'voyager.payment-schedules.index',
                'parameters' => NULL,
            ),
            41 => 
            array (
                'id' => 52,
                'menu_id' => 1,
                'title' => 'Payment Installments',
                'url' => '',
                'target' => '_self',
                'icon_class' => NULL,
                'color' => NULL,
                'parent_id' => 60,
                'order' => 5,
                'created_at' => '2020-11-23 14:03:41',
                'updated_at' => '2021-02-12 08:48:47',
                'route' => 'voyager.payment-installments.index',
                'parameters' => NULL,
            ),
            42 => 
            array (
                'id' => 53,
                'menu_id' => 1,
                'title' => 'Tours',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-compass',
                'color' => '#000000',
                'parent_id' => NULL,
                'order' => 7,
                'created_at' => '2020-11-23 14:13:35',
                'updated_at' => '2021-02-09 06:20:15',
                'route' => NULL,
                'parameters' => '',
            ),
            43 => 
            array (
                'id' => 54,
                'menu_id' => 1,
                'title' => 'Orders',
                'url' => '',
                'target' => '_self',
                'icon_class' => NULL,
                'color' => NULL,
                'parent_id' => 60,
                'order' => 2,
                'created_at' => '2020-11-25 15:38:18',
                'updated_at' => '2021-02-04 22:45:54',
                'route' => 'voyager.orders.index',
                'parameters' => NULL,
            ),
            44 => 
            array (
                'id' => 56,
                'menu_id' => 1,
                'title' => 'Order Statuses',
                'url' => '',
                'target' => '_self',
                'icon_class' => NULL,
                'color' => NULL,
                'parent_id' => 60,
                'order' => 1,
                'created_at' => '2020-11-26 08:51:04',
                'updated_at' => '2021-02-04 22:45:47',
                'route' => 'voyager.order-statuses.index',
                'parameters' => NULL,
            ),
            45 => 
            array (
                'id' => 57,
                'menu_id' => 1,
                'title' => 'Customers',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-people',
                'color' => '#000000',
                'parent_id' => 63,
                'order' => 1,
                'created_at' => '2020-11-26 09:18:56',
                'updated_at' => '2021-02-09 06:20:15',
                'route' => 'voyager.customers.index',
                'parameters' => 'null',
            ),
            46 => 
            array (
                'id' => 59,
                'menu_id' => 1,
                'title' => 'Invoices',
                'url' => '',
                'target' => '_self',
                'icon_class' => NULL,
                'color' => NULL,
                'parent_id' => 60,
                'order' => 3,
                'created_at' => '2020-11-27 09:18:30',
                'updated_at' => '2021-02-04 22:45:54',
                'route' => 'voyager.invoices.index',
                'parameters' => NULL,
            ),
            47 => 
            array (
                'id' => 60,
                'menu_id' => 1,
                'title' => 'Orders',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-credit-cards',
                'color' => '#000000',
                'parent_id' => NULL,
                'order' => 4,
                'created_at' => '2020-12-04 16:33:56',
                'updated_at' => '2021-02-09 06:20:15',
                'route' => NULL,
                'parameters' => '',
            ),
            48 => 
            array (
                'id' => 61,
                'menu_id' => 1,
                'title' => 'Tour Component Types',
                'url' => '',
                'target' => '_self',
                'icon_class' => NULL,
                'color' => NULL,
                'parent_id' => 53,
                'order' => 1,
                'created_at' => '2020-12-08 15:33:09',
                'updated_at' => '2021-02-04 22:44:46',
                'route' => 'voyager.tour-component-types.index',
                'parameters' => NULL,
            ),
            49 => 
            array (
                'id' => 63,
                'menu_id' => 1,
                'title' => 'Customers',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-people',
                'color' => '#000000',
                'parent_id' => NULL,
                'order' => 3,
                'created_at' => '2021-02-09 06:19:42',
                'updated_at' => '2021-02-11 21:17:29',
                'route' => NULL,
                'parameters' => '',
            ),
        ));
        
        
    }
}
